### ISSUE TITLE
Genbil not able to catch queries on a 2012 environment

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#100]
Hello Seddryck,

a similar issue  than #97 occurs with genbi not executing queries to catch test cases and being in an 2012-environment. Maybe it's related? The Error message is:

Source: NBi.Core
Type: System.IO.FileNotFoundException
Description:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

Cheers,
Tilo

**Comment by Seddryck** [comment]
just copy paste the dll Microsoft.analysisServices.adomdClient that you have in your "framework" folder into the Genbi folder. It will solve your problem.

**Comment by Seddryck** [comment]
@FuegoArtificial, does it fix your problem to copy/paste the dll into the directory? If yes, I'll add it in the next build.

**Comment by FuegoArtificial** [comment]
@Seddryck Yes, it helped. I took the dll from in different SQL2k14 server, first, because I basically got the idea on how to solve the issue. I checked it with "your" dll and it works like a charm :)

**Comment by Seddryck** [comment]
Merged to master will be part of v1.11
