### ISSUE TITLE
Display column names in error message

### ISSUE THREAD

**Issue by FuegoArtificial** [Seddryck/NBi#105]
Hi Seddryck,

I would like to ask for a feature: Could you provide the display of column names within error messages? Right now, we get the information if it is a key or value-column. The Name would be helpful :)

For example:

```
Expected: 
ResultSet with 1 row

KEY (Text) | VALUE (Numeric) (+/- 15.00%)
---------- | ----------------------------- 
RowCount | 273649 
```

If I would know, which values are in the values columns (especially if there are more than one), I could be able to communicate easier about the issues.

Thanks :)
Tilo

**Comment by Seddryck** [comment]
Should be relatively easy to add this.

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.15.0-ci.18

This preview also includes #241

**Comment by aniketh02** [comment]
I have downloaded the code from 
https://github.com/Seddryck/NBi/tree/feature/Compare_result-sets_by_column_name_(%23241)
and build it in my local machine.
But still I am not able to see the column names in the result. Am I doing the right way?

`	<column name="productKey"  role="key" type="text" ></column>
        <column name ="ProductAlternateKey" role="value" type="text" />
		<column name="EnglishProductName" role="value" type="text" />
        <column name="StandardCost" role="value" type="numeric" /> `

**Comment by Seddryck** [comment]
This branch is not merged with the branch where the feature you're looking for is implemented: https://github.com/Seddryck/NBi/tree/feature/Display_column_name_(%23105) 

Personnaly, I'd try this build to get this feature: https://ci.appveyor.com/project/Seddryck/nbi/build/1.15.0-ci.27/artifacts 

It should work, but (there is a "but") ... I've many issues with the rest-api and this feature was implemented within this work-package ... I'll need to rebranch and play a lot of git to get this feature in the release 1.15 (most of the rest-api features will be discarded).

PS: Good news that you can build this on your own machine

**Comment by FuegoArtificial** [comment]
It works for me with build/version number 1.15.0.93.

  Expected: 
ResultSet with 1 row

     #0 (ImportantMeasure)
     KEY (Text)           
     --------------------- 
     2

**Comment by Seddryck** [comment]
Good news :-)

**Comment by aniketh02** [comment]
Yeah Its Working. Thanks.

**Comment by Seddryck** [comment]
Available in beta: https://github.com/Seddryck/NBi/releases/tag/v1.15-beta
