### ISSUE TITLE
Question: How to build a test to test existence of a table

### ISSUE THREAD

**Issue by FuegoArtificial** [Seddryck/NBi#108]
Dear Seddryck, dear NBi-users,

how would you set up a test, which checks if a table exists in a database?
Im trying to achieve this with the following test.

```
<test name="test">
    <category>test</category>
    <system-under-test>
        <structure>
            <table caption="DimCountry" perspective="dbo" connectionString="@Datamart"/>
        </structure>
    </system-under-test>
    <assert>
        <exists />
    </assert>
</test>
```

I tried to derive this test from the two pages of documentation:
[General exist-tests](http://www.nbi.io/docs/model-exists/)
[Using the structure-tag](http://www.nbi.io/docs/model-objects/)

The reference `@Datamart` is given.

The error I get by now is

```
NBi.NUnit.Runtime.TestSuite.test:
System.InvalidOperationException : Sequence contains no matching element
```

Do you have an idea how to write the test correctly?

Context: The scenario is that after a deployment all tables of the QA-instance must exist in the PROD-instance.

Cheers

**Comment by Seddryck** [comment]
Replace the tag table by tables and the assertion exists by contain, it should work. 

I will check what's wrong with exists.

**Comment by FuegoArtificial** [comment]
I just tested both ways again and they work, now. 
What did I do?
While trying to use the tables-tag, I realized it was not available in the schema. Checking for the version of NBi it stated version 1.10.0.14xx. After Updating NBi to 1.10.0.19, both approaches worked fine.
Sorry for the confusion!

**Comment by Seddryck** [comment]
I really enjoy this kind of self-fixing-bugs
