### ISSUE TITLE
Genbi generates invalid element 'default' in 'row-count' and 'equalTo' assertions when tests are preexisting

### ISSUE THREAD

**Issue by DonatasLTU** [Seddryck/NBi#117]
Hi,

There is a bug. When you open test suite in Genbi, already having few tests and view their code, they are syntactically correct ( as you can see in the first picture ). Then you generate a test using a template and save test suite with the same name. When you try reopen same test suite, you get an error that there are errors in the first few tests ( additional line has been added in everyeach of these tests to ASSERT block :         <Default apply-to="assert" />  ) . So you must remove these lines in order to get tests working. 
![bug1](https://cloud.githubusercontent.com/assets/14074706/9851427/4198108c-5b01-11e5-8e4a-8f5bf77ee60f.jpg)
![bug2](https://cloud.githubusercontent.com/assets/14074706/9851429/41a70970-5b01-11e5-8f29-4fbb87e9756b.jpg)
![bug3](https://cloud.githubusercontent.com/assets/14074706/9851428/4199f096-5b01-11e5-89d0-71cfdbd73e32.jpg)

**Comment by Seddryck** [comment]
Indeed there is a bug. I can reproduce it but I've some troubles to isolate it. Will take a look.

**Comment by Seddryck** [comment]
Bug should be fixed in the binaries available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99071 

Will be appreciated if you confirm the bug fix. Thx for the report.

**Comment by DonatasLTU** [comment]
Hi, Cedric,

How could I confirm the bug fix?

**Comment by Seddryck** [comment]
On the link specified above, you have a tab named artefacts (right of the screen) Just click on it and you will be able to download a new version of genbi (including the bug fix).
