### ISSUE TITLE
Running macros on Genbi for the second time rises an error

### ISSUE THREAD

**Issue by DonatasLTU** [Seddryck/NBi#118]
Running macros on Genbi for the second time rises an error
![bug4](https://cloud.githubusercontent.com/assets/14074706/9870108/dd51ceba-5b91-11e5-9780-381abaa4a209.jpg)

**Comment by Seddryck** [comment]
Shouldn't be difficult to fix and will dot it ASAP, but you shouldn't use the UI to start a macro. It's probably easier to execute the macro through the command line. 

```
genbi.exe myScript.genbil -q
```

**Comment by Seddryck** [comment]
Fixed. Build available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99072

Thx to confirm bug fix.
