### ISSUE TITLE
Using a global variable in a row-count assert

### ISSUE THREAD

**Issue by DonatasLTU** [Seddryck/NBi#119]
Hi, Charlier,

Still working with NBI testing framework and would like to report a bug (think so that this is a bug:) ) : I made this simple test, where instread of rowcount, I use integer parameter, and when loading the test, it throws and error 
![testname](https://cloud.githubusercontent.com/assets/14074706/10070161/65cc8b8a-62b9-11e5-880b-ddc795573b18.jpg)
![errormessage](https://cloud.githubusercontent.com/assets/14074706/10070172/70e46bb4-62b9-11e5-8f10-dd73dcad5222.jpg)

Could you take a look?

Donatas

**Comment by Seddryck** [comment]
Hi,

Row-count expect an integer. It's currently not possible to use a parameter. It could be added in a future release.

**Comment by DonatasLTU** [comment]
Thank you and closing the issue.

**Comment by Seddryck** [comment]
I reopen the issue because it is a perfect feature-request. One day it will be implemented.

**Comment by Seddryck** [comment]
Now that we've introduced [global variables](https://github.com/Seddryck/NBi/issues/301), it sounds like a small-improvement to support this use-case.

**Comment by Seddryck** [comment]
Beta is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-beta.85.build.195
