### ISSUE TITLE
Error while implementing NBi testing framework for database

### ISSUE THREAD

**Issue by srw213** [Seddryck/NBi#120]
Hi, 
I am trying to implement NBI testing for one of the databases. I've created .nbits fie in which I've given connection string and valid username and password. But when I execute the test I get an error 'Login failed for user ...'
Can you please help me resolve this error?

**Comment by Seddryck** [comment]
It just means that your connection string is not valid, your user have no access to this database.

**Comment by srw213** [comment]
I'm using the connection string exactly same way its mentioned in the examples in NBI documentation. Also, the user has access to the database. The user can connect to the database without any issue while connecting through SSMS, but get an error 'Login failed' in NBI.
Please advise.

**Comment by Seddryck** [comment]
I just confirm your connection string is wrong. If you want some help you need to provide some information, nobody could help you with the few information you've distilled. If you just copy/paste most of the connection strings found in the documentation they won't work because they are just fake.

Could you, at least, post your connection string and previously check that you don't use a connection string with SQL Server authentication information when your server is configured to use Windows authentication. Globally, this problem is not specific to NBi but to your environment and the connection string.

**Comment by amitsinghmiet** [comment]
Our server is configured to Windows authentication; what should be the syntax of connection string in such case?

**Comment by FuegoArtificial** [comment]
Connection strings can look differently. Let me google it for you: https://www.connectionstrings.com/sql-server/

As soon as you can connect with the same user from another client (e.g. Excel) with this connection string, it will work with NBi. "Login failed" suggests that the actual user who tries to connect does not have a login on the server. Debug this first, NBi requires working connections.

Try to build a connection with Excel and take out the information out of the connection properties and put it into the required connection string. Does that help?

Perhaps an admin can help you setting up connections to a database, too :)

Cheers

**Comment by amitsinghmiet** [comment]
We are using following connection string:
<query connectionString="Data Source=Server_Name;Initial Catalog=Database_Name;User Id=Domain\Username;password=***********">

Our SQL server is configured with Windows authentication.
User that is executing code has access on to the server.
Even then we are getting login failed error. Screenshot below

Connection string is borrowed from an Excel connection with same data source.

**Comment by Seddryck** [comment]
Guys, 

If your server is configured for Windows Authentication then you don't need to provide the user and password in your connection string.

**Comment by amitsinghmiet** [comment]
We have tried that approach too but in that case test case fails stating an error 'Login is failed for user '<blank> '

**Comment by Seddryck** [comment]
connectionString="Data Source=Server_Name;Initial Catalog=Database_Name;Integrated Security=true"

**Comment by srw213** [comment]
It worked. Thanks for your help.
