### ISSUE TITLE
Checking if table exists

### ISSUE THREAD

**Issue by DonatasLTU** [Seddryck/NBi#123]
Hi, Charlier,

I have written this test :

---

   test name="Checking if table exists" uid="0001" 
     category>Data quality   /category 
     system-under-test 
       structure 
    table caption="Investicijos" schema="dbo" 
        connectionString="Data Source=dvh-u\c02;Initial Catalog=USAGE; User Id=STB\C02; Integrated Security=True;"/ 
 /structure 
         /system-under-test 
     assert 
       exists / 
     /assert 
   /test 

---

And it returns this error:
NBi.NUnit.Runtime.TestSuite.ExecuteTestCases:
System.ArgumentException : The test suite is not valid. Check with the XSD. 2 errors have been found during the validation of the test-suite:
    At line 246: The 'schema' attribute is not declared.
    At line 246: The required attribute 'perspective' is missing.

How should table existence be tested?  What mistakes have I made?

Donatas

**Comment by FuegoArtificial** [comment]
Hi Donatas,

I believe the structure was initially written for cube-structure tests and some key words have to be matched to this.
In this doc http://www.nbi.io/docs/model-objects/ is written: 
In this xml node, named “structure”, you’ll need to specify on which object you’ll perform your assertion. For this you’ll need to specify the type of object (perspective, dimension, table …), its caption and also its parents (expl: for a dimension: a perspective).

This basically means that "perspective" is the "schema", as a "parent" of the table.
This works for me:

```
    <system-under-test>
        <structure>
            <table caption="$Table$" perspective="$Schema$" connectionString="@myDB"/>
        </structure>
    </system-under-test>
```

Does it work for you?

**Comment by DonatasLTU** [comment]
Yeah, it does, Thank you!

**Comment by Seddryck** [comment]
I'm still trying to find a way to use schema as a synonym of perspective, but no solution at the moment.
