### ISSUE TITLE
ETL package executes successfully through SQL job but fails while executing through NUnit

### ISSUE THREAD

**Issue by amitsinghmiet** [Seddryck/NBi#124]
An ETL package executes successfully through SQL Server Data Tools or a SQL job but when executed through a test case in NUnit. It fails with following error:
"The requested OLE DB provider Microsoft.ACE.OLEDB.12.0 is not registered" and 
"The requested OLE DB provider Microsoft.Jet.OLEDB.4.0 is not registered"

It doesn't give any such error while executing manually through above mentioned tools.

**Comment by FuegoArtificial** [comment]
Do you run NBi on the same Machine where the providers are registered on?
When executing the package, does SSDT use the same providers as stated in the error message or a different, registered one?

**Comment by amitsinghmiet** [comment]
Yes, we ran NBi on the same machine where the providers are registered. Moreover, SSDT use same providers and the package executes successfully without any error. Though with NBi it fails stating the error that I had already mentioned.

**Comment by FuegoArtificial** [comment]
Alright. I understand that everything is on one machine.
Could you please provide the connection string you use with the provider information within NBi and a screenshot of the connection information in SSDT?
Perhaps this way we get an idea what the issue could be.

**Comment by Seddryck** [comment]
Without any additional comment before EOW, I'll consider this case as solved.
