### ISSUE TITLE
Escape XML predefined entities for attributes

### ISSUE THREAD

**Issue by FuegoArtificial** [Seddryck/NBi#125]
Hi Cedric,

is it possible to escape predefined entities like "less than" in certain properties as well, just like it's already done within queries?
We use a template which tests for certain values in a table field. The query therefore states something like `WHERE FieldName <> '<NA>'`. NBi correctly escapes the predefined entities "<" and ">" in this query with `&lt;` and `&gt;`.
Now, I put the `'<NA>'` into the name of the test to point out which value was tested for. The predefined entities are not escaped and the test suite is not generated. 
I can now manually escape the characters in the name, but the test name is combined with the template being generated with the string just like as it's used in the query. A "double escape" would occur where the test name is displayed correctly but the query would be different: `WHERE FieldName &lt;&gt; '&amp;lt;NA&amp;gt;'`

Do you need more information to clarify the issue? Do you need the template for easier reproduction? PM?
Are there more properties like the test name (description? category?) where these characters need to be escaped?

FYI, the list of relevant entities is here: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

Have a great day!

**Comment by Seddryck** [comment]
Could you send me a way to reproduce your issue. I will check this.

**Comment by FuegoArtificial** [comment]
Of course.
Consider the following two data rows representing two test cases. Take any table/field you would like to test instead of the samples here:

| Column | Table | Value | Tolerance | IgnoreReason |
| --- | --- | --- | --- | --- |
| [PlanTypeID] | [dwh].[FactPlans] | -1 | 0% |  |
| [ProjectPlanName] | [dwh].[FactPlans] | `<NA>` | 0% |  |

Apply the following template in genbi:

```
<test name="Check if table '$Table$' contains less or equal than '$Tolerance$' of '$Value$' values in column '$Column$'">
    $if(IgnoreReason)$<ignore>$IgnoreReason$</ignore>$endif$
    <category>Test Instance: Quota check</category>
    <system-under-test>
        <execution>
            <query connectionString="@DWH_Test">
                <![CDATA[SELECT 'RowCount' AS [Description], COUNT_BIG(*) AS [Count] FROM $Table$ t WHERE $Column$ <> '$Value$']]>
            </query>
        </execution>
    </system-under-test>
    <assert>
        <equalTo tolerance="$Tolerance$">
            <query connectionString="@DWH_Test">
                <![CDATA[SELECT 'RowCount' AS [Description], COUNT_BIG(*) AS [Count] FROM $Table$ t]]>
            </query>
        </equalTo>
    </assert>
</test>
```

The name of the test contains a $Value$ placeholder. When the row with `<NA>` is applied the generation of the test suite is aborted due to the "XML predefined entities".

Besides the property of the test name there might be more properties with this issue like possibly description.

Is it possible for you to reproduce the issue?

**Comment by Seddryck** [comment]
Ok, it sounds possible to add formatters to StringTemplate. I think that I should be able to add a feature to render correctly the content of your fields. I'll surely add this to the next release.

**Comment by Seddryck** [comment]
Hello,

Apparently I don't need to implement something, it's already implemented in StringTemplate if I change a few lines of code.

In place of writing `<element attribute="$variable$"/>`, you should write `<element attribute="$variable; format="xml-encode"$"/>` and use the new binaries found at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99092

Could you provide some feedback on this it's not without risk?

**Comment by FuegoArtificial** [comment]
Thank you, I'll check it asap! :)

**Comment by FuegoArtificial** [comment]
hi Cedric,

it doesn't work with this build. Did I catch the wrong one?
![nbi_build_date](https://cloud.githubusercontent.com/assets/13558754/10541403/051e6a42-7411-11e5-93df-3ae0bddcede1.png)

Cheers

**Comment by FuegoArtificial** [comment]
ah, it works!
I must have had a copy & paste error somewhere promoting a different character somewhere. retyping worked! nice! let me furtherly check. I'll give thumbs up as soon as I retested together with GenbiL.

**Comment by FuegoArtificial** [comment]
hi Cedric,

this update is great and very elegant. It's just something one has to know of and the template therefore is easily adjustible.

Pretty cool! Thanks!

**Comment by Seddryck** [comment]
Ok it will be part of the release 1.11. I'll probably release it next week.
