### ISSUE TITLE
Reference file has not been found

### ISSUE THREAD

**Issue by DonatasLTU** [Seddryck/NBi#126]
Hi,

I have implemented reference file in my Nunit project and have placed it in the same folder where my TestSuite file is. But when running the testsuite, it throws an error that my settings file is not found
![nbiset1](https://cloud.githubusercontent.com/assets/14074706/10422876/179971c6-70c9-11e5-8e0a-57819174f7e6.jpg)
![nbiset2](https://cloud.githubusercontent.com/assets/14074706/10422878/1c60493c-70c9-11e5-80b4-2e9d9fdcc6b0.jpg)
![nbiset3](https://cloud.githubusercontent.com/assets/14074706/10422880/2239892c-70c9-11e5-8848-78466407f0b4.jpg)

**Comment by Seddryck** [comment]
This feature has a bug in v1.10. Have you tried the version 1.11-beta?

**Comment by DonatasLTU** [comment]
I will try soon

**Comment by Seddryck** [comment]
No news, good news: closing the issue
