### ISSUE TITLE
Complete syntax for using Intervals of values

### ISSUE THREAD

**Issue by amitsinghmiet** [Seddryck/NBi#127]
Need an example for interval of values so that I can create a test case using the same.

**Comment by FuegoArtificial** [comment]
Did you try building a test with the help of an existing test and the application of what's written here: http://www.nbi.io/docs/compare-intervals/?
If so, could you please provide your sample so we can help to figure out, what you are missing?
Thanks!

**Comment by amitsinghmiet** [comment]
Here is the sample code that I'm trying to execute:
![nbi range issue](https://cloud.githubusercontent.com/assets/14869676/10575289/334ea386-7610-11e5-8ac5-69fa2d347bbf.JPG)
Kindly have a look at it and let me know what needs to be corrected.

**Comment by FuegoArtificial** [comment]
Thank you!
Does your query return one row?
In the assert there is one row defined. If your query returns more than one row it might not work. Perhaps it's a different issue, it's just what pops up into my mind immediately.

**Comment by amitsinghmiet** [comment]
Query return just one row with one column only. There is some issue with syntax of assert, row or cell because test case on NUnit throws below mentioned error.

"The test suite is not valid. Check with the XSD. 1 error has been found during the validation of the test-suite:
    At line 35: The element 'equalTo' in namespace 'http://NBi/TestSuite' has invalid child element 'row' in namespace 'http://NBi/TestSuite'. List of possible elements expected: 'column, resultSet, query, xml-source' in namespace 'http://NBi/TestSuite'."

**Comment by amitsinghmiet** [comment]
I want to create a test case where SUM of a measure should lie between a particular range.
So assert clause will contain the range value. How can I achieve that?

**Comment by Seddryck** [comment]
The syntax of the assertion `equalTo` is defined at http://www.nbi.io/docs/compare-equivalence-resultsets/#embedded-result-set If you read this, you'll quickly understand that the element `<resultSet>` is missing in your test. I'd even say that this information is clearly specified in the error message that you've copy/pasted ... `equalTo` doesn't expect `row`.

Except this, the test sounds well-written.
