### ISSUE TITLE
Comparing report's dataset result with query based result set

### ISSUE THREAD

**Issue by amitsinghmiet** [Seddryck/NBi#128]
Is it possible to compare a report's dataset result with result set of a query fired on a database.
If yes, I'm getting an error where it says "Result set was empty" while the same query is giving records when executed in SSMS. Take a look at the screenshot for more insight:
![test case error message](https://cloud.githubusercontent.com/assets/14869676/10685573/635b2df8-7910-11e5-8f02-450a8a380169.jpg)

Screen grab of XML Code for the test cases is placed below:
![report vs query comparison nbi](https://cloud.githubusercontent.com/assets/14869676/10685547/09024d96-7910-11e5-8135-e99ab9063bec.jpg)

**Comment by Seddryck** [comment]
You're not getting any error, just a failure message. Your test is not successful. 

The query in the assertion returns 1 row and the query from the report 0. No surprise that your test is failing.

**Comment by amitsinghmiet** [comment]
When I'm executing the query from report/dataset in SSMS, it's executing fine and providing me a valid result set. Can't seem to find any error here. Kindly advise.

**Comment by FuegoArtificial** [comment]
Did you try the following steps?
1. Download the exact report to your local computer
2. copy and paste the query from the downloaded report to SSMS
3. declare the parameter in SQL and set it to the parameter you use (DANNYVO, I believe)
4. check if the result is still the same as in the assert query.

If it isn't the same, could you please try it with a different report and check if the result there is always 0 rows, too?

**Comment by Seddryck** [comment]
Without any additional comment before EOW, I'll consider this case as solved.
