### ISSUE TITLE
In assertion 'row-count', the xsd doesn't accept the value 0 for the option 'more-than'

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#129]
If you try to write this assertion, it's not validated by the XSD but it's a perfectly valid test.

``` xml
<assert>
    <row-count>
        <more-than>0<more-than>
    </row-count>
</assert>
```

**Comment by WimDeRons** [comment]
Hello Cédric,
I have tested this using version 1.11.0.99096 and can confirm it is fixed.
Kind regards,
Wim
