### ISSUE TITLE
Run multiple nbits with one dll

### ISSUE THREAD

**Issue by PascalCeccaldi** [Seddryck/NBi#130]
Hello Seddryck,

First I would like to thank you for providing such a good tool as Nbi, which is really interesting and well documented too.

I’m working on building a continuous integration environment for a BI solution with TFS online 2015.
You may know that a build in TFS is composed with tasks, sometimes pre-defined and sometimes created on your own with Powershell for example.
There is a “test” task which launch a dll file and run tests linked with this dll.

In my case, I have for now two nbits files (for different kinds of test), one runtime.dll and one runtime.dll.config file.
![capture3](https://cloud.githubusercontent.com/assets/10080840/10727256/a51c5288-7bd8-11e5-884f-151fc3a3384f.PNG)

To run the tests, I created two tasks for each nbits file calling the same dll, and I created other custom tasks to edit dynamically the runtime.dll.config file to change the path of the nbits file.
Then I have got three tasks by one nbits file, and the number of nbits file is undetermined.

So I would like to factorize the process by getting only one custom task.
This custom task would call the runtime.dll, and this one should be link to all the nbits files that I have in my project (due to the config file maybe).
I would like to know if it is possible and if there is a special way to do it.

Thank you by advance,

Pascal Ceccaldi

**Comment by Seddryck** [comment]
I currently don't plan to support a way to run more than one test-suite in a single run.

But, you can easily simplify your case. Create nunitproject files and one config file for each nbits, for more info check http://www.nbi.io/docs/installation-nunit-project/ and next pages
