### ISSUE TITLE
Be able to specify Environment when running SSIS Package from SSISDB Catalog

### ISSUE THREAD

**Issue by janvanhumbeek** [Seddryck/NBi#132]
When running an SSIS package from the SSISDB catalog, it would be useful if we could specify an environment (preferrably by Name, but ReferenceId should be fine too).
Currently, we need to specify all required parameters while we want to run the package using a pre-existing environment configuration on the catalog.

``` xml
<system-under-test>
  <execution>
    <etl 
      server="[ssis_server]" 
      catalog="SSISDB" 
      folder="[folder]" 
      project="[project]" 
      name="[package.dtsx]" 
      environment="[test]"/>
  </execution>
</system-under-test>
```

**Comment by Seddryck** [comment]
Should be easy to implement. Will add this soon.

**Comment by Seddryck** [comment]
New binaries for this feature are available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.12.0.99007 (In the tab "Artifacts")

If it solves the issue, just close it.
