### ISSUE TITLE
Use 'row-count' with a condition and support % of rows validating the condition compared to full result-set.

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#133]
This feature should enable the users to validate a query in the system-under-test by asserting than (more/less/equal) x% of the rows validate a condition.

In the exemple here under, the condition will be that OrderQuantity multiplied by UnitPrice will be greater than 5000$ in less than 20% of the rows.

``` xml
<assert>
  <row-count>
    <filter>
      <variable column-index="2">OrderQuantity</variable>
      <variable column-index="3">UnitPrice</variable>
      <expression name="TotalPrice">
        OrderQuantity*UnitPrice
      </formula>
      <predicate name="TotalPrice">
          <more-than>5000</more-than>
       </predicate>
    <filter>
    <less-than>20%</less-than>
  </row-count>
</assert>
```

**Comment by Seddryck** [comment]
@FuegoArtificial about the topic that we discussed offine, will it be helpful to have this kind of assertion?

**Comment by FuegoArtificial** [comment]
@Seddryck, either way this assertion is helpful! How would I write the assertion if we would count the occurance of a string like "unknown" and want it to occur equal or less than 20% of total rows? Would absolute limits be valid, too?
Thanks for considering my input! :)

**Comment by Seddryck** [comment]
> How would I write the assertion if we would count the occurrence of a string like "unknown" and want it to occur equal or less than 20% of total rows

``` xml
<assert>
  <row-count>
    <filter>
      <variable column-index="2">X</variable>
      <predicate column-index="2">
          <equal>Unknown</equal>
       </predicate>
    <filter>
    <less-than>20%</less-than>
  </row-count>
</assert>
```

Yes it would work also with an absolute value.

**Comment by FuegoArtificial** [comment]
That would work!
How does it technically work behind the scenes? Do you let the database (SQL Server) count or do you query the table and compare on NBi-side? The least one could lead to performance issues? Just thinking about a fact-table with one billion rows and you'd like to check one column for -1 values. Counting with SQL Server would give NBi just one row with the count. Counting on NBi side would return one billion rows from SQL Server.

**Comment by Seddryck** [comment]
@FuegoArtificial 
I'll surely not filter on SQL because it should also support MDX and FLOWR (xml). If you really have 1b rows, I suppose you can add a filter on a year or date to decrease the count of rows ... and I'm quite sure thanyour % should improve from year to year ;-)

**Comment by FuegoArtificial** [comment]
Hopefully it does improve ;)
Well, in fact-tables we sometimes have billions of rows, indeed. So for complete testing we would stick to the "abused" form of query to query tests. But for tests with smaller amounts of rows your idea is great! Like filtering for certain time frames makes sense if data quality imrproves over time and is no logic-issue in the ETL-part.
For smaller ("normal case") tables in general I would use und recommend your new test type! Where would you see a practical limit of rows? :)

**Comment by Seddryck** [comment]
This feature is available in preview at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.13 ... feel free to reports bugs and errors
