### ISSUE TITLE
When asserting query execution against an external file, existence of the external file should be validated after setup tasks have run

### ISSUE THREAD

**Issue by janvanhumbeek** [Seddryck/NBi#136]
For some of my tests I am creating the expected resultset, to validate query execution results against, in my setup tasks.
When I start my tests a first time (when the external resultset-file is still non-existent), NBi throws an ExternalDependencyNotFoundException on the file that would be created through the setup.

```
NBi.NUnit.Runtime.TestSuite.<testname>:
NBi.Core.ExternalDependencyNotFoundException: This test is in error because the following dependency has not been found '<full path to external resultset file>'.
```

Can the order be changed so that the file's existence is only checked after setup tasks have run?

**Comment by Seddryck** [comment]
The easiest work-around is probably to have an empty file and overwrite itin the steup. I'm working on fixing this bug.

**Comment by Seddryck** [comment]
Bug fixed in https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.12.0.99036
