### ISSUE TITLE
How to define data types for columns resulted from a query

### ISSUE THREAD

**Issue by Pramod-AG** [Seddryck/NBi#146]
I have a source sql query which result 4 columns with data (Numeric, text, text, date) to compare with target mdx query with same result (Numeric, text, text, date). However when i execute this i gets error like  "NBi.NUnit.Runtime.CustomStackTraceErrorException : The column with an index of 1 is expecting a numeric value but the first row of your result set contains a value 'aaa' not recognized as a valid numeric value or a valid interval.". I have seen similar issue can be solved by defining data types if we are comparing RECORDSETS manually entered. But in this case how and where i can define data types to compare ? I have attached a sample scenario pic. Will be grateful
![data_types](https://cloud.githubusercontent.com/assets/15996426/11397154/2f8b0d16-939d-11e5-9d93-8a4b2dac3422.jpg)
 if you can provide some suggestions. Thanks in Advance :)

**Comment by Seddryck** [comment]
The same way than for a result-set manually defined. See http://www.nbi.io/docs/compare-configuration/ 

Pragmaticaaly:

``` xml
<assert>
    <equalTo>
        <column  index="0" role="key" type="numeric"/>
        <column  index="1" role="value" type="text" />
        <column  index="2" role="value" type="text" />
        <column  index="3" role="value" type="dateTime" />
        <query ... />
    </equalTo>
</assert>
```

**Comment by Pramod-AG** [comment]
Thank you so much Seddryck, Its worked :)
