### ISSUE TITLE
Passing parameters in query element - ssas connection string

### ISSUE THREAD

**Issue by Pramod-AG** [Seddryck/NBi#147]
I would like to pass 'Initial Catalog' value in SSAS cube connection string in <query> element on run time or from a list. This is for running the same test case for multiple cubes with same structure. I have seen in the NBi documentation we can create and pass parameters, But is this possible in my scenario ? Please suggest as i am very new to this tool

**Comment by Seddryck** [comment]
Using parameters is not a solution for your scenario.

You should probably create settings and config files to redirect to the cube under test.

http://www.nbi.io/docs/config-connection-strings/ (especially the part about external reference)
http://www.nbi.io/docs/installation-config/

If it doesn't solve your scenario, explain why, I'm interested.

**Comment by Pramod-AG** [comment]
Thanks Seddryck for your help. I am going through the links and will back to you with my result. And another thing day by day my interest in this wonderful tool is going up and up. I am trying to utilize all features for my requirements by testing, going through older tickets posted by others and documentation in nbi site. Mean while i will be raising few more questions, once you have try please help.....
