### ISSUE TITLE
Compare all results of a query with only one value (equal, lower, higher)

### ISSUE THREAD

**Issue by teulgreg** [Seddryck/NBi#148]
Hello Seddryck, 

On our project we need to compare all the results of a query (sql or mdx) with only one expected value.

Example : we have a queries checking that all financial measures from a cube are not lower than 1 k€ . 

Is it possible to create a new feature to compare all the results of a query with only one expected value 
(alll results equal, lower or higher than one expected value) ?

thanks  :-)

Gregory

**Comment by Seddryck** [comment]
Hi Gregory,

It's a good idea and a planned feature.

In fact it's already possible to hack the feature [Calculations in a resultset](http://www.nbi.io/docs/resultset-calculations/) to implement this kind of test. But I agree that it's not user-friendly and it has some serious limitations ... more info about the way to hack this feature on my [blog](https://seddryck.wordpress.com/2014/11/02/evaluate-an-expression-to-validate-the-result-of-a-query/)

**Comment by teulgreg** [comment]
Thank u Cédric. :-)

Grégory

PS : Galla Pupel who you met last week at the SQL server days and work with me, says hello to you

**Comment by Seddryck** [comment]
I propose following syntax

``` xml
<assert>
  <all-rows>
    <variable column-index=3>Sales</variable>
    <predicate name="Sales">
      <more-than>1000</more-than>
    <predicate>
  </all-rows>
</assert>
```

This test should assert that all the rows have a value greater than 1000 for column #3

Now that #133 is complete, I can create a variant to support this.

**Comment by teulgreg** [comment]
I think it is a good syntax. It would be very usefull for our tests.

You should, if it is possible,  also integrate with “more-than”, “less-than” and “equal-to” possibilities

**Comment by Seddryck** [comment]
The build https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.16 introduces the assertions `all-rows` and `no-rows`. Feel free to download and provide feedback. Some examples are available at https://github.com/Seddryck/NBi/blob/master/NBi.Testing/Acceptance/Resources/Positive/QueryAllNoRows.nbits
