### ISSUE TITLE
Call testcases

### ISSUE THREAD

**Issue by dayanavarelamejia** [Seddryck/NBi#150]
Is possible execute a specific testcase for example in 

cmd C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "C:\Documents\Testing\Tests.nunit" /config:test_config /run

But also i want run a specific testcase

**Comment by Seddryck** [comment]
It's more a question related to NUnit than NBi :-) This link should give you some information: http://www.nunit.org/index.php?p=consoleCommandLine&r=2.6.4 If you've issues with these solutions describe them.

**Comment by dayanavarelamejia** [comment]
But i want to call nbi test. This is possible?

**Comment by Seddryck** [comment]
I don't see a reason why it shouldn't. Have you tried?

**Comment by dayanavarelamejia** [comment]
Yeah!! it's possible with .dll, but when im trying with .nbits is not working
Probably the problem is in nunit!!

Thanks.

**Comment by Seddryck** [comment]
Could you post the command that you've tested?

**Comment by dayanavarelamejia** [comment]
is

C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "C:\Testing\UnitTests.nunit" /config:UnitConfig /run:test_name

**Comment by Seddryck** [comment]
And what was your value for _test_name_ ? It should be the full test's name starting by "NBi.NUnit.Runtime.TestSuite.ExecuteTestCases"

**Comment by dayanavarelamejia** [comment]
the name of test case for example calendar but also i'm trying with 
C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "C:\Testing\UnitTests.nunit" /config:UnitConfig /run:"NBi.NUnit.Runtime.TestSuite.Calendar"

but the program run all

**Comment by Seddryck** [comment]
ExecuteTestCases is missing in the command you've copy/pasted.

Anyway, the GUI hasn't this problem.

**Comment by dayanavarelamejia** [comment]
But ExecuteTestCases is to run all, if i have like 500 test case but i want run a list just 3 without the GUI, in a batch file, only using the nbits file and config, nunit does not accepting call only one from the nbits file

**Comment by Seddryck** [comment]
I'm expecting `C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "C:\Testing\UnitTests.nunit" /config:UnitConfig /run:NBi.NUnit.Runtime.TestSuite.ExecuteTestCases.Calendar` to only run the test named "Calendar" but I've never tried this.

To be honest when I use the console, I usually specify one or more categories rather than a few test names.

**Comment by Seddryck** [comment]
NBi simulates multiples tests by creating TestCases from a parametrized Test decorated by a TestCaseSource.When building the ITestCaseData, the property TestCaseName is set to the name declared in the nbits file (here "Calendar").

Apparently it works on my side if I use `C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "C:\Testing\UnitTests.nunit" /config:UnitConfig /run:NBi.NUnit.Runtime.TestSuite.Calendar`

**Comment by dayanavarelamejia** [comment]
Yeah! i know, in the code have the same name of the label for a weird reason it's not working for me, but thanks a lot. i will find a way to do!
