### ISSUE TITLE
Number of rows that are being displyed is limited

### ISSUE THREAD

**Issue by ramakrishnarayipudi** [Seddryck/NBi#153]
Hi, 

Right now, I only can see top 10 rows in the unexpected rows and missing rows categories and most of the time the number of rows are more than 10 rows and these are being skipped for the display purpose and right now don't have any provision to see all the rows.
Is there anyway to extract all rows that are not matched or not expected, if so how and if not, can I except in future release ?

Thanks.
Krishna

**Comment by ramakrishnarayipudi** [comment]
Hi,

I have updated the configuration as suggested here (http://www.nbi.io/docs/config-profile-failure-report/) and don't find any difference in the result set. It still displays same 10 rows after making the changes to the configuration file.

Thanks,
Krishna

**Comment by rvdpluijm** [comment]
Same here. I added the following to my .config file:

``` xml
<nbi testSuite="UnitTesting\UnitTesting.nbits">
   <failure-report-profile
        threshold-sample-items="250"
        max-sample-items="200"
        expected-set="Full"
        actual-set="Full"
        analysis-set="Full"
    />
 </nbi>
```

But I received the following result (trimmed for convenience here) back:

``` xml
<![CDATA[
ResultSet with 140 rows

     KEY (Text) | KEY (Text) | KEY (Text) | KEY (Text) | KEY (Text) | KEY (Text) | KEY (Text) | VALUE (Numeric)  (+/- 0.00)
     ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | --------------------------- 
     HR         | 2016       | 2          | 500        | 16000      | C0000075   | (empty)    | -750.000000                
     HR         | 2016       | 2          | 500        | 16000      | C0000104   | (empty)    | -427.710000                
     HR         | 2016       | 2          | 500        | 16000      | C0000229   | (empty)    | -150.600000                
     HR         | 2016       | 2          | 500        | 16000      | C0000828   | (empty)    | -11176.170000              
     HR         | 2016       | 2          | 500        | 16000      | C0001092   | (empty)    | -686.400000                
     HR         | 2016       | 2          | 500        | 16000      | C0001285   | (empty)    | -6.500000                  
     HR         | 2016       | 2          | 500        | 16000      | C0004611   | (empty)    | -7.700000                  
     HR         | 2016       | 2          | 500        | 16000      | C0004906   | (empty)    | -6280.000000               
     HR         | 2016       | 2          | 500        | 16000      | C0005755   | (empty)    | -3614.000000               
     HR         | 2016       | 2          | 500        | 16000      | C0006960   | (empty)    | -2941.500000               

130 (of 140) rows have been skipped for display purpose.]]>
```

**Comment by Seddryck** [comment]
Which version of NBi? Should have been fixed in 1.11

**Comment by rvdpluijm** [comment]
Version 11.0.35723

**Comment by Seddryck** [comment]
Huuum, it should be fixed according to this thread [https://github.com/Seddryck/NBi/issues/98] Could you try with the preview version attached to this issue or with the official release of [1.12](https://github.com/Seddryck/NBi/releases/download/v1.12/NBi-1.12.0.7.zip)

**Comment by rvdpluijm** [comment]
Hi @Seddryck ,

With 1.12 I managed a successful test. Thanks for your support! This issue may be closed now.
