### ISSUE TITLE
Timeout for queries <execution>

### ISSUE THREAD

**Issue by bipedro** [Seddryck/NBi#160]
Hi,

Thanks for the work with NBi. It's a great tool for testing MS BI Stack.

Is there anyway to have a timeout for long running queries used in an equalTo assertion?

Imagine that for any reason my query is blocked in the DW in an equality assertion, the tests coming next will have to wait until the query either finishes or is killed.

Thanks.

**Comment by Seddryck** [comment]
Not at the moment, but it's something that could be considered in a next release.

**Comment by bipedro** [comment]
Thanks for the quick response.

I would appreciate that given it seems an important feature to avoid having your test suite taking ages to finish.

If you could consider this for a next release that would be great.

Thanks again.

**Comment by FuegoArtificial** [comment]
Hi bipedro,

would it be an option for you to consider the following ideas to workaround your issue?:
- switch the testing to times when no ETL takes place
- if tests run too long generally, reduce the tests to a very broad perspective to discover inconsistencies, not necessarily telling you what exactly went wrong, just that there is an issue. This might improve performance und is sometimes sufficient. Like sum of turnover in the source must be equal to the sum of turnover in destination. if it doesn't match, it can have several reasons, you know there is something wrong but the test will perform better than with a complex logic applied.
- reducing test-run times can mean to test a smaller time frame (or any other smaller amount of data), too.

just some thoughts, perhaps it helps.

**Comment by bipedro** [comment]
Thanks for the help.

Regarding:
- switch the testing to times when no ETL takes place;
  I'm not sure I've understood the suggestion; Can you explain me in other terms please?

Regarding the second option: are you telling me to create more broad queries to discover problems, right?

The problem is that, sometimes, even with broader queries these can become blocked in the DW.
This is also true for a smaler amount of data; If the DW or other environment is under heavy pressure the query might not terminate or take too long.

I would appreciate a way to tell my test-suite to consider the test as failed due to a query that does not finish.

**Comment by bipedro** [comment]
I mistakenly closed this issue. Sorry.

**Comment by FuegoArtificial** [comment]
Hi bipedro,

with "switch the testing to times when no ETL takes place" I mean to switch the tests to a time when you don't load data into the DW. [Wikipedia: ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load)
Blocks usually occur when you write into a DB and want to read it at the same time. As soon as you know the reason for the blocks you can work around it and let the tests run when no blocking takes place, explicitly. Is that an option for you?

Cheers

**Comment by bipedro** [comment]
Hi,

That's something I already do (or try to), but I'm not only talking just about blocking. Sometimes the DW is under heavy load by analyst's queries.

There are lot's of ways to go around this. I only think that having the possibility to define a timeout for otherwise fast queries would be a nice to have (a little more than nice to have) since in a regression test suite with lot's of SQL comparisons this might become a problem.

What do you think?

**Comment by Seddryck** [comment]
Preview available: https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.36 

It supports the following syntax.

``` xml
<execution>
    <query timeout-milliSeconds="60000">
        select * from myTable
    </query>
</execution>
```
