### ISSUE TITLE
GenBI: Pass <![CDATA]< in template

### ISSUE THREAD

**Issue by rvdpluijm** [Seddryck/NBi#161]
When using the following test template, the CDATA tag isn't passed through to the test file, while that is the preferred situation in the case of queries.

``` XML
<test name="Vergelijk recordset '$usp$' gedraaid op '$productiedb$' met recordset gedraaid op '$acceptatiedb$'">
 <description>Check in hoeverrre de resultset vanuit '$usp$' op '$productiedb$' overeenkomt met de resultset van deze Stored procedure op de '$acceptatiedb$', gegeven dat de data op hetzelfde moment gesynchroniseerd wordt</description>
 <edition author="$username$" created="$now$"/>
 <system-under-test>
           <execution> 
  <query connectionString="Server=$productieserver$;Database=$productiedb$;User Id=$userid$;Password=$password$">
  <![CDATA[
  exec $usp$
        $if(parameter1)$ $parameter1$ = $parameter1waarde$ $endif$
  $if(parameter2)$ , $parameter2$ = $parameter2waarde$ $endif$
  $if(parameter3)$ , $parameter3$ = $parameter3waarde$ $endif$
  $if(parameter4)$ , $parameter4$ = $parameter4waarde$ $endif$
  $if(parameter5)$ , $parameter5$ = $parameter5waarde$ $endif$
  ]]>
  </query>
          </execution> 
 </system-under-test>
 <assert>
  <equalTo>
  <query connectionString="Server=$acceptatieserver$;Database=$acceptatiedb$;User Id=$userid$;Password=$password$">
    <![CDATA[
  execute $usp$
        $if(parameter1)$ $parameter1$ = $parameter1waarde$ $endif$
  $if(parameter2)$ , $parameter2$ = $parameter2waarde$ $endif$
  $if(parameter3)$ , $parameter3$ = $parameter3waarde$ $endif$
  $if(parameter4)$ , $parameter4$ = $parameter4waarde$ $endif$
  $if(parameter5)$ , $parameter5$ = $parameter5waarde$ $endif$
  ]]>
   </query>
  </equalTo>
 </assert>
</test>
```

**Comment by Seddryck** [comment]
I'll check if it's possible to enforce the CDATA markup when serializing a text element and if it's the case, I'll do it.

**Comment by Seddryck** [comment]
After a quick check, it sounds too much work for a small benefit. I will let this here but won't work on it.

**Comment by Seddryck** [comment]
@fefeslon @rvdpluijm 

Preview is available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.15.0-ci.7/artifacts (download the UI zip to get genbi).

The CDATA section is now enforced for all **queries** ... independently of the fact that you've it or not in your template.

Please, if you've some issues with this new build ... report in this issue! ... and if it works, just tell it.

**Comment by FuegoArtificial** [comment]
That's a great feature! That it doesn't matter if the CDATA is in our templates or not, enables backward-compatibility. Pretty cool!  I'd like to test that version the upcoming week in two or three productive environments for one run, return to version 1.14 again and report if there have been any issues.

@rvdpluijm: very sophisticated template! cool!

**Comment by FuegoArtificial** [comment]
the feature passed "my test". a simple test if everything runs and results are returned like before reveals no problems.
Thank you for implementing this!

**Comment by fefeslon** [comment]
Works perfectly for me, thanks for implementing!

**Comment by Seddryck** [comment]
Available in beta: https://github.com/Seddryck/NBi/releases/tag/v1.15-beta
