### ISSUE TITLE
SSIS EtlCatalogRunner

### ISSUE THREAD

**Issue by loewensteinph** [Seddryck/NBi#164]
Bug in EtlCatalogRunner Class:

System.ArgumentOutOfRangeException : The package named '**samplepackage.dtsx**' hasn't been found on the project 'testproject'. List of existing packages: **samplepackage.dtsx**, samplepackage2.dtsx, samplepackage3.dtsx.
Parameter name: Name
at NBi.Core.SqlServer.IntegrationService.EtlCatalogRunner.GetPackage(IntegrationServices integrationServices) 

![screenshot](https://cloud.githubusercontent.com/assets/17300968/13121636/6f55af7a-d5b3-11e5-813d-adb5d81dc369.PNG)

**Comment by Seddryck** [comment]
Thx for the report (and the fix)!

A new version is available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.29
