### ISSUE TITLE
Question: NUnit/NBi integration with Jenkins

### ISSUE THREAD

**Issue by bipedro** [Seddryck/NBi#167]
Hi @Seddryck,

Do you have any tutorial explaining how to integrate NUnit/NBi with Jenkins? Have you done this?

Do you know if I can do this by using Jenkins NUnit addin?

Any help you'd be greatly appreciated.

Thanks.

**Comment by Seddryck** [comment]
I have never tried this with Jenkins.

If you can specify a NUnit project file to Jenkins, I see no issue. Just define correctly your project file for running NBi and it will be OK.

**Comment by bipedro** [comment]
Thanks. It works.
