### ISSUE TITLE
record-separator="\r\n" in csv file not working

### ISSUE THREAD

**Issue by Reinacher** [Seddryck/NBi#168]
Hi,

I'm using NBI to build some basic tests where I compare a database query with data from a csv file.

`<settings>
        <csv-profile field-separator="," record-separator="\r\n"/>
    </settings>`

I'm experiencing the problem that when I run my test in NUnit the record separator is not recognized.
The test works fine when I use a different record-separator e.g. "#".

**Comment by Seddryck** [comment]
You should try

``` xml
<settings>
    <csv-profile field-separator="," record-separator="CrLf"/>
</settings>
```

http://www.nbi.io/docs/config-profile-csv/

**Comment by Reinacher** [comment]
That worked, thank you.
