### ISSUE TITLE
Issues while comparing SQL and MDX query

### ISSUE THREAD

**Issue by Reinacher** [Seddryck/NBi#170]
I'm having issues while comparing an SQL and MDX query. I'm receiving the following error:

NBi.NUnit.Runtime.TestSuite.Compare two query results:
System.AggregateException : One or more errors occurred.
  ----> System.Data.SqlClient.SqlException : Incorrect syntax near the keyword 'on'.

Both queries are fully functional on the SQL server but I can't seem to get them to work in NBI.

`<?xml version="1.0" encoding="utf-8"?>
<testSuite name="Dupa testSuite" xmlns="http://NBi/TestSuite">
    <test name="Compare two query results">
      <system-under-test>
        <execution>
             <query connectionString="Server=.;Database=Gas;User Id=###;Password=######;">
            select Sum([Nominated_exit]) AS [NominatedExit] from (
            select  SUM([Nominated_exit]) AS [Nominated_exit] from NominationsPerNetworkpoint_Julianadorp
                union
            select  SUM([Nominated_exit]) AS [Nominated_exit] from NominationsPerNetworkpoint_Other
            ) AS [NominatedExit] ;  
        </query>    
        </execution>
      </system-under-test>
        <assert>
        <equalTo>
        <column  index="0" role="value" type="numeric" tolerance="0.1"/>
         <query name = "mdx" connectionString="Server=.;Database=Gas_DW;User Id=###;Password=######;">  
        SELECT [Measures].[Nominated Exit] AS [NominatedExit] on 0  FROM [Gas DW]  ;
          </query>
         </equalTo>
      </assert>
    </test>
</testSuite>` 

I'm probably making a shameful mistake but if anyone could help me out it would be extremely appreciated.

**Comment by FuegoArtificial** [comment]
Does the MDX-query really work like that?
Otherwise try
`WITH
MEMBER [NominatedExit] AS [Measures].[Nominated Exit]
SELECT [Measures].[NominatedExit] on 0 FROM [Gas DW]`

**Comment by Reinacher** [comment]
Yes the MDX works perfect in SQL server Management studio.

When using "WITH MEMBER" it still works fine in Management studio but it generates an extra syntax error in NUnit.

I've tried everything that I could find online and I'm completely out of ideas.
I'm using this framework for my internship and it has been very useful but with my deadline approaching this is the only real problem that I have left.

**Comment by Seddryck** [comment]
The connection string for the assertion is not recognised as an SSAS connection string. 

change it and it will fix your issue.

**Comment by Reinacher** [comment]
Thanks for helping me out, I knew it was a shameful mistake. 

And thanks for making this framework it really helped me a lot!
