### ISSUE TITLE
Rounding is broken for negative values

### ISSUE THREAD

**Issue by mthierba** [Seddryck/NBi#173]
Hi,
I've recently started using NBi, and I'm really impressed. Great work! However, today I had to learn the hard way that rounding fails for negative values. I've add some test cases to demonstrate. Please see PR attached.

Thanks,
Mathias

**Comment by mthierba** [comment]
Just to clarify: By "failing" I mean that applying NBi rounding to negative values actually makes them positive (round -0.1234 with step 0.01 gives +0.12).

**Comment by Seddryck** [comment]
Just to be sure that there is no misunderstanding, your tests are defined with 

``` xml
<column ... rounding-style="floor" rounding-step="0.01" />
```

and not with 

``` xml
<column ... tolerance="0.001" />
```

See doc at http://www.nbi.io/docs/compare-tolerances-roundings/

I'll check this but it should berelatively easy to fix.

**Comment by mthierba** [comment]
Yes, I am talking about roundings, not tolerances.(BTW, I temporarily solved that problem for my test cases by applying the rounding at the data source level, i.e. before any values get to NBi - but, obviously, it would be nice to be able to use that feature as it is intended.)

**Comment by Seddryck** [comment]
You'll find a bug fix at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.42/artifacts

**Comment by mthierba** [comment]
Thanks for sorting this out so quickly! Really appreciated.
