### ISSUE TITLE
SSIS Environment references not under SSISDB

### ISSUE THREAD

**Issue by rcarasan** [Seddryck/NBi#176]
Hello, 

There's a small issue when referencing Environments from the SSIS Catalog: 
If in the SSISDB, the Environment is referenced from the local folder, like so:
![env pop-up local](https://cloud.githubusercontent.com/assets/17856171/14108333/33ff66da-f5bd-11e5-8993-333bf9623fdc.png)
an ArgumentOutOfRangeException is thrown:

```
System.ArgumentOutOfRangeException : The environment named 'Dev' exists but is not referenced in the project 'myproject'. List of existing references: Dev.
Parameter name: Environment 
at NBi.Core.SqlServer.IntegrationService.EtlCatalogRunner.GetEnvironmentReference(ProjectInfo project) in c:\projects\nbi\NBi.Core.SqlServer\IntegrationService\EtlCatalogRunner.cs:line 93

```

If on the other hand, the Environment is referenced from the actual folder, like so:
![env pop-up folder](https://cloud.githubusercontent.com/assets/17856171/14108405/92a979dc-f5bd-11e5-8bb1-c1cfb9aef4b9.png)
Then the package is executed correctly and the test is run. 

In both cases, the etl is defined in the same way in the .nbits file:

```
            <etl
                server="server"
                catalog="SSISDB"
                folder="ETL_Retail"
                project="myproject"
                name="package.dtsx"
                environment="Dev"
            />
```

It's not a big deal, but maybe add a quick note about it in the documentation if a fix isn't possible.

And thanks a lot for this great tool

**Comment by Seddryck** [comment]
Oups, didn't know it was possible to create an environement somewhere else than in your project's folder. I'll take a look and check how I can handle this case.

**Comment by Seddryck** [comment]
Alpha version available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-alpha.1+85.build.82
