### ISSUE TITLE
SSIS Package hosted on SSISDB run into an error

### ISSUE THREAD

**Issue by SauerCh** [Seddryck/NBi#177]
Couldn't run test whether my ETL is successful or not. The nbits file should be OK, cross checked it with an experienced colleague. At runtime, I receive the following error message:

_NBi.NUnit.Runtime.TestSuite.ETLCRMToStageSuccessful:
System.ArgumentOutOfRangeException : The package named 'ShowTimeBIStageToDWHMasterPackage.dtsx' hasn't been found on the project 'ShowTimeBIETL'. List of existing packages: ShowTimeBICRMToStageAccount.dtsx, ShowTimeBICRMToStageFact.dtsx, ShowTimeBICRMToStageMasterPackage.dtsx, ShowTimeBICRMToStageSystemUser.dtsx, ShowTimeBIStageToDWHDimCustomer.dtsx, ShowTimeBIStageToDWHDimLocation.dtsx, ShowTimeBIStageToDWHFactWork.dtsx, ShowTimeBIStageToDWHMasterPackage.dtsx.
Parameter name: Name_

Any idea?

**Comment by Seddryck** [comment]
I think the error message is self-explicit: the package you are trying to run doesn't exist. You should deploy it on your test server or check twice the path.

**Comment by SauerCh** [comment]
I'm sorry but it isn't that easy. Please have a look at the List of existing packages. The package I would like to test is listed. 

NBi.NUnit.Runtime.TestSuite.ETLCRMToStageSuccessful:
System.ArgumentOutOfRangeException : The package named **'ShowTimeBIStageToDWHMasterPackage.dtsx'** hasn't been found on the project 'ShowTimeBIETL'. List of existing packages: ShowTimeBICRMToStageAccount.dtsx, ShowTimeBICRMToStageFact.dtsx, ShowTimeBICRMToStageMasterPackage.dtsx, ShowTimeBICRMToStageSystemUser.dtsx, ShowTimeBIStageToDWHDimCustomer.dtsx, ShowTimeBIStageToDWHDimLocation.dtsx, ShowTimeBIStageToDWHFactWork.dtsx, **ShowTimeBIStageToDWHMasterPackage.dtsx**.
Parameter name: Name

**Comment by Seddryck** [comment]
Sorry, was a bit fast: You should check this thread #164
