### ISSUE TITLE
The column with an index of 1 is expecting a numeric value but the first row of your result set contains a value 'New' not recognized as a valid numeric value or a valid interval.

### ISSUE THREAD

**Issue by ASahithi** [Seddryck/NBi#181]
Hi,

While I am comparing the report's dataset result with result set of a query, I am getting the below error:
The column with an index of 1 is expecting a numeric value but the first row of your result set contains a value 'New' not recognized as a valid numeric value or a valid interval.

Below is the screenshot of the code
![dataset result vs query result](https://cloud.githubusercontent.com/assets/18462160/14527140/893302b0-0265-11e6-8220-feccd3928b45.PNG)

**Comment by Seddryck** [comment]
As detailed in the error message : The query returns "new" for the column with index 1 in the first row and you've defined this column as a numericvalue. Is "new" a numeric value? No ... what are you expecting? what is not clear? Adapt your test's definition (or fix the bug in your report). http://www.nbi.io/docs/compare-configuration/ 

It would be nice to follow the guidelines at https://github.com/Seddryck/NBi/blob/master/contributing.md before submitting an issue and notably to close the issue if it's fixing your issue.
