### ISSUE TITLE
gen Bi - creates test based on CSV / Query  but values to caption and perspective is blank for all test cases.

### ISSUE THREAD

**Issue by shiv-2019** [Seddryck/NBi#183]
![capture](https://cloud.githubusercontent.com/assets/6196817/14636303/84d8bf96-0622-11e6-8385-66ad46206c3f.JPG)

**Comment by Seddryck** [comment]
Can I see the test-cases tab? Isn't it an issue between UPPERCASE and lowercase?
What's your version of Genbi?

**Comment by shiv-2019** [comment]
Hi Sed, its version 1.13.0.5

**Comment by Seddryck** [comment]
Could you answer all the questions?

**Comment by Seddryck** [comment]
Will consider as answered
