### ISSUE TITLE
clean-cache not working on SSAS tabular mode?

### ISSUE THREAD

**Issue by robertZaufall** [Seddryck/NBi#185]
I am getting this error:
Microsoft.AnalysisServices.AdomdClient.AdomdErrorResponseException : XML parsing failed at line 7, column 54: A text/xml declaration may occur only at the very beginning of input.

**Comment by Seddryck** [comment]
Which version? Could you post your test?

**Comment by Seddryck** [comment]
No feedback ... question closed.
