### ISSUE TITLE
Display column aliases in the result output?

### ISSUE THREAD

**Issue by dvaston** [Seddryck/NBi#189]
Hi,

When there is a mismatch in the data, is it possible to display the column headings from MDX or SQL (or use your own aliases)?

So for example, instead of the below output, it would have the proper column names (e.g. "State", "Sales", "Customers", etc) instead of "VALUE (Numeric)  (+/- 0)".

| KEY (Text) | VALUE (Numeric)  (+/- 0) | VALUE (Numeric)  (+/- 0) |
| --- | --- | --- |
| NSW | 3100.79 | 8075 |
| VIC | 4486.19 | 2995 |

**Comment by Seddryck** [comment]
It's not a priority but it's on the to-do list.

**Comment by Seddryck** [comment]
Will continue to follow this issue in #105 but work as has started
