### ISSUE TITLE
Test a shared dataset without specifying a report

### ISSUE THREAD

**Issue by kottivakkam** [Seddryck/NBi#190]
Is it possible to test a shared dataset in SSRS? I can see that I can test a shared dataset in the context of a report, but can the shared dataset be tested directly?

In my case I am writing tests for app. 400 reports, but they are all using shared datasets and there are only about 100 shared datasets in total. if I try to omit the report name from the XML and let path/dataset point to the shared dataset I get the error that @ReportName is expected.

**Comment by Seddryck** [comment]
It's not possible at the moment, but it's relatively easy to implement. I'll include this in a next release.

**Comment by Seddryck** [comment]
syntax should be

``` xml
<shared-dataset
  source="..."
  path="..."
  name="..."
/>
```

behaviour must be the same than for reports (including settings).

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.14.0-ci.10
