### ISSUE TITLE
Teradata connection issues

### ISSUE THREAD

**Issue by crnkyunicorn** [Seddryck/NBi#191]
I am trying to use the framework to test an SSAS cube that sits over the top of Teradata but running into some problems with the connections.  The current OleDb driver for Teradata isn't usable due to the version (15 doesn't seem to work with 15.10) and I cant seem to get NBi to work with the Teradata Odbc or .Net providers.

Any suggestions would be most helpful?

**Comment by Seddryck** [comment]
If you have no way to connect through Oledb, I don't think I've another option for you at the moment: it's not possible to use Odbc and the only .net provider supported is the one for SQL Server. 

It's something on the roadmap to support custom .net providers ... perhaps in a couple of months.

**Comment by Seddryck** [comment]
Version https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.14.0-ci.8 is a preview supporting ODBC connections. If it's an option for you ...

**Comment by Seddryck** [comment]
It's now possible to implement your own custom connector to any database, see http://www.nbi.io/docs/extension-support/
