### ISSUE TITLE
Issue with parallel tasks

### ISSUE THREAD

**Issue by luwer** [Seddryck/NBi#195]
Hi there,

I am having a bit of a problem trying to implement some basic ETL-Unit-Tests.

A short background:
We are building a data warehouse with the data vault methodology and I am trying to run some tests to make sure my logic is set up correctly.
Therefore I wanted to run numerous <sql-run> commands in the <setup> of my tests to load my data in the data vault stage in parallel to improve performance of my tests.
In the SQLs is a stored procedure execution command, which we need to run our SSIS packages.
Because every package is independent of one another, I wanted to let it run in parallel.

Here is the problem I keep having:
I want to run a series of `<tasks>` in my setup of the test. That should be possible, right? At least I am doing it so far and in some cases it works just fine.
The first <tasks> group is supposed to run sequential, while the second and third group of tasks are supposed to run in parallel inside their own group.
To clarify, something like this:

```
<testsuite>
    <group name="">
        <setup>
            <tasks parallel="0" run-once="1">
                <!-- clear the necessary tables and setup the wanted data in them -->
            </tasks>
            <tasks parallel="1" run-once="1">
                <sql-run ... />
                <sql-run ... />
                ...
            </tasks>
            <tasks parallel="1" run-once="1">
                <sql-run ... />
                <sql-run ... />
                ...
            </tasks>
        </setup>
        <test name="">
            ...
        </test>
    </group>
</testsuite>
```

If I add more than around 10 <sql-run> commands in the parallel task groups I keep having an endless loop in my setup. The sql-commands are being started endlessly, as far as I can tell at least.

Is there a sort of limit for running commands in parallel, or am I doing something else wrong?

I would really appreciate some feedback, maybe I overlooked something simple.

Best regards,
Lutz

**Comment by Seddryck** [comment]
I don't see something wrong with your setup definition and there is no known limitation about running commands in parallel.

Could you explain what you mean by "endless loop"? Is it the same set of commands restarting again and again or some of the commands are never ending?

**Comment by luwer** [comment]
By investigating via SQL Profiler I found, that it starts the `EXEC stored_procedure` commands, that are in my sql-files over and over.

So my sql file looks like this:

```
EXEC stored_procedure 'parameter1' 'parameter2' ...
```

The stored procedure is started and finished as it should be.

It just doesnt stop.

Hope that explains it a bit.

**Comment by Seddryck** [comment]
I tried to reproduce but didn't succeed. Have you been able to reproduce this on AdventureWorks or any other public database. If it'sthe case I'd be pleased to investigate further.

**Comment by luwer** [comment]
I will be at work again tomorrow. 
Let you know if I can find some more info on this.

**Comment by luwer** [comment]
Okay, I feel silly now.

It seems like my procedure was not working as i expected.
Plus I had a misspell with one parameter in my script :)

Once corrected, everything works fine.

Thanks for the help,
even tho it was not needed. 

Best Regards,
Lutz

**Comment by luwer** [comment]
Another strange thing:
When I try to run it like this:
```
<group name="group">
        <setup>
            <tasks parallel="0" run-once="1">
                <table-reset name="skript_group_1.1"/>
                <table-reset name="skript_group_1.2"/>
                <table-reset name="skript_group_1.3"/>
                <table-reset name="skript_group_1.4"/>
                <table-reset name="skript_group_1.5"/>
                <table-reset name="skript_group_1.6"/>
                <table-reset name="skript_group_1.7"/>
                <table-reset name="skript_group_1.8"/>
                <table-reset name="skript_group_1.9"/>
                <table-reset name="skript_group_1.10"/>
                <table-reset name="skript_group_1.11"/>
                <table-reset name="skript_group_1.12"/>
                <table-reset name="skript_group_1.13"/>
                <table-reset name="skript_group_1.14"/>
                <table-reset name="skript_group_1.15"/>
            </tasks>
            <!--Run Packages-->
            <tasks parallel="1" run-once="1">
                <sql-run name="skript_group_2.1.sql" path="..\Tests\Packages\" connectionString="@DWH_META"/>
                <sql-run name="skript_group_2.2.sql" path="..\Tests\Packages\" connectionString="@DWH_META"/>
                <sql-run name="skript_group_2.3.sql" path="..\Tests\Packages\" connectionString="@DWH_META"/>
                <sql-run name="skript_group_2.4.sql" path="..\Tests\Packages\" connectionString="@DWH_META"/>
                <sql-run name="skript_group_2.5.sql" path="..\Tests\Packages\" connectionString="@DWH_META"/>
            </tasks>           
        </setup>
```
It works fine, als long as I have less than 10 sql commands in the second group of tasks.

As soon as I put 10 commands in it, it keeps running them over and over.
Hope that helps.

**Comment by Seddryck** [comment]
Thx. I Will take a look to this Tonight.

**Comment by luwer** [comment]
The problem is solved on my end.

It was a human error on my end.

Once corrected, everything worked fine.

**Comment by Seddryck** [comment]
Ok, good news. Thx for the feedback, really appreciated.
