### ISSUE TITLE
DAX SUM / SUMX calculation does not work

### ISSUE THREAD

**Issue by devnkd** [Seddryck/NBi#199]
I'm trying to test the following DAX function which start with SUMX but keeps getting "Function not found" error. I decided to try a simple SUM and got the same issue. Is there a support for SUM or SUMX with NBi testing?

=SUMX(FILTER(MyTable, AND(MyTable[Date] = EARLIER(MyTable[Date]), MyTable[Account] = EARLIER(MyTable[Account]))), MyTable[Amount])

**Comment by Seddryck** [comment]
I propose to perform the follow-up of this query in Stackoverflow: http://stackoverflow.com/questions/38231412/testing-dax-calculation-with-nbi
