### ISSUE TITLE
Unable to run nbi tests using nunit-console.exe

### ISSUE THREAD

**Issue by debarshi09** [Seddryck/NBi#202]
Hi,

Till now we are successfully able to run our nbi tests using the nunit GUI. We have a requirement now to run nbi tests in a continuous integration environment. Using the nunit-console.exe normally works but in our case we have a specific provider to connect to a Sybase datawarehouse and this is specified in the config file as follows: 

``` xml
<providers>
  <add id="SAOLEDB.12" invariant-name="System.Data.OleDb" />
</providers>
```

And what I've observed is that this configuration file is not used at all by nunit-console.exe and we keep on getting an error 'provider' not found. Looking at the stack trace it looks like it doesn't read the configuration file at all.

Have you tried using the nunit-console.exe. Any help would be much appreciated.

**Comment by Seddryck** [comment]
I haven't experimented any issue with nunit.console.exe
- What's your version of NBi ?
- Are you sure the same test-suite works with NUnit GUI?
- Are you using nunit.console.exe v2.6
- What are the command line attributes of nunit-console.exe?
- What's the name of your config file?

**Comment by debarshi09** [comment]
Hi Seddryck,

Thanks for getting back. Following are answers to your questions :
- We are using 1.12.0.7 version of NBi.
- Yes, we have been running the tests in the test-suite with NUnit GUI for the last 4-5 months.
- Yes, we are using version 2.6 of nunit-console.exe.
- The command line we are using is nunit-console.exe LocalPath\NBi.Nunit.Runtime.dll /result:Testing.xml /include:CategoryName. We are following the documentation from the nUnit site : http://www.nunit.org/index.php?p=consoleCommandLine&r=2.6.4.
- The name of our config file is NBi.Nunit.Runtime.dll.config in accordance with nunit documentation for configuration files (http://www.nunit.org/index.php?p=configFiles&r=2.6.4).

I can send you the stack trace if that would help in any way. But I guess the best would be to do a similar test on your side.

Let me know if you need any other information or if you have any leads.

Thanks,
Debarshi

**Comment by FuegoArtificial** [comment]
Hi @debarshi09 ,

in the command line you might need to call a nunit-file. Do you have such one?
The documentation you may need is here: http://www.nbi.io/docs/installation-environment/
Although it's not all you need, yet, this might give you a heads up.

Does this help?
Cheers

**Comment by Seddryck** [comment]
Stack trace could help because my environment could be different than yours. But, before going further I'd recommend to follow @FuegoArtificial suggestion because I'm creating NUnit file and I've no issue (and it's a key differencebetween our environments)

**Comment by Seddryck** [comment]
As a general comment I'd really recommend to use NUnit file, it is cleaner than the ugly hack of the fixed configure name. It is also easier to share binaries between test suites and configurations.

**Comment by Seddryck** [comment]
@debarshi09 Could you confirm that the switch a `nunit` file has resolved your problem?If it's the case just close this issue. Thx.

**Comment by debarshi09** [comment]
Hi,

No, I didn't try that till today as I had found a way to use nunit classes to load the NBI dll and run the tests from a .NET console application. Yes, using the .nunit file would also work but I was trying to avoid installing nUnit on our Integration Server and using just the nunit dll in the project would do the work for me. Thanks for your help @FuegoArtificial and @Seddryck .
