### ISSUE TITLE
Test name cannot contain xml special characters

### ISSUE THREAD

**Issue by FuegoArtificial** [Seddryck/NBi#206]
the test name (a property right now) cannot contain special characters like '&'.
suggestion: enable name as an element so the cdata tag can be used.

use case: getting all job names to test run times of jobs. within the name there is an '&'. If using the job name as part of the test name the test generation fails due to the '&'.

**Comment by Seddryck** [comment]
I doubt that NUnit itself supports "&" inside the test name. It's probably a won't fix.

**Comment by FuegoArtificial** [comment]
Would a name element besides a property allow the cdata tag? I use it in queries so it's being accepted.

edit: It's a little constraining adding a names must not have "<" or "&"... but I'll find a work around :)

**Comment by Seddryck** [comment]
@fuegoartificial the first issue is to know if NUnit itself supports a test name with an &. I doubt. If it's not supported, I have no chance of success to implement support for this in NBi. 

Anyway, have you got this problem when generating tests with Genbil ?

**Comment by FuegoArtificial** [comment]
I see the problem here :)
Yes, it happens when generating tests with Genbil. It states incorrect XML-Syntax. Removing the field from the template and figuring out which value of the field creates the error I figured it's the xml special characters.
In the query, which gets the test cases within Genbil-Script, I can work around it to take a second derived field replacing the non-conform characters. And there are other ways, to avoid it, too :) No big deal, it just took some time to realize the issue.

**Comment by Seddryck** [comment]
It could be good idea to add a function "encode" to genbiL.

**Comment by Seddryck** [comment]
By the way isn't it the same issue than https://github.com/Seddryck/NBi/issues/125 (See also [documentation](http://www.nbi.io/automation/format-variable/))

**Comment by FuegoArtificial** [comment]
Agreed :-)
