### ISSUE TITLE
How to setup connections to OLEDB connection to Oracle DB?

### ISSUE THREAD

**Issue by Yingmin-Li** [Seddryck/NBi#209]
Hi, 

I followed instruction suggestion in Issue#101, by Installed the Microsoft OLE DB Provider for Oracle and add in config file

``` xml
<providers>
    <add id="OleDb.Oracle" invariant-name="System.Data.OleDb"/>
  </providers>
```

Then in .nbits file in connectionString add:

```
connectionString="Provider=OleDb.Oracle;Data Source=host\instance,1521; User ID=xxx;Password=xxx;Integrated Security=SSPI"
```

It reports error message 1 "multiple step ole db operation generated errors. check each ole db status value"

If I remove Provider in ConnectionString, it report error message 2 "A connection was successfully established with the server, but then an error occurred during the pre-login handshake."

Can you please help to to understand how to configure correctly the ConnectionString for Oracle DB?

Thank you!

The environment is:

Win7 Pro 64 bit
Microsoft OLE DB Provider for Oracle 12.1
NUnit 2.6.x 32 bit
NBi 1.11
remote Oracle 11g under RedHat

**Comment by Seddryck** [comment]
I'm not an expert in Oracle but your connection-string sounds weird.
1. The provider for the Microsoft OLE DB Provider for Oracle is not `OleDb.Oracle`but `MSDAORA`. MOre info on [connectionstrings.com](https://www.connectionstrings.com/microsoft-ole-db-provider-for-oracle-msdaora/)
2.  You cannot say Integrated Security=SSPI and provide a login/pwd ... you should remove the token `Integrated Security=SSPI` or the tokens `User ID` and `Password`

Typically I'd go for something equivalent to
`Provider=MSDAORA;Data Source=serverName;User ID=MyUserID; Password=MyPassword;`

and change my config file to

``` xml
<providers>
    <add id="MSDAORA" invariant-name="System.Data.OleDb"/>
</providers>
```

**Comment by Seddryck** [comment]
Would be great to have some feedback!

**Comment by Djub3r** [comment]
Hi Seddryck,

it works with 

```
<providers>
      <add id="OraOLEDB.Oracle.1" invariant-name="System.Data.OleDb"/>
</providers>
```

MSDAORA is the OleDB provider for Oracle From Microsoft
OraOLEDB is the OleDB provider for Oracle From Oracle (it must be more performant)

I used a connection string like this :

"Data Source=server:port/servicename;User ID=xxx;Password=xxx;Provider=OraOLEDB.Oracle.1;Persist Security Info=True;"

And I have no problem to connect me

**Comment by Seddryck** [comment]
Thx for the feedback @Djub3r ... will close this as it sounds to work correctly.

**Comment by DmytroAndriychenko** [comment]
For clarity, for this to work on 64bit Windows, it is essential to install 64bit Oracle OleDb provider as opposed to 32 bit. I could not get Microsoft OleDbDriver MSDAORA to work altogether on my 64bit Win7 machine. Since there is no 64 bit version of MSDAORA, one can only install Oracle 64bit OleDb provider from http://www.oracle.com/technetwork/database/windows/downloads/index-090165.html Then it works.
