### ISSUE TITLE
Override project parameters on ETL run

### ISSUE THREAD

**Issue by fpvmorais** [Seddryck/NBi#210]
Hello,

Is there any way to change Project Variables when running a package?

Thx

**Comment by Seddryck** [comment]
it depends ...

What's your version of SQL Server?
Do you try to load the SSIS from file or from SSIS Catalog
What do you mean by Project Variable (I know what's a variable and a project parameter but not a project variable)?

Check at http://www.nbi.io/docs/etl-parameters-variables/ for more infos

**Comment by fpvmorais** [comment]
Hi, 

I'm using SQLServer 2016 CU2. You're right about the name confusion. My ETL load has several project parameters (Connection strings, etc) but the two I would like to override are the BeginDate and EndDate. I've tried to use the 'parameter' syntax, while running just one of the project packages, but It didn't worked.

Is this possible?

Thank you

**Comment by Seddryck** [comment]
It should work. Could you post your test ? And explain what's wrong ... The test doesn't execute, the parameter is not overriden?

**Comment by fpvmorais** [comment]
I've tried like this:

``` xml
<system-under-test>
  <execution>
    <etl
        server="localhost"
        catalog="SSISDB"
        folder="ETL Global"
        project="ETL Global"
        name="E_Vendas.dtsx">
       <parameter name="BeginDate">20160927</parameter>
       <parameter name="EndDate">20160927</parameter>
    </etl>
  </execution>
</system-under-test>
```

Also tried to change the name of BeginDate to Project::BeginDate and !Project::BeginDate.

The error is always the following:

```
NBi.NUnit.Runtime.TestSuite.FirstTest:
System.ArgumentOutOfRangeException : No parameter named 'BeginDate' found in the package E_Vendas.dtsx, can't override its value for execution.
Parameter name: overridenParameters
```

**Comment by Seddryck** [comment]
Huuum weird ... but it rings a bell. I'll investigate this further Thursday evening

**Comment by Seddryck** [comment]
@fpvmorais could you try with this new build https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.96 

It won't fix the problem buut I hope that I'll receive something more helpful. 

Could you post the new report that will replace this one (expect to get the list of existing parameters)

```
NBi.NUnit.Runtime.TestSuite.FirstTest:
System.ArgumentOutOfRangeException : No parameter named 'BeginDate' found in the package E_Vendas.dtsx, can't override its value for execution.
Parameter name: overridenParameters
```

**Comment by fpvmorais** [comment]
Hello,

This is the result:

```
NBi.NUnit.Runtime.TestSuite.Primeiro teste:
System.ArgumentOutOfRangeException : No parameter named 'DataInicio' found in the package E_Vendas.dtsx, can't override its value for execution. List of existing parameters System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Microsoft.SqlServer.Management.IntegrationServices.ParameterInfo,System.String]
Parameter name: overridenParameters
```

**Comment by fpvmorais** [comment]
I have closed this by mistake

Thank you

**Comment by fpvmorais** [comment]
I did some debugging on my own and I think I've found the problem. I'm not exactly sure of the best way  to solve it, but, I hope it helps somehow.

When the program calls the Parameterize method @ ETLCatalogRunner.cs line 51 , the `package.Parameters` collection goes passed as the ones to be overridden. 

In this case the parameter collection of my package goes empty, and it's ok, because the package has no parameters. 

The parameters I would like to be able to override are one level up, on `package.Parent.Parameters` collection that refers the Project ones.

Maybe this can be solved by forcing the inclusion of the string `!Project::VariableToOverride` to differentiate between the package and project ones like you did for the `User::VariableToOverride` mentioned @ [http://www.nbi.io/docs/etl-parameters-variables/](http://www.nbi.io/docs/etl-parameters-variables/)

If I can help you somehow please tell, I can try to code something. 

Thank's

**Comment by Seddryck** [comment]
Thx for your help. You've the root cause of the issue but I'm a bit surprised about the design of your package. Will check this tomorrow.

**Comment by fpvmorais** [comment]
I have a set of packages that do extraction from an ERP. There are some read only parameters like BeginDate and EndDate that are common to them. This way, when the Master package that orchestrates the sequence of extractions is called, the parameters are set globally once, instead of passing around the values per package or setting them one by one. 

Is this not a common practice? Why did you find the design surprising?

**Comment by Seddryck** [comment]
You've so many ways to design packages that it's difficult to be sure that this code handle all these cases. Indeed using a project parameter and starting your ETL from a child package wasn't succesful. Should be fixed in this release:
https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.14.0-ci.4 

Note that the syntax is not different, just specify the name of the parameter (not starting by $Project::).

**Comment by fpvmorais** [comment]
I'm sorry to say but the problem persists. =\

**Comment by Seddryck** [comment]
I won't be able to fix this without a SSIS project handling project parameters the exact same way than you. Please post such a small project on github and I'll take a look and fix the issue for your case.

**Comment by fpvmorais** [comment]
Hello,

Sorry by the delay. Here's a minimal working example.

[SampleProject.zip](https://github.com/Seddryck/NBi/files/551325/SampleProject.zip)

Hope it helps :)

**Comment by Seddryck** [comment]
I'll check this tonight.

**Comment by Seddryck** [comment]
I just checked right now and indeed the release 1.13 has a bug with project params but the build https://ci.appveyor.com/project/Seddryck/nbi/build/1.14.0-ci.4 works with your sample project.

**Comment by fpvmorais** [comment]
I can confirm that it works with the sample, but when I try with my real project this error happens:

``` xml
at NBi.Core.SqlServer.IntegrationService.EtlCatalogRunner.<Parameterize>d__4.MoveNext() in C:\projects\nbi\NBi.Core.SqlServer\IntegrationService\EtlCatalogRunner.cs:line 149
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at NBi.Core.SqlServer.IntegrationService.EtlCatalogRunner.Run() in C:\projects\nbi\NBi.Core.SqlServer\IntegrationService\EtlCatalogRunner.cs:line 52
at NBi.NUnit.Execution.SuccessfulConstraint.doMatch(IExecution actual) in c:\projects\nbi\NBi.NUnit\Execution\SuccessfulConstraint.cs:line 32
at NBi.NUnit.Execution.SuccessfulConstraint.Matches(Object actual) in c:\projects\nbi\NBi.NUnit\Execution\SuccessfulConstraint.cs:line 25
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace) in c:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 198
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in c:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 88
```

Do you have any idea why?

**Comment by Seddryck** [comment]
Could you add the top part of the stack? (In the textbox under the red/green bar on NUnit).

**Comment by fpvmorais** [comment]
Please forget the last comment. It was my mistaske.

It correctly launched the package, but stopped after 30 seconds. The package takes a few minutes to run:

``` xml
NBi.NUnit.Runtime.TestSuite.Primeiro teste:
System.Data.SqlClient.SqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
  ----> System.ComponentModel.Win32Exception : The wait operation timed out
```

Is there a timeout variable for running packages?

**Comment by Seddryck** [comment]
Yes you should add an attribute `timeout` in milliseconds to your etl definition

**Comment by fpvmorais** [comment]
It's working :+1: 

Just noticed a weird behaviour, NUnit was launching the the package with the correct parameters but the package didn't start running in the catalog, as reported by the execution report. Eventually it stopped when the timeout was reached.

I've tried a few things but what seemed to solve the problem was a restart of the SQL Server Service.

Thank you for your help.
