### ISSUE TITLE
Support comparison of resultsets with a single row without keys (values only)

### ISSUE THREAD

**Issue by Djub3r** [Seddryck/NBi#215]
I want to define a tolerance for a key.

the case is the foolowing one :

I create lot of unit tests on a low level of granularity. So I get only one value (=one key) in result.
In this case, i can't define tolerance.

David

**Comment by Seddryck** [comment]
I'll not support tolerance for a key, but I could imagine a case where you define that your result-set is only row (with keyword `one-row-query` in place of `query`) and in this specific case all the cells will be a value and never a key.

**Comment by Seddryck** [comment]
As a workaround at the moment I'd recommend to use and additional known field and put it as the key something as:

``` xml
<system-under-test>
  <execution>
    select 'A', ... your query
  </execution>
</system-under-test>
<assert>
  <equalTo tolerance="10">
    <resultSet>
      <row><cell>A</cell><cell>100</cell></row>
    </resultSet>
  </equalTo>
</assert>
```

**Comment by Seddryck** [comment]
After implementing it, I don't think, it's especially smart to have to specify that the result contains one row at the query level. I'll move this to the equalTo level

``` xml
<equalTo behavior="single-row">
...
</equalTo>
```

**Comment by Seddryck** [comment]
preview available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.14.0-ci.24
