### ISSUE TITLE
CSV profile: null or empty?

### ISSUE THREAD

**Issue by pemmasani87** [Seddryck/NBi#219]
While reading the data from file nbi is reading as empty.But when there is an empty without any delimiter it is reading as null.how to make the nbi to read null as well as empty string as null

**Comment by Seddryck** [comment]
Indeed, in a CSV file, when the content of the cell is empty (two consecutives separators) NBi interprets it as `(empty)` but when the column is missing (parsing of a record-separator when some additional field-separators were expected) it interprets it as `(null)`. 

If you want to read `(empty)` or `(null)` values, you should explicitely use these values in your CSV file. Check http://www.nbi.io/docs/compare-special-generic-values/ for more info.

You could also be interested by https://github.com/Seddryck/NBi/issues/216 ... it's now available in the release 1.14.

You could also request an upgrade of the CSV profile http://www.nbi.io/docs/config-profile-csv/ to take into account two additional attributes `empty-cell` and `missing-cell` with possible values `(null)` and `(empty)` (and `(blank)`).

**Comment by Seddryck** [comment]
The feature is implemented in #275 

If interested/feedback please comment on this issue.
