### ISSUE TITLE
Passing CommandTimeout parameter

### ISSUE THREAD

**Issue by amdgoncalves** [Seddryck/NBi#221]
Hi Cédric,

I am getting CommandTimeoutException, because some test queries are taking more than 30 seconds to run, this is the default CommandTimeout value for OleDbCommand and SqlCommand. 

I haven't found a way to pass a parameter to set this property, if there is a way please could you tell me, if not could you please add this feature to NBi. 

Thank you 
António Gonçalves

**Comment by Seddryck** [comment]
You should take a look to https://github.com/Seddryck/NBi/issues/208 and use the latest beta to solve your problem. 

If it doesn't work for you please reopen the issue #208 and be sure to specify your connection string
