### ISSUE TITLE
etl test to assert failure

### ISSUE THREAD

**Issue by xiaueyg** [Seddryck/NBi#223]
Currently i can not find out to assert the failure (only successful) for etl test, it will be great to add this feature

**Comment by Seddryck** [comment]
Indeed, at the moment it's not possible but should be easy to add. I'll take care of this tonight.

**Comment by Seddryck** [comment]
The preview is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.14.0-ci.46

the syntax is 

```xml
<assert>
   <successful not="true"/>
</assert>
```

Feedback welcome.

**Comment by Seddryck** [comment]
Included in release v1.14
