### ISSUE TITLE
Error instead of fail

### ISSUE THREAD

**Issue by Goawaves** [Seddryck/NBi#225]
Hi,

When I create a test case and compare two result sets I only get 1 error when the values differ. I expected to get a fail when values differ but test case is run without "errors". Am I doing something wrong?

  <system-under-test>
   <execution>
    <query connectionString="...">
	 <![CDATA[ Select 'Antal', Count(*) From VehicleProject ]]>
    </query>
   </execution>
  </system-under-test>
  <assert>
   <equalTo>
    <query connectionString="...">
	  <![CDATA[ select 'Antal', 27 ]]>
	</query>
   </equalTo>
  </assert>
 </test>
</testSuite>

**Comment by FuegoArtificial** [comment]
hi Goa,

can you help me understand your issue better?
How does your test exactly (or with some fake SQL) look like and what are the results, and what is your expectation? It just wasn't clear for me, yet.
Are you concerned about the difference between "error" and "failure"?

Cheers

**Comment by Seddryck** [comment]
If your question is about failure/error then I can confirm that NBi doesn't make the difference between an error and a failure (all failures are reported as errors). If I'm remembering correctly, the way NUnit makes the difference between a failure and an error was too deep in the framework to let me use correctly the notions of errors and failures. When I'll update to NUnit 3.x, I'll try to review this ... but as long as NUnit 3.x doesn't come with a clean UI, I won't switch to this branch.
