### ISSUE TITLE
Uid can't be more than 255 (uid="0255")

### ISSUE THREAD

**Issue by RitaBI** [Seddryck/NBi#227]
Hi,
I have 302 test cases running using NBi and I used uid attribute for each test case in order to have a specific id for, in future, introduce this id in a database and analyze the results of tests.
However, when I add the uid attribute for test case number 256 it is returned the following error.

At line 15303: The 'uid' attribute is invalid - The value '0256' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:unsignedByte' - The string '0256' is not a valid Byte value.

The syntax used was:
<test name="STG01 vs DW01 online items " uid="0256">

Can you help me solving this problem? Am I using in a wrong way this attribute?

Thank you in advance,

**Comment by Seddryck** [comment]
You're correctly using it, it's a bug. 

Most (all?) of us use the name as the identifier of the test. It's technically possible to have two tests with the same name but it's not recommended. Somewhere I think that changing the name's test is equivalent to changing the test.

I'll fix the bug before end of week and provide a preview with this fix implemented.

**Comment by Seddryck** [comment]
Set max value for this attribute to 4294967295

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.14.0-ci.48 (Tab artefacts)

**Comment by RitaBI** [comment]
Thanks a lot for correct this issue.
I'm using xml results to insert information in database and I want to use uid to have a unique identifier of tests for make more easy the location and possible correction of those tests in nbits file.

Thanks again.

**Comment by Seddryck** [comment]
Included in release v1.14
