### ISSUE TITLE
Support of a regex operator for strings within predicates

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#229]
Currently when performing assertions such as ```all-rows```, ```no-rows```, ... predicates support the operators ```equal```, ```more-than``` and ```less-than```. The idea is to add support for a regex operator for string comparison.

It will allow to test that all the values of a given column are effectively validating a regex.

**Comment by FuegoArtificial** [comment]
Is the difference to the matchpattern-assertion that it would be applicable to certain columns instead of just one available?

To have some context: The current matchpattern-assertion-syntax looks like this and the resultset of the system-under-test must be one column. At least I didn't try using more than one.

```xml
<assert>
   <matchPattern>
      <regex>$RegEx$</regex>
   </matchPattern>
</assert>
```

**Comment by Seddryck** [comment]
The ```matchPattern``` assertion is intended to work with a cube (dimension/level/hierarchy) and the assertions ```all-rows``` and ```no-rows``` are more intended to be used with result-sets.

I agree that somewhere there is a kind of overlap but the newly proposed feature is more generic than the existing one.

I'm planning something as 

```xml
<assert>
   <no-rows>
      <variable column-index="3">Foo</variable>
      <predicate>
         <matches-regex>$RegEx$</matches-regex>
      </predicate>
   </no-rows>
</assert>
```

**Comment by FuegoArtificial** [comment]
Ah, I see! An existing, though very generic approach, is the one discussed here, which works great with custom SQL queries and one column: https://github.com/Seddryck/NBi/issues/106
Just to make sure you aware of it :)
Having more support in that area sounds good!

**Comment by Seddryck** [comment]
Another advantage of this approach is that you could use it for an assertion such as "more-than 90%"

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.15.0-ci.99

**Comment by Seddryck** [comment]
Available in beta: https://github.com/Seddryck/NBi/releases/tag/v1.15-beta
