### ISSUE TITLE
Teradata connection with nbi 1.14

### ISSUE THREAD

**Issue by sapnakap** [Seddryck/NBi#234]
I want to use NBI for teradata vs OLAP cube comparison.
Could anyone help me with the steps required for teradata configuration for nbi.
What changes are required for providers, drivers etc 
Any sample connection string to be used.

**Comment by Seddryck** [comment]
I never used Teradata but apparently it comes with an [Oledb provider](http://downloads.teradata.com/download/connectivity/ole-db-provider) that you should install on the machine running your test-suite.

After this you should be able to use the feature [additional provider](http://www.nbi.io/docs/connection-providers/#register-additional-providers) to help NBi find which provider should be used for your connection string.

Without any guarantee, I'd say that you should add this to your NBi config file
```xml
<nbi testSuite="...">
  <providers>
    <add id="TDOLEDB" invariant-name="System.Data.OleDb"/>
  </providers>
</nbi>
```
and use this kind of connection string in your tests:

```
Provider=TDOLEDB;Data Source=myServerAddress;Persist Security Info=True;
User ID=myUsername;Password=myPassword;Session Mode=ANSI;
```

Please, comment if it was successful or not.

**Comment by sapnakap** [comment]
I am not sure if tdoledb works with 64 bit system as the one I installed is not working.
Could you guide me which other provider I can use for teradata to work.

**Comment by Seddryck** [comment]
If the OleDB provider is not running on 64 bits architecture, you can try the ODBC driver http://downloads.teradata.com/download/connectivity/odbc-driver/windows

In this case you don't need to register an additional provider, just using the keyword "driver" in the connection string is enough to switch to system.data.odbc namespace.

**Comment by Seddryck** [comment]
Is it possible to receive some feedback?
