### ISSUE TITLE
<![CDATA[ ]]> missing in queries after test creation using Genbil

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#240]
Hi Cedric,

I have tried to create some tests using the genbil, but I am missing the `<![CDATA[ ]]>` in the created tests and I also get the the **special signs misinterpreted** in the result (signs like <, >, etc. in queries).

**Actual result:**
```
select [Measures].[all] on 0, [all].[all].Children on 1 from 
WHERE 1 &lt; 2
```

**Expected result:**
```
<![CDATA[
select [Measures].[all] on 0, [all].[all].Children on 1 from []
WHERE 1 < 2
]]>
```

Is there any way to get `<![CDATA[ ]]>` and not to misinterpret speacial signs (expected result) in the created test suite?

Please find the template used and the result attached.

[test.zip](https://github.com/Seddryck/NBi/files/760767/test.zip)

```xml
<test name="Compare '$measure$' exposed by '$hierarchy$'">
	<description>Check if the same query executed on two instances of the cube have the same result. Specifically, for measure '$measure$' by dimension/hierarchy '$dimension$/$hierarchy$' through perspective '$perspective$'</description>
	<edition author="$username$" created="$now$"/>
	<category>$measure$</category>
	<category>$dimension$</category>
	<category>$hierarchy$</category>
	<system-under-test>
		<execution>	
			<query>
				<![CDATA[
				select [Measures].[$measure$] on 0, [$dimension$].[$hierarchy$].Children on 1 from [$perspective$]
				WHERE 1 < 2
				]]>
			</query>
		</execution>	
	</system-under-test>
	<assert>
		<equalTo>
			<query>
				<![CDATA[
				select [Measures].[$measure$] on 0, [$dimension$].[$hierarchy$].Children on 1 from [$perspective$]
				]]>
			</query>
		</equalTo>
	</assert>
</test>
```

**Comment by Seddryck** [comment]
Is it different than https://github.com/Seddryck/NBi/issues/161 ?

What do you mean by **special chars misinterpreted**? Values such as ```&lt;``` is perfectly valid in an xml file and is interpreted correctly (I mean translated to ```<```) when the file is read by NBi. If you run your test above, NBi won't complain and will correctly parse your query. What's exactly your problem?

I can take an additional look but really want to be sure of the problem you're facing.

**Comment by fefeslon** [comment]
Hey,

Yes it's a duplicate to #161 (sorry for that, I have noticed it right after submitting this one).

As you say the tests are working perfectly (after the translation).

The case when this starts to be uncomfortable is when the test fails and someone tries to investigate the issue (usually by checking the query/trying to re-run it).

In that case one has to know the xml values of the special signs and has to rewrite it to be able to run the query from the failing tests.

So the motivation beside this issue is to make the code more readable for failure analysis.

Does it make sense to you?

**Comment by Seddryck** [comment]
Ok thx for the explanation, I'll close this issue and will do the follow-up in #161. But I've an idea how to fix it and I'm building the solution. Expect a preview for today.

**Comment by fefeslon** [comment]
Thanks!
