### ISSUE TITLE
Variable propagated to the generated tests

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#244]
Hi Cedric,

Is it somehow possible to propagate the variables into the tests generated by Genbil?

Example code:
```xml
   <query connectionString="@env1"
          timeout-milliSeconds="180000"
    >
     <![CDATA[
          SELECT
            ,SUM(fs.[sales_inc_vat]) AS [sales_inc_vat]
            ,SUM(fs.[sales_ex_vat]) AS [sales_ex_vat]
            ,SUM(fs.[vat]) AS [vat]

            FROM [fact_sales]
            WHERE 
              fs.[transaction_date_key] BETWEEN 20130201 AND 20161231
     ]]>
    </query>
```

I woul like to get a result like this:
```xml
   <query connectionString="@env1"
          timeout-milliSeconds="180000"
    >
     <![CDATA[
          SELECT
            ,SUM(fs.[sales_inc_vat]) AS [sales_inc_vat]
            ,SUM(fs.[sales_ex_vat]) AS [sales_ex_vat]
            ,SUM(fs.[vat]) AS [vat]

            FROM [fact_sales]
            WHERE 
              fs.[transaction_date_key] BETWEEN $start_date_key$ AND $end_date_key$
     ]]>
    </query>
```

The idea beside this is to have an option to work with variables in external settings file.
For example generate a bunch of tests that will be run on different date ranges/test environments combinations etc. that will be defined every time before running the test_suite (in external settings).

In case this is not supported, could this option be added to test generation?

Michal.

**Comment by Seddryck** [comment]
Haven't you invert your code and your result?

Anyway, it sounds possible to achieve what you're trying to do.

First you'll need to [parametrize your query](http://www.nbi.io/docs/query-parameters/). As you can see in the doc it's possible to reference the value of the parameter in the settings at the top of your test-suite. You can go a step further and use [variable-template](http://www.nbi.io/docs/query-template/) within your query but it's usally to not easy to maintain (and understand the purpose of your test).

But you can go a step further and reference an [external settings file](http://www.nbi.io/docs/config-settings-external-file/) ... it will contain the effective value of your parameter.

Is it what you're looking for?

**Comment by fefeslon** [comment]
> Haven't you invert your code and your result?
@Seddryck  Nope, first is the current code and the second is the result I wanted to get (query with variables instead of hard coded dates).

Ah thanks, this will work! I have tried to create variables inside the test suite, but parameters will definitely solve the issue.

The issue I have had was that when I have created variables in the template, it just left them blank in the generated tests (as expected) and I was looking for some workaround (solved by exchanging variables to parameters).

Thanks,

M.

**Comment by Seddryck** [comment]
If you want to use [variable-template](http://www.nbi.io/docs/query-template/) in a template, you need to escape the $ symbol by preceding it by a \ ... search for "escaped delimiter" in https://theantlrguy.atlassian.net/wiki/display/ST/StringTemplate+cheat+sheet

**Comment by fefeslon** [comment]
Definitely helped, thanks!
