### ISSUE TITLE
Request some sample scripts

### ISSUE THREAD

**Issue by fondywang** [Seddryck/NBi#250]
Hi Seddryck,

Could you please provide some sample scripts for reference?
[MyTest - Issues.txt](https://github.com/Seddryck/NBi/files/789186/MyTest.-.Issues.txt)

I have some doubts how to code it:

**Sample1:**

The same script works for some tables, but failed for some tables.
Details pls check attachment -   test name="Item-SrcToStgValue"

NBi.NUnit.Runtime.TestSuite.Item-SrcToStgValue:
NBi.NUnit.Runtime.CustomStackTraceErrorException : The column with an index of 1 is expecting a numeric value but the first row of your result set contains a value '?? ??? ??????? 10W-60aaaaaaaaaaaaaaaabbbbbcccccddd' not recognized as a valid numeric value or a valid interval. 

[No_] is nvarchar(50), but system consider it as numeric

Tried to identify the column type, but not sure how to identify the columns what I queried? 

how to combine this with queries? 

`<column  index="0" role="key" type="text"/>`

	   SELECT [No_]   
		     ,[Description]   	   
             ,[Position Group Code]  
		FROM [STG].[STG_Item]

**Sample2:**

I want to check prec is great than or equal to , how to compare great than?  I only know equalTo as it is mentioned in the document, but is there any document listed all the grammar? 
Details pls check attachment - test name="Item-SrcToStgDDL"

**Comment by Seddryck** [comment]
I'll split your initial question into three questions for clarity (see #251 and #252)

About more samples:

* You can check the folder "samples" that is available with your binaries. Unfortunatelly this folder is empty in the release 1.14 (and perhaps some others) ... see #235 but you can use this link to get access to the files: https://github.com/Seddryck/NBi/tree/master/NBi.Testing/Acceptance/Resources/Positive 
* You can read my blog at [http://seddryck.wordpress.com]

**Comment by fondywang** [comment]
Thanks so much, Yes, There are many samples I will take a look, it is really helpful! 

https://github.com/Seddryck/NBi/tree/master/NBi.Testing/Acceptance/Resources/Positive
