### ISSUE TITLE
The column with an index of 1 is expecting a numeric value but the first row of your result set contains a value 'abcdefgh'

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#251]
@fondywang

The same script works for some tables, but failed for some tables.
Details pls check attachment -   test name="Item-SrcToStgValue"
[MyTest - Issues.txt](https://github.com/Seddryck/NBi/files/789186/MyTest.-.Issues.txt)

NBi.NUnit.Runtime.TestSuite.Item-SrcToStgValue:
NBi.NUnit.Runtime.CustomStackTraceErrorException : The column with an index of 1 is expecting a numeric value but the first row of your result set contains a value '?? ??? ??????? 10W-60aaaaaaaaaaaaaaaabbbbbcccccddd' not recognized as a valid numeric value or a valid interval. 

[No_] is nvarchar(50), but system consider it as numeric

Tried to identify the column type, but not sure how to identify the columns what I queried? 

how to combine this with queries? 

``` xml
<column  index="0" role="key" type="text"/>`
    SELECT 
        [No_]   
        ,[Description]   	   
        ,[Position Group Code]  
    FROM 
        [STG].[STG_Item]
```

**Comment by Seddryck** [comment]
Your problem is not with the column ```[No_]``` (index=0) but with the column ```[Description]``` (index=1).

If you don't explicitely define the type of a ```value``` column, it's assigned to ```numeric```. It means that in your case the column  ```[Description]``` is defined as ```numeric``` but the first row is not a valid numeric '?? ??? ??????? 10W-60aaaaaaaaaaaaaaaabbbbbcccccddd'. 

To solve this problem you can define the type of each column with:
```xml
<column  index="1" role="value" type="text"/>`
<column  index="2" role="value" type="text"/>`
```
Or you can use the shortcut to override the default type for values by using
```xml
<equalTo values-default-type="text"> ...
```

**Comment by fondywang** [comment]
Tried as following format, but got error info as below, could you please help to clarify?

```xml
<assert>
   <equalTo value-default-type="text">
    <query connectionString="@second-ref">
     <![CDATA[
		SELECT [No_]
		      ,Cast([Posting Date] as int)	
              ,[Service Center]    
		FROM [STG].[STG_Sales_Invoice_Header]
     ]]>
    </query>
   </equalTo>
  </assert>
```

Got error when loading project:

`NBi.NUnit.Runtime.TestSuite.ExecuteTestCases:
System.ArgumentException : The test suite is not valid. Check with the XSD. 1 error has been found during the validation of the test-suite:
	At line 49: The 'value-default-type' attribute is not declared.
`

**Comment by Seddryck** [comment]
Check http://www.nbi.io/docs/compare-configuration/#default-type-for-a-result-set it is ```values-default-type``` with a "s".

**Comment by Seddryck** [comment]
Hi @fondywang,

If the answer is helping you, could you close this issue? 

Thx.
