### ISSUE TITLE
Check value is greater or equal than value in the assert

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#252]
@fondywang

I want to check prec is great than or equal to , how to compare great than?  I only know equalTo as it is mentioned in the document, but is there any document listed all the grammar? 
Details pls check attachment - test name="Item-SrcToStgDDL" 
[MyTest - Issues.txt](https://github.com/Seddryck/NBi/files/789186/MyTest.-.Issues.txt)

**Comment by Seddryck** [comment]
This kind of test is not officially supported by NBi at the moment but you can work-around this.

Create a ```equalTo``` assertion and for your column ```[prec]``` you can define a [one-sided tolerance](http://www.nbi.io/docs/compare-tolerances-roundings/#one-sided-tolerance).

```xml
<column index="1" type="numeric" role="value" tolerance="+1000000"/>
```

If you value can be higher than assert-value+1000000 add a few zeros :-)

**Comment by fondywang** [comment]
Thanks for quick response! This way can only handle I  know exactly how much greater than. But if I don't know , just want to check if it is greater than, then I can't use tolerance. right?

**Comment by Seddryck** [comment]
No you don't need to know the exact difference between your value in system-under-test and the value in assert.

 This method is creating an interval of valid values between the value returned in the assertion and this value + 1000000 => [x;x+10000000]. Just Check, it will work for you!

**Comment by Seddryck** [comment]
Hi @fondywang,

If the answer is helping you, could you close this issue? 

Thx.
