### ISSUE TITLE
Timeout when the query returned after 20 mins

### ISSUE THREAD

**Issue by fondywang** [Seddryck/NBi#254]
Hi Seddryck,

I have a query which takes about 20 ~ 30mins, But NBI returned as error after 30 second.  Can we change the timeout to 1 hour?

> wasn't finished after '30' seconds and has thrown a timeout, 
 ----> System.ComponentModel.Win32Exception : The wait operation timed out

Best Regards,
Fondy

**Comment by fondywang** [comment]
I tried to change the timeout in NBI.XML, But NBI.XML is complied and can't be changed.  I need to get the source code and rebuild NBI?

**Comment by fondywang** [comment]
Attach the SQL for reference, Maybe caused by the SQL?
[sql.txt](https://github.com/Seddryck/NBi/files/813405/sql.txt)

**Comment by Seddryck** [comment]
At the level of the query, you have an attribute timeout-milliSeconds. Check at [this page](http://www.nbi.io/docs/query-timeout/) for correct syntax.

**Comment by Seddryck** [comment]
Hi @fondywang,

If the answer is helping you, could you close this issue? 

Thx.

**Comment by fondywang** [comment]
Yes, It is very helpful! thanks so much for your patient!
