### ISSUE TITLE
How to run ETL when connection is identified in params file

### ISSUE THREAD

**Issue by fondywang** [Seddryck/NBi#255]
Hi Seddryck,

In SSIS environment, the connection is getting from params file , If run in SSIS, the package can run successfully, But run in NBI, it can't parse the params file to get the connection info, Can you please advise?

Error info and params:  

[error.txt](https://github.com/Seddryck/NBi/files/829868/error.txt)

Project.params:

```xml
<?xml version="1.0"?>
<SSIS:Parameters xmlns:SSIS="www.microsoft.com/SqlServer/SSIS">
  <SSIS:Parameter
    SSIS:Name="DataWarehouse_ConnectionString">
    <SSIS:Properties>
```

Best Regards,
Fondy

**Comment by Seddryck** [comment]
What do you mean by params file?

**Comment by fondywang** [comment]
This is the params file which will be loaded by SSIS and public to all packages, Then all packages can use this connection:

Project.params:
```xml
<SSIS:Parameters xmlns:SSIS="www.microsoft.com/SqlServer/SSIS">
 <SSIS:Parameter
 SSIS:Name="DataWarehouse_ConnectionString">
 SSIS:Properties
```

**Comment by Seddryck** [comment]
Sorry but I don't know or don't understand this strategy to specify parameters for an etl run.

**Comment by fondywang** [comment]
ok, thank! I will try another way!
