### ISSUE TITLE
unable to connect to MS SQL server database.

### ISSUE THREAD

**Issue by gkkarthick2k** [Seddryck/NBi#256]
I am unable to connect the DB server. please let me know what i am missing

<connectionString>Provider=SQL Server Native Client 11.0;Data Source=NFUMDEMO;Initial Catalog=PIP_TST_SOURCE;User ID=eeeeuser;Password=win@xxxxxation;</connectionString>

![image](https://cloud.githubusercontent.com/assets/25860486/23849854/038def64-07d5-11e7-82a8-11e1fb853807.png)

**Comment by Seddryck** [comment]
Remove the ```provider``` information in your connection string, it should resolve the issue.

**Comment by Seddryck** [comment]
After a quick check, I'd say that you've two options:

* As previously suggested you remove the provider information, NBI will use the .NET Framework Data Provider for SQL Server (System.Data.SqlClient).
* If you want to use the OleDb provider then you should use the valid nickname for "SQL Server Native Client 11.0": ```provider=SQLNCLI11```.

If it responds to your question please close the issue.

**Comment by gkkarthick2k** [comment]
Thanks Seddryck, this helped me to resolve this issue.
now the next question would be how to get the test results

I tried adding this, but not sure where to add this

![image](https://cloud.githubusercontent.com/assets/25860486/23892744/c399c9ae-0893-11e7-8bb4-6d3bad7c9147.png)


pls let me know.

**Comment by Seddryck** [comment]
One issue, one question. Before asking read the documentation at www.nbi.io
