### ISSUE TITLE
NBi Nuget

### ISSUE THREAD

**Issue by fpvmorais** [Seddryck/NBi#257]
Hi,

I have found this [NBi Nuget](https://www.nuget.org/packages/BiTest.NBi/) 

Are there any instructions how to set up Visual Studio to use it?

Thanks

**Comment by Seddryck** [comment]
Absolutely no idea :-) I was not aware of the existence of this package. 

I will check this soon but at the moment, I don't see how it could be helpful to have a nuget package.

**Comment by Seddryck** [comment]
I checked and found no clue on how to use it.

**Comment by fpvmorais** [comment]
I've also tried and couldn't make it work. As for the utility I think it
could be cool to have a Nuget to create a test project in a solution with
the SSIS project. We would be able to use the VS integrated tests instead
of opening the Nunit GUI.

Thanks ;)

2017-03-14 20:36 GMT+00:00 Cédric L. Charlier <notifications@github.com>:

**Comment by Seddryck** [comment]
As far as I know, it's not possible to specify a config file to the VS runner. If it's not possible to specify a config file then it's not possible to run the NBi test suite. But perhaps, the creator has found a trick to overcome this issue.

**Comment by Seddryck** [comment]
i think the following idea could work:

1. Create a class library project
1. Add references to all the dll of NBi
1. Add a reference to nunit.exe (and all the dlls in the lib folder)
1. Go to the project settings (section debug)
1. Change the start option by external program and reference nunit.exe
1. In command line arguments reference the "nunit project file"
1. Add the nunit project file, the config file and the nbits
1. Click on debug should start NUnit with the project

You could naturally replace nunit.exe by nunit-console.exe

If it works, you can build a nuget package doing all the steps for you and it should speed up the creation of a test-suite.

IMO should work :-)

**Comment by Seddryck** [comment]
It effectively works ... 
I integrated everything into a nuget package: ```Install-Package NBi.VisualStudio```
More info and project available at https://github.com/Seddryck/NBi.VisualStudio

**Comment by fpvmorais** [comment]
It works flawlessly :D

Great work!

Thanks

2017-03-18 15:42 GMT+00:00 Cédric L. Charlier <notifications@github.com>:

**Comment by Seddryck** [comment]
Thx for the suggestion and for the check.
