### ISSUE TITLE
Additional CSV Configuration

### ISSUE THREAD

**Issue by loewensteinph** [Seddryck/NBi#275]
It would be awesome if CsvProfileXml Configuration would offer two more options.

```xml
<csv-profile field-separator=";" record-separator="CrLf" firstrow-header="true" empty-cell="NULL"/>
```
- Specify if the file has a header row
Already parametrized in NBi.Core.CsvReader but not configurable

```csharp
public DataTable Read(string filename, bool firstLineIsColumnName)
        {
            if (!File.Exists(filename))
                throw new ExternalDependencyNotFoundException(filename);
            using (var stream = new FileStream(filename, FileMode.Open, FileAccess.Read))
            {
                return Read(stream, firstLineIsColumnName);
            }
        }
```
- Option to define NULL CSV value #219 
Currently defaults to (null) would be nice to have an option to specify this as NULL

**Comment by Seddryck** [comment]
Good idea. Will add it to the backlog

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.15.0-ci.82

Check syntax here under (slightly different than the proposed one).
```xml
<csv-profile
   field-separator=";" 
   record-separator="CrLf" 
   first-row-header="true" 
   empty-cell="(null)"
   missing-cell="(empty)"
/>
```

**Comment by loewensteinph** [comment]
Thanks for the addition. The first-row-header option works fine, whereas empty-cell  & missing-cell seems not to work. 

Tested it with following test:
```xml
<csv-profile
    field-separator="|"
    record-separator="CrLf"
    first-row-header="true"
    empty-cell="NULL"
    missing-cell="NULL"
/>

<execution>
          <query>
            SELECT [Key]=1,Val1='2',Val3='NULL',Val3='3'
            UNION
            SELECT [Key]=4,Val1='NULL',Val2='3',Val3='2'
          </query>
</execution>

<equalTo keys="first" behavior="multiple-rows" values="all-except-first" values-default-type="text">
          <resultSet file="..\Tests\Assertion\Sample.csv">
          </resultSet>
</equalTo>
```
CSV content

Key|Name1|Name2|Name3
1|2|NULL|3
4|NULL|3|2

Shouldnt the result set comparison classes reflect the additional options aswell?
i.e. namespace
NBi.Core.ResultSet.Comparer

**Comment by Seddryck** [comment]
Replace the value ```NULL``` by the value ```(null)``` for the elements ```empty-cell```and ```missing-cell``` in the parent element ```csv-profile``` and it should resolve your issue.

**Comment by Seddryck** [comment]
Indeed, you was right, it didn't work. But the bug wasn't really due to the introduction of the new options. I fixed it and added acceptance tests. The new build is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.15.0-ci.86

Your test is a little bit incorrect, your query should be:
```sql
SELECT [Key]=1,Val1='2',Val3=NULL,Val3='3'
UNION
SELECT [Key]=4,Val1=NULL,Val2='3',Val3='2'
```
without quotes around NULL

**Comment by Seddryck** [comment]
Available in beta: https://github.com/Seddryck/NBi/releases/tag/v1.15-beta
