### ISSUE TITLE
Error on connection string

### ISSUE THREAD

**Issue by arunvd** [Seddryck/NBi#279]
```
NBi.NUnit.Runtime.TestSuite.Dimension name
SystemAggregateException : One or more errors occurred
--->NBi.Core.ConnectionException : The Cube either does not exist or has not been processed
The connection sting used was 'Provided =Msolap.4; Integrated Security=SSPI; Data Source= xyz; Initial Catalog = 'cubename'
```
```

**Comment by FuegoArtificial** [comment]
What's your question?
Why "The Cube either does not exist or has not been processed" or how you set up proper connection strings? If so, how does this relate to NBi?

**Comment by arunvd** [comment]
Hi,

 Thanks for picking up, I got an issue here, I am making an nunit project to compare the ssas cube in dev itself for testing purpose but when I run the nunit I am getting the error show at the end but my cube is processed and I can write the mdx by browsing , I am not sure how I am getting the error.

please check below my config file and nbits file and my error,



configuration file:
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
 <configSections>
  <section name="nbi" type="NBi.NUnit.Runtime.NBiSection, NBi.NUnit.Runtime"/>
 </configSections>
 <nbi testSuite="TestingGenbi\DimensionandMeasurestest.nbits"/>
 <connectionStrings>
    <clear />
    <add name="BIDEV"        
     connectionString="Provider=MSOLAP.4;Data Source=cubename; Initial Catalog= ssascube; Integrated Security=SSPI" />
    <add name="BIUAT"
     connectionString="Provider=MSOLAP.4;Data Source=cubename; Initial Catalog= ssascube; Integrated Security=SSPI" />
  </connectionStrings>
</configuration>


Nbits file:
<?xml version="1.0" encoding="utf-8"?>
<testSuite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
  <settings>

<default apply-to="system-under-test">
       <connectionString>@BIDEV</connectionString>
      </default>
      <default apply-to="assert">
        <connectionString>@BIUAT</connectionString>
</default>
  </settings>


  <test name="Account">
    <system-under-test>
      <execution>
        <query>  

select{Account    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{Account    
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
  <test name="Costcentre">
    <system-under-test>
      <execution>
        <query>  

select{Costcentre    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{Costcentre    
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
  <test name="GL Transaction">
    <system-under-test>
      <execution>
        <query>  

select{[Measures].[GL Transaction]    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{[Measures].[GL Transaction]     
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
  <test name="Budget And Forecast">
    <system-under-test>
      <execution>
        <query>  

select{[Measures].[Budget And Forecast]    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{[Measures].[Budget And Forecast]     
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
</testSuite>

Error:
![error](https://user-images.githubusercontent.com/28649471/27086602-945bc1c0-504a-11e7-9688-35006fd148f7.PNG)

**Comment by arunvd** [comment]
Hi,

 Thanks for picking up, I got an issue here, I am making an nunit project to compare the ssas cube in dev itself for testing purpose but when I run the nunit I am getting the error show at the end but my cube is processed and I can write the mdx by browsing , I am not sure how I am getting the error.

please check below my config file and nbits file and my error,



configuration file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
 <configSections>
  <section name="nbi" type="NBi.NUnit.Runtime.NBiSection, NBi.NUnit.Runtime"/>
 </configSections>
 <nbi testSuite="TestingGenbi\DimensionandMeasurestest.nbits"/>
 <connectionStrings>
    <clear />
    <add name="BIDEV"        
     connectionString="Provider=MSOLAP.4;Data Source=cubename; Initial Catalog= ssascube; Integrated Security=SSPI" />
    <add name="BIUAT"
     connectionString="Provider=MSOLAP.4;Data Source=cubename; Initial Catalog= ssascube; Integrated Security=SSPI" />
  </connectionStrings>
</configuration>
```

Nbits file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testSuite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
  <settings>

<default apply-to="system-under-test">
       <connectionString>@BIDEV</connectionString>
      </default>
      <default apply-to="assert">
        <connectionString>@BIUAT</connectionString>
</default>
  </settings>


  <test name="Account">
    <system-under-test>
      <execution>
        <query>  

select{Account    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{Account    
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
  <test name="Costcentre">
    <system-under-test>
      <execution>
        <query>  

select{Costcentre    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{Costcentre    
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
  <test name="GL Transaction">
    <system-under-test>
      <execution>
        <query>  

select{[Measures].[GL Transaction]    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{[Measures].[GL Transaction]     
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
  <test name="Budget And Forecast">
    <system-under-test>
      <execution>
        <query>  

select{[Measures].[Budget And Forecast]    
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query> 
select{[Measures].[Budget And Forecast]     
} on 0
from [BI]

</query>
      </equalTo>
    </assert>
  </test>
</testSuite>
```

Error:
![error](https://user-images.githubusercontent.com/28649471/27086602-945bc1c0-504a-11e7-9688-35006fd148f7.PNG)

**Comment by arunvd** [comment]
Hi,
 Thanks for picking up, I got an issue here, I am making an nunit project
to compare the ssas cube in dev itself for testing purpose but when I run
the nunit I am getting the error show at the end but my cube is processed
and I can write the mdx by browsing , I am not sure how I am getting the
error.
please check below my config file and nbits file and my error,

configuration file:
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
 <configSections>
  <section name="nbi" type="NBi.NUnit.Runtime.NBiSection,
NBi.NUnit.Runtime"/>
 </configSections>
 <nbi testSuite="TestingGenbi\DimensionandMeasurestest.nbits"/>
 <connectionStrings>
    <clear />
    <add name="BIDEV"
     connectionString="Provider=MSOLAP.4;Data Source=cubename; Initial
Catalog= ssascube; Integrated Security=SSPI" />
    <add name="BIUAT"
     connectionString="Provider=MSOLAP.4;Data Source=cubename; Initial
Catalog= ssascube; Integrated Security=SSPI" />
  </connectionStrings>
</configuration>

Nbits file:
<?xml version="1.0" encoding="utf-8"?>
<testSuite xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
  <settings>
<default apply-to="system-under-test">
       <connectionString>@BIDEV</connectionString>
      </default>
      <default apply-to="assert">
        <connectionString>@BIUAT</connectionString>
</default>
  </settings>

  <test name="Account">
    <system-under-test>
      <execution>
        <query>
select{Account
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query>
select{Account
} on 0
from [BI]
</query>
      </equalTo>
    </assert>
  </test>
  <test name="Costcentre">
    <system-under-test>
      <execution>
        <query>
select{Costcentre
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query>
select{Costcentre
} on 0
from [BI]
</query>
      </equalTo>
    </assert>
  </test>
  <test name="GL Transaction">
    <system-under-test>
      <execution>
        <query>
select{[Measures].[GL Transaction]
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query>
select{[Measures].[GL Transaction]
} on 0
from [BI]
</query>
      </equalTo>
    </assert>
  </test>
  <test name="Budget And Forecast">
    <system-under-test>
      <execution>
        <query>
select{[Measures].[Budget And Forecast]
} on 0 from [BI]
</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
        <column index="0" role="value" type="text" tolerance="0.01" />
        <query>
select{[Measures].[Budget And Forecast]
} on 0
from [BI]
</query>
      </equalTo>
    </assert>
  </test>
</testSuite>



Error:
![error](
https://user-images.githubusercontent.com/28649471/27086602-945bc1c0-504a-11e7-9688-35006fd148f7.PNG
)

**Comment by Seddryck** [comment]
Your connection-string is not valid. Remove the quotes around ```BI``` in the initial catalog.

**Comment by Seddryck** [comment]
Huuuum, it sounds you have many more issues in your test-suite.

1. You must define a key for each result-set or use the tip for ```single-row``` result-set
1. not really sure how you're expecting a type ```text``` and set a tolerance of ```0.01```. Doc clearly states it's not possible to define a tolerance for text values.
1. Are you sure that your fact are ```text``` ... I'm not really expecting it.

**Comment by Seddryck** [comment]
Dear @arunvd 

Now that I answered your question (and the next ones), I'll do a comment about the way your interacting with an open-source project. 

1. It would be appreciated if you could effectively post a question and not just the first rows of a stacktrace
1. Correctly edit your question and other comments by using the correct markdown syntax to post an xml content. You don't know the syntax? Just click on the link [Styling with Markdown is supported](https://guides.github.com/features/mastering-markdown/) and read this page.
1. Would be great to have the exact error message and not something that you edited (and removed your own mistake by the way)
1. Did you check the previous issues of this repository, before creating this one? Surely not, another issue had exactly the same description and an answer was provided.
1. If we helped you to resolve your issue, say thx and close this issue

All these things take less than 1 minute to learn and then execute. But you'll show a bit of respect for the people maintaining this project and answering your question for free ... isn't it the minimum that we could expect?

**Comment by arunvd** [comment]
Hi,

Thanks for your help, I went through all the previous issues and found out the mistakes, now my nunit is upon running with no issues.

Regards
A
