### ISSUE TITLE
genbiL swaps XML elements

### ISSUE THREAD

**Issue by Hellfire1433** [Seddryck/NBi#284]
Hi guys,

When I run the genbiL-script below

```
case load query
{
SELECT a.*, ISNULL(b.KommuneKode, 999) AS KommuneKode, ISNULL(b.KommuneNavn, 'Alle kommuner') AS KommuneNavn
  FROM [Test].[vNBiTest] a
 LEFT JOIN [Test].[Kommuner] b
on a.Kommunespecifik = b. [Kommunespecifik]
where Id = '6'
} on 'Data Source=localhost;Initial Catalog=MDM;Trusted_Connection=True';

case concatenate column 'Testform' with column 'Operator';

case replace column 'Testform' with values '
	<row-count>
        <filter>
          <variable column-index="0">Praedikatvaerdi</variable>
          <predicate name="Praedikatvaerdi">
          <equal>pctPraedikatvaerdi</equal>
          </predicate>
        </filter>
	<less-than or-equal="true">pctGraensevaerdi</less-than>
	</row-count>' when values like 'Procentsats<%';
		
		template load file '..\NBi\NBiTestTemplate.nbitt';
		suite generate;
```

and use the column "Testform" in my template for assertion

```
<assert>
            $Testform$
</assert>
```

GenBI generates an output (saying marco was executed successfully) where `<less-than or-equal="true">1</less-than>` is moved to another line and hence generates wrong syntax:

```
<assert>
      <row-count>
        <less-than or-equal="true">1</less-than>
        <filter>
          <variable column-index="0">Praedikatvaerdi</variable>
          <predicate name="Praedikatvaerdi">
            <equal>-1</equal>
          </predicate>
        </filter>
      </row-count>
    </assert>
```

Do you know if there is any workaround or solution to this problem?

**Comment by Seddryck** [comment]
There is probably a bug during the serialization/deserialization process of NBi. genbi always deseralize the generated string (to ensure it's a valid test) before reserializing it. 

It shouldn't be too difficult to fix, you need to add Order attributes to the properties of the [RowCountXml](https://github.com/Seddryck/NBi/blob/master/NBi.Xml/Constraints/RowCountXml.cs) class. It should be trivial (take a look to TestXml if you want to see how to do it).

I'm extremely busy at the moment but will take time to fix this next week.

**Comment by Seddryck** [comment]
@Hellfire1515 The fix is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.15.0-ci.92 If you confirm that it's effectively fixing your issue, could you close this bug? Thx.

**Comment by Hellfire1433** [comment]
The fix works like a charm, thank you very much. I close the bug.

**Comment by Seddryck** [comment]
Available in beta: https://github.com/Seddryck/NBi/releases/tag/v1.15-beta
