### ISSUE TITLE
TestResult.xml file has role and type in the column name position instead of column name.

### ISSUE THREAD

**Issue by aniketh02** [Seddryck/NBi#285]
If the test has more number of columns in a testcase then it is difficult to understand the results. 
![columnnames](https://user-images.githubusercontent.com/29744147/28957035-b7b1aacc-790d-11e7-9f90-fdb31703293a.PNG)

**Comment by FuegoArtificial** [comment]
Hi,

what's your question?

Does the naming of columns already help?: https://github.com/Seddryck/NBi/issues/105 
As far as I understand, the latest build contains the new feature and will be included in the next release.


Cheers

**Comment by Seddryck** [comment]
@FuegoArtificial is right, adding the name of columns is under development and U already published a preview: check in the items related to next release. 

But, I'd never recommend to have more than a few ```value columns``` in a test. If needed write multiples tests. That's a general guideline for all automated tests framework: when reading the name of a faking test, you should exactly know what is wrong in your development. If you have 10 value columns, you should have 10 tests.
