### ISSUE TITLE
Test that the rows-count of a query is greater than the rows-count of another query

### ISSUE THREAD

**Issue by 0guptaShruti0** [Seddryck/NBi#286]
greater than, less than, greater than or equal to assert are not available
Eg. Compare count of employess of age 30 is greater than equal to the count of employees of age 50"

```xml
<test name="Compare count of employess of age 30 is greater than equal to the count
 of employees of age 50">
    <system-under-test>
        <execution>
            <query timeout-milliSeconds="9000000"
                  connectionString="@conn-MDS">
                  <![CDATA[
                       SELECT
                            COUNT(EmployeeID)
                       FROM Employee  
                       Where age=30
                   ]]>
            </query>
        </execution>
    </system-under-test>
    <assert>
        <greater-than-equal-to>
            <query timeout-milliSeconds="9000000" 
                    connectionString="@conn-EDW">
                   <![CDATA[ 
                            SELECT
                            COUNT(EmployeeID)
                            FROM Employee  
                            Where age=70
                    ]]>
             </query>
        </greater-than-equal-to>
    </assert>
</test>
```

**Comment by Seddryck** [comment]
The easiest answer is that you should use ```equalTo``` and intervals. With
```XML
<assert>
  <equalTo  behavior="single-row">
    <resultSet>
      <row>
        <cell>(>50)</cell>
      </row>
    </resultSet>
  </equalTo>
<assert>
```
http://www.nbi.io/docs/compare-intervals/

But, it's not how you should write tests with NBi. It's surely better to use the following features:

* [rows count](http://www.nbi.io/docs/resultset-rows-count/)
* If you are on a dimension (SSAS): [members count](http://www.nbi.io/docs/members-count/)
* optionally check also this feature: [all rows](http://www.nbi.io/docs/resultset-all-no-rows)

**Comment by Seddryck** [comment]
Sorry, was on holiday previous weeks and probably not correctly read your question. Checking my answer and it's not really the best that i could provide.

If I had to write a test similar to the one suggested in your example, I'd go this way: Test that in a set with all the rows where age is 30 or 50, assert that I've more rows where age is 30 (the subset with rows where age is 30 has more than 50% of all the rows of the initial set).

```xml
<test name="Compare count of employees of age 30 is greater than equal to the count
 of employees of age 50">
    <system-under-test>
        <execution>
            <query timeout-milliSeconds="9000000"
                  connectionString="@conn-EDW">
                  <![CDATA[
                       select Age, *
                       from Employee  
                       where Age=30 or Age=50
                   ]]>
            </query>
        </execution>
    </system-under-test>
    <assert>
        <row-count>
           <filter>
               <variable column-index="0">Age</variable>
               <predicate name="Age">
                    <equal>30<equal>
               </predicate>
           <filter>
           <more-than or-equal="true">50%<more-than>
       </row-count>
    </assert>
</test>
```

**Comment by Seddryck** [comment]
Nevertheless, I understand and agree that it would be useful to accept have a more natural notation for this kind of test. I'd add this to the backlog.

**Comment by 0guptaShruti0** [comment]
Thanks for above solution Seddryck.
 How to solve if we compare results on 2 diff env
 Compare count of employess of age 30 on UAT is greater than equal to the count of employees of age 50 on PROD

**Comment by Seddryck** [comment]
I see no way to work-around your issue. I'll add a feature for this in release 1.17
```xml
<test name="Compare count of employees of age 30 is greater than equal to the count
 of employees of age 50">
    <system-under-test>
        <resultSet>
            <query connectionString="@conn-EDW">
                  <![CDATA[
                       select Age, *
                       from Employee  
                       where Age=30
                   ]]>
            </query>
        </resultSet>
    </system-under-test>
    <assert>
        <row-count>
           <more-than or-equal="true">
             <projection type="row-count">
               <resultSet>
                  <query connectionString="@conn-Other">
                     <![CDATA[
                       select Age, *
                       from Employee  
                       where Age=50
                      ]]>
                   </query>
               </resultSet>
             </projection>
           <more-than>
       </row-count>
    </assert>
</test>
```

**Comment by Seddryck** [comment]
Will need to
- [x] Refactor ```IResultSetLoader``` to become ```IResultSetResolver```
- [x] Create a helper for building a ```IResultSetResolver```
- [x] Create a ```IScalarResolver``` supporting an integer
- [x] Create a ```IScalarResolver``` supporting a percentage
- [x] Create a ```IScalarResolver``` supporting a global-variable
- [x] Create a ```IScalarResolver``` supporting a projection (Row-Count) on a ResultSet
- [x] Create a helper for building a ```IScalarResolver```
- [x] At xml level accept that the child of ```more-than``` (and assimilated) can be a ```projection```
- [x] At xml level accept that the child of ```more-than``` (and assimilated) can be a ```scalar-query```

**Comment by Seddryck** [comment]
@0guptaShruti0 A version supporting the syntax described above (projection) is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-alpha.1+95.build.203 is available. Feedback welcome!

**Comment by Seddryck** [comment]
Included in https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-beta.106.build.213

**Comment by aniketh02** [comment]
This feature is working perfectly but I mention Settings in external file then the test is failing saying that no reference to the connection. If the connection string is in .nbits file it working,

**Comment by Seddryck** [comment]
Once again, I cannot reproduce your bug and your report is missing key information: fullname of the version, is it specific or not to this test, are you new with connection strings into config file ... etc.

Community is one of the most important aspects of open source, but sometimes a few bad actors can ruin the experience for the group. I took the decision to not invest more time into your issues until you start to communicate clearly. I spent a few hours this week to try to reproduce your bugs but I'm just wasting my time and delaying new features. I won't continue like this, you should clearly learn to collaborate or I'll block you.
