### ISSUE TITLE
ReportServer connection string as reference

### ISSUE THREAD

**Issue by rjankovic** [Seddryck/NBi#295]
When loading a report from the ReportServer DB, is it possible to use a reference for the "source" attribute? What would the settings section look like? 

I use references for the dataset connection string, that works, but for the source, it keeps complaining:
```
NBi.NUnit.Runtime.TestSuite.ExecuteTestCases:
System.NullReferenceException : A reference named 'RS_CS' has been found, but no element 'report' has been defined
```

```xml
			<execution>
				<report
				  source="@RS_CS"
				  connectionString="@works_fine"> ...
				</report>
			</execution>`
```
```xml
<settings>
<reference name="RS_CS">
      <connectionString>...</connectionString>
  </reference>
</settings>`
```
Thanks

**Comment by Seddryck** [comment]
At this [page of documentation](http://www.nbi.io/docs/config-defaults-references/#values-configurable-in-a-default), you've an example of settings (reference/default) for a ```report```. Have you tried this notation?

**Comment by rjankovic** [comment]
The default did the trick. Thanks a lot!

**Comment by Seddryck** [comment]
Thx for feedback
