### ISSUE TITLE
Make ignore role standard unless otherwise specified

### ISSUE THREAD

**Issue by Code-nomad** [Seddryck/NBi#296]
Example:
```xml
      <equalTo>
            <column index="0" role="key"/>
            <column index="1" type="numeric" role="value" tolerance="0.001"/>
            <column index="..." role="ignore"/>
            <resultSet ..../>
      </equalTo>
```
Columns that are not to be included in the test are currently marked with the ignore keyword. On big tables of which you only want to check one or two columns you have to specify ignore on all the others. 

The feature proposition is: Make ignore standard behavior unless specified otherwise.

**Comment by Seddryck** [comment]
I understand the unfriendliness of the current design when most of the columns must be set to ```ignore```. Nevertheless, changing the default behaviour (all columns are keys except the first) is a huge breaking-change and will probably break 20% of the tests that are coded with NBi.

I'll check further the best solution but I'll probably add an attribute at the level of the ```equalTo``` assertion to specify that by default columns should be ignored.

**Comment by Code-nomad** [comment]
I was talking to Wim last week about a possible non mandatory attribute remarking default behavior. That might be a slightly more elegant solution.

**Comment by FuegoArtificial** [comment]
How could a use case look like to ignore columns? I never select columns I don't test for, that's why I ask.

**Comment by Seddryck** [comment]
@FuegoArtificial If you've a stored procedure returning 3 columns (1 key and two values), the best practice is to have two tests, one checking the first value-column and ignoring the second and a second with the opposite configuration.

Another case is when you've a CSV file with many information including the few columns that you need for your assertion.

**Comment by FuegoArtificial** [comment]
ah okay, that makes sense.
I disagree with that best practice to have an extra test for each value along the same entities, so maybe that's why I never have that use case. 
There can be a heavy performance impact on the one side and I don't see a reason not to test multiple values at once on the other side. But maybe that's a matter of taste to understand which values fail just from the test name instead of having to look on the error result table.

**Comment by Seddryck** [comment]
Finally, I just added an option to specify ```none``` for the ```values``` attribute of the ```equalTo``` assertion. If you select this option it means that you must specify one by one all the columns that should be treated as a value column.

**Comment by Seddryck** [comment]
Available in beta: https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-beta.20.build.18
