### ISSUE TITLE
Problem with MDX query parameters

### ISSUE THREAD

**Issue by Pplatteeuw** [Seddryck/NBi#298]
Hello, 

We wrote a test suite containing the following code 

```
 <test name="21. Test de la superficie soutenue ICRD" uid="00021">
	<description>
		Pour une année de finalisation donnée, une année comptable donnée et pour la source ICRD, la superficie soutenue ne devrait pas varier pour un
		échantillon de données constant.
	</description>
	<edition author="xxxxxxxxxxxxxxx">	</edition>
	<system-under-test>
		<execution>
			<query connectionString="Provider=MSOLAP.4;Data Source=xxxxxxxxxxx;Integrated Security=SSPI;Initial Catalog=DATAWAREHOUSE_OPW;User Id=xxxxxxx;Password=xxxxxxxxxxxxxx">
				SELECT NON EMPTY { 
						[Measures].[Superficie Soutenue ICRD] 
								 } 
				ON COLUMNS FROM [DATAWAREHOUSE OPW]
				WHERE 
					( 
						StrToMember(@Source), StrToMember(@DatePayFinop), StrToMember(@DateFinFinop)
					) 
					
				<parameter name="Source">
					[Gen Source].[Source].&[6]
				</parameter>
				<parameter name="DatePayFinop">
					[Date Paiement Finop].[Annee].&[2016]
				</parameter>
				<parameter name="DateFinFinop">
					[Date Finalisation Finop].[Annee].&[2016]
				</parameter>
			</query>
		</execution>
	</system-under-test>
	<assert>
		<equalTo>
			 183761.88
		</equalTo>
	</assert>
</test>

```

The query works on our SSAS server and on our SSRS server (with the parameters). But when trying to run the test in Nbi, we get the following message  : 

The test suite is not valid. Check with the XSD. 1 error has been found during the validation of the test-suite:
	At line 0: Une erreur s'est produite lors de l'analyse de EntityName. Ligne 532, position 30.

Ligne 532, position 30 is the first "r" in the following line : 
 [Gen Source].[Source].&[6]

I can't figure what I'm doing wrong... 
Can somebody help me understand ? 

Many thanks in advance

**Comment by Seddryck** [comment]
Hello,

The issue is related to the symbol ```&``` (ampersand) in your parameter. This symbol has a special meaning in xml and must be escaped. Due to this symbol, your Xml file is not valid. 

To achieve this you can replace this ```&``` by ```&amp;```. Another way is to surround the value of the parameter by the tags  ```<![CDATA[``` and ```]]>``` (more info at https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean)

**Comment by Pplatteeuw** [comment]
Thank you, it was indeed that character posing problem. 
Thank you for the support
