### ISSUE TITLE
Support of result-sets defined in files in the system-under-test

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#300]
Until now, it's only possible to define a query in a system-under-test but we've a use-case to define a flat file containing the result-set in place of the query. In fact during the setup of the test, we'll execute an executable creating a flat file and we need to check its content.

```xml
<system-under-test>
   <result-set file="myFile.csv"/>
</system-under-test>
```

Suggested by @WimDeRons

**Comment by FuegoArtificial** [comment]
Could this also be a workaround for the OData-Feed for SSRS-Reports
https://github.com/Seddryck/NBi/issues/40 ?
Then the Odata-feed could be caputured and saved as a CSV once and later compared against again. with a new capture?

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-beta.59.build.56

**Comment by Seddryck** [comment]
@fuegoArtificial yes it could. The use-case that we have is to check the output of a web service, during setup we call it and process the output to CSV then we validate it. You could achieve the same result with SSRS.

**Comment by FuegoArtificial** [comment]
@Seddryck brilliant!
