### ISSUE TITLE
Global variables for predicates

### ISSUE THREAD

**Issue by Pplatteeuw** [Seddryck/NBi#301]
Hello again, 

What can you do when you don't know in advance the value you'll have to test against in a predicate ? 
Example : 
I've got a query sending back a colmun containing a year. This year must be smaller (using less-than is easy) than the current year... But I don't want to edit the test in January to change the year I'm comparing to... 
So I'd like to have a variable or something that can specify the current year... 
How can I do that ?

**Comment by Seddryck** [comment]
At the moment, it's not possible to define dynamic variables in your test. But I could create relatively easily something useful for you.

Would it make sense, if NBi was supporting the following syntax:

At the top of the test-suite (same level than ```settings```):
```xml
<variables>
  <variable name="year">
    <script language="c-sharp">
       DateTime.Now.Year
    </script>
  <variable>
</variables>
```
And in the test(s)
```xml
<assert>
   <all-rows>
      <alias column-index="1">Year</variable>
      <predicate name="Year">
           <less-than>@year<less-than>
        <predicate>
   </all-rows>
</assert>
```

**Comment by Pplatteeuw** [comment]
I would indeed solve my current problem. 
Thank you very much

**Comment by FuegoArtificial** [comment]
Is there a way to use "less than" with a sql query dynamically returning the current year to solve your problem? SELECT year(getdate())?

**Comment by Seddryck** [comment]
@FuegoArtificial ```less-than``` is expecting a value nothing else. 

Introduction of variables is a feature requested since long and could easily solve this kind of limitation. To be honnest, I'm not 100% convinced that it's a good practice for automated tests, but if we want to expand the scope to data quality then in this case, it's a must ... let's go for implementation.

**Comment by Seddryck** [comment]
@Pplatteeuw and @FuegoArtificial 

An alpha build is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-alpha.1+69.build.62

The syntax described above is supported but only available for ```all-rows``` and ```no-rows``` assertions.

A working example can be found for the tests 0008 and 0009 https://github.com/Seddryck/NBi/blob/develop/NBi.Testing/Acceptance/Resources/Positive/QueryAllNoRows.nbits

If validated, I can generalize the same approach relatively easily at some other place (```row-count```) but would be really helpful to have a clear view or where you think it will be needed.

**Comment by FuegoArtificial** [comment]
I don't have an opinion, because I wouldn't use this approach right now, but might adapt it later at some point :)
Thanks for asking for feedback!

**Comment by Seddryck** [comment]
I found a bug related to this new feature (assignement of a reference for a predicate when the predicate is not expected it - such as lower-case or upper-case).

I also included the branch about implicit variables for the predicate (and the renaming to alias) #301

New alpha: https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-alpha.1+74.build.66

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.16.0-beta.74.build.67
