### ISSUE TITLE
Define a variable with a SQL query

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#304]
At the moment it's possible to assign a value to a variable with a c-sharp script. It should be possible to do the same with a SQL query.

```xml
<variable>
  <query-scalar connectionString="...">
           select top 1 x from myTable where column = @param
           <parameter name="param">'myValue'</parameter>
   </query-scalar>
</variable>

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-beta.102.build.209

**Comment by aniketh02** [comment]
Documentation is missing on the site for global varibales?
.
