### ISSUE TITLE
Unable to execute dtsx file with project parameters

### ISSUE THREAD

**Issue by Chresten888** [Seddryck/NBi#321]
Hi Seddryck
I am developing a SSIS package in sql server version 2012. I have the dtsx file is saved locally, just as Visual studio saves it. My package uses project parameters to setup a connection string towards a sql database.
I have made a NBI test where I would like to execute the SSIS package. I am able to execute the dtsx file from NBI, if I do not use project parameters, but only package parameters. Is there a way to execute the dtsx file locally on my pc from NBI with project parameters? If yes, it would be nice with an example - If no can it be accomplished in another way?
For me it does not make sense, that I can call a dtsx file with project parameters, since there are no references to the param.proj file in the dtsx file, but it just sounds like it is possible, when I read the documentation in www.NBI.io

My NBI test (The DPLCatalog is a project parameter)
```xml
<system-under-test>
  <execution>
    <etl path="C:\...\ETLExample\" name="ETLExample.dtsx" version="SqlServer2012">
      <parameter name="DPLCatalog">D7DPL_ETLExamplePOC</parameter>
    </etl>
  </execution>
</system-under-test>
```

**Comment by Seddryck** [comment]
Hi,

Which version of NBi are you using? apparently I solved the same kind of issue in https://github.com/Seddryck/NBi/issues/210 and it's included in release v1.14

**Comment by Chresten888** [comment]
Hi Seddryck
Thanks for your fast time to respond.
I have downloaded the latest version of NBI framework (NBi-1.16.0.2).
In issue #210 ,is he executing from a file or from SSISCatalog?

Error I am getting in Nunit GUI:
```
NBi.NUnit.Runtime.TestSuite.SSIS execution test2:
System.ArgumentOutOfRangeException : No parameter or variable named 'DPLCatalog' found in the package ETLExample, can't override its value for execution.
Parameter name: param.Name

at NBi.Core.SqlServer.IntegrationService.EtlDtsRunner.Parameterize(IEnumerable`1 parameters, Package& package)
at NBi.Core.SqlServer.IntegrationService.EtlDtsRunner.Run()
at NBi.NUnit.Execution.SuccessfulConstraint.doMatch(IExecution actual)
at NBi.NUnit.Execution.SuccessfulConstraint.Matches(Object actual)
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
```

**Comment by Seddryck** [comment]
I'm sorry but I don't think it's possible to run a package, designed to be hosted in SSIS Catalog, from a place outside of this catalog. In #210, the tested package was hosted on SSIS Catalog and from there it's possible to override project parameters but from the file, in standalone, I doubt. When I try to simulate this, the package has no parameter with the names mapping the project parameters.

```
The variable "$Project::CountyFilter" was not found in the Variables collection. The variable might not exist in the correct scope.
```
I also tried to add this variable but it's impossible to add a variable in the namespace $Project. 

IMO, it's a won't fix and you should rely on hosting your packages in SSIS Catalog and start them from there. Anyway, I dropped a new version with an attempt to fix this (it's an improvement but probably not related to your case) at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-RC.2+1.build.218

**Comment by Chresten888** [comment]
Hi Seddryck
Ok, that was also what I expected. Thanks for the answer - Much appreciated. Thumbs up for a sweet framework:-)
