### ISSUE TITLE
Test could be defined as not-implemented

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#324]
At the moment you've the possibility to use the ```ignore``` element to specify that a test should not be run. But, anyway the test should be valid from a syntax point of view. This new option will let you the opportunity to specify that a test should exist but has not been implemented at all (so the system-under-test and assert are not expected).

```xml
<test name="...">
  <description>...</description>
  <category>...</category>
  <not-implemented>
     <reason>This kind of test is not supported by NBi</reason>
  </not-implemented>
</test>
```
A not-implemented test will be ignored and a category will automatically be added (not_implemented)

**Comment by FuegoArtificial** [comment]
Hi @Seddryck ,

would it make sense to directly write the reason into the element not-implemented instead of having an extra reason-element within? 
```
<test name="...">
  <description>...</description>
  <category>...</category>
  <not-implemented>
       This kind of test is not supported by NBi
  </not-implemented>
</test>
```

This would be consistent with the ignore-element, which directly contains the ignore-reason.
```
    <ignore>
         my reason
    <ignore>
```

Cheers

**Comment by Seddryck** [comment]
Yes should also be supported.

**Comment by Seddryck** [comment]
The elements following the new element ```not-implemented``` (within the scope of the test) will not be validated against the xsd, letting you define a completely invalid test. Anyway the tahs above such as description, category or traits (even ignored) will be parsed an interpreted. Not implemented as a prevalence on ignore.

Final syntax:

```xml
<test name="...">
  <description>...</description>
  <category>...</category>
  <not-implemented>This kind of test is not supported by NBi</not-implemented>
  <any-tag>
      <any-child-tag/>
  </any-tag>
  <ohhh-another-tag/>
</test>
```

**Comment by Seddryck** [comment]
Alpha version available at: https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.0-alpha.1+112.build.237

This won't be included in 1.17 but in 1.18

**Comment by FuegoArtificial** [comment]
would the reason for not-implemented be returned in the result-xml as well?

**Comment by Seddryck** [comment]
Yes, it is. If a test is not-implemented then it will be ignored and the reason if non-implementation will be reported in the ignore message.
