### ISSUE TITLE
An empty string is not accepted as the default value when adding a column in GenbiL

### ISSUE THREAD

**Issue by WimDeRons** [Seddryck/NBi#346]
To avoid the use of (none) as a default value, an empty string was used. However, this results in an error during the execution of the GenbiL script.

Remark: A string with a single space is used as a workaround.

**Comment by Seddryck** [comment]
I’ll add support for the following code ```case add column 'col' values empty```.

**Comment by Seddryck** [comment]
You must explicitely use the empty keyword and not an empty pair of quotes. Introduced in https://ci.appveyor.com/project/Seddryck/nbi/build/1.18.0-RC.1.build.318
