### ISSUE TITLE
Genbi is slower than in previous versions

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#347]
Reported by @WimDeRons

I have compared the execution times of all versions of GenBI that I have on my laptop, and this shows that the big difference in terms of execution time was introduced in 1.15.0.1.
 
Current performance numbers:
-	Execution time:                +- 90 seconds
-	CPU usage:                        +- 40% peak
-	RAM usage:                       +- 600MB peak
 
Previously:
-	Execution time:                +- 2 seconds
-	CPU usage:                        +- 20% peak
-	RAM usage:                       +- 30MB peak

**Comment by Seddryck** [comment]
The issue is in the ```suite generate``` and was introduced by the code to handle CDATA for queries. This feature needed to add an XmlAttributeOverrider to the serializer and the creation of the serializer is really expensive. I improved the performances by avoiding to create a serializer for each test.

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.18.0-beta.88.build.324/artifacts

**Comment by WimDeRons** [comment]
Using the 1.18.0 beta version, the execution time is now +-3 seconds.

Thank you!
