### ISSUE TITLE
Connection strings in config files

### ISSUE THREAD

**Issue by avipmathur** [Seddryck/NBi#354]
A Connection string in  config files error.
the error is as below
------------------------------------------------
_NBi.NUnit.Runtime.TestSuite.My second test:
System.AggregateException : One or more errors occurred.
  ----> System.InvalidOperationException : The ConnectionString property has not been initialized._

----the code is as below---
```xml
<settings>
  <default apply-to="system-under-test">
    <connectionString>Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog='Test';Data Source=.</connectionString>
  </default>
</settings>
```
-------------------------------
Can't figure out why is it not working in the settings tag. Though the same string works in the query tag
```xml
<query connectionString="Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog='Test';Data Source=.">
    select * from [dbo].[Table_5]
</query>
```

**Comment by Seddryck** [comment]
Shouldn’t be an issue with your test definition. 

Could you place your full test (feel free to scratch queries) or at least tell me the system-under-test that you are using (execution or resultSet) and the assertion (equalTo, row-count, all-rows) ?

**Comment by Seddryck** [comment]
The version of NBi would also be great :-)

**Comment by avipmathur** [comment]
Solved the problem today.
it was missing code for assert
```  xml
<default apply-to="assert">
      <connectionString>Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog='Test';Data Source=.</connectionString>
</default>
```
