### ISSUE TITLE
MDX Hierarchy data pulled strangely - Question

### ISSUE THREAD

**Issue by dvadwh** [Seddryck/NBi#355]
Hi Seddryck,

I'm having weird results when testing cube data from my hierarchy Date.
Which contains following (in exact order):

[Date].[abc Year]
[Date].[abc Quarter]
[Date].[abc Period]
[Date].[abc Week]
[Date].[abc Date]

Basically if i want to test 1 level or hierarchy let’s say [abc Date] i use following query(where unique key is made by concatenation of member name and member ordinary number in custom column "x").

WITH MEMBER x AS
       CSTR([Date].[abc Hierarchy].currentmember.name) + ' ' + CSTR([Date].[abc Hierarchy].currentmember.LEVEL.ORDINAL)
      SELECT
        {x}
      ON COLUMNS,  
        {[Date].[abc Hierarchy].[abc Date]} 
      ON ROWS
      FROM [My Cube] 
 
After running above query in management studio I get result as expected:

`https://imgur.com/a/DDFlI`

But for some unknown reason when I start automatic test, NBi won’t take just these 2 columns, instead it takes whole the hierarchy from the highest member to the member i chose in MDX query(in this case [abc Date]):
So this example give me whole hierarchy. (Althought I wanted just lowest member of this hierarchy [Date].[abc Date])

`https://imgur.com/a/e1g3V`
 
Meaning for example if would choose I want to test [Date].[abc Quarter] it would show me 

[Date].[abc Year]
[Date].[abc Quarter]

 `https://imgur.com/a/zHJ1J`

Can you please advice what is reason behind this behaviour?

Thanks in advance,
George

**Comment by FuegoArtificial** [comment]
Hi George,

if I remember correctly, the query result is common behavior of Analysis Services (depending on the client tool represented differently) and is often helpful to return the ascending hierarchy-levels, too. I don't think it's NBi-dependent.
Now, depending on what you want to test, you might want to change the MDX-query, even though this might be a little tricky.
What would you like to test on the hierarchy level? Perhaps we can help here.

Cheers,
Tilo

**Comment by Seddryck** [comment]
Hi,

I confirm what Tilo said, the behaviour is not linked to NBi in fact SSMS is cheating and not returning the real result returned by adomd. If you explain where this behaviour is troubling your test we could probably help you.

**Comment by Seddryck** [comment]
If you need any additional help, tell us.
