### ISSUE TITLE
tolerance on different rows

### ISSUE THREAD

**Issue by johnwww** [Seddryck/NBi#356]
When asserting that 2 datasets are equal, I have a case where there can be some additional rows in one of the datasets with values very close to zero. I expected that setting a tolerance would correctly ignore these small differences but it seems that tolerance is only applied when rows are matched, and that new rows are always flagged as difference. Is there a solution for this issue? (note that sub/superset will not really work as I only want very small values to be ignored).

**Comment by Seddryck** [comment]
To solve your issue I'd go with a filter on the system-under-test. Filtering out all the rows with a value close to zero and then applying an equalTo constraint on the remaining rows. More info in the [syntax 2.0 page](http://www.nbi.io/docs/syntax-2-0/) and the [filter explanation](http://www.nbi.io/docs/resultset-rows-count-advanced/#filter)

```xml
<system-under-test>
   <resultSet>
        <query>...</query>
        <alter>
             <filter>
                 <predicate name="#1">
                        <more-than or-equal="true">1<more-than>
                 <predicate>
             </filter>
        </alter>
   </resultSet>
```

**Comment by johnwww** [comment]
Thanks, this helps. It does not seem possible to put a similar filter on the dataset used for the assert, correct? I solved it now by including the filter in the query, but it would have been cleaner to use a similar filter as outlined above.

In any case thanks for this great testing solution, really impressive how complete it is and how well it works!

**Comment by Seddryck** [comment]
Indeed, at the moment you can't apply a filter transformation to the result-set available in the assertion. I created https://github.com/Seddryck/NBi/issues/358 to take care of that but it won't be in the pipeline before May.
