### ISSUE TITLE
Configuration of Genbi

### ISSUE THREAD

**Issue by chifaanfar** [Seddryck/NBi#360]
Hey!!

i am in the process of creating a test-suite with genbi , and i would ask if i have to configure something else in genbi , apart the configuration doing in the begginig( creation of ".config" file, ".nbits" file and ".nunit" file.).
or just click on the Genbi .exe and working in the interface.
Because while i'am tring to do it , i found that all tests are generated  succesfully , even if i put a No existing dimension , but they told me that it exist in the perspective.

![genbi](https://user-images.githubusercontent.com/37936281/38144567-c2a6432e-3434-11e8-8f18-8e65f0ef1bd3.PNG)

thanks in advance for your answers

**Comment by Seddryck** [comment]
Genbi is creating tests based on inputs. Test generation is independent of test execution.  Genbi doesn’t execute these tests (for that you must use NUnit console or GUI). If you execute the tests generated by Genbi, your last one will fail.

**Comment by chifaanfar** [comment]
Thank you Seddryck a lot for your return , it's more clearer now , so after running this test cases in NUnit , i received this error , can you please give me the source of this probleme , because i spent a lot of time to analyse it , thank you again

"NBi.NUnit.Runtime.TestSuite.A dimension named 'Calling Format' exists in perspective 'WII_ORIGIN'.:
System.ArgumentOutOfRangeException : L'argument spécifié n'était pas dans les limites de la plage des valeurs valides.
Nom du paramètre : The value 'Dimensions' is not supported when instantiating with 'RelationalStructureDiscoveryFactory'."

**Comment by Seddryck** [comment]
Can you post the test and especially the connection string.

**Comment by chifaanfar** [comment]
![page1](https://user-images.githubusercontent.com/37936281/38238938-f47ff226-371a-11e8-997d-565a72821d5f.png)
![page2](https://user-images.githubusercontent.com/37936281/38238948-fa67d38e-371a-11e8-8696-c9be69a7e7a2.png)

as you can see , in the element settings , i can't found the description of the connection string declared in Genbi

**Comment by Seddryck** [comment]
I see, this is a known issue in the UI of genbi. When you write a connection-string into the upper-right ("settings") block, be sure to switch to another member of the dropdown (expl: "Default-Assert") or it could be not considered when you click on save. If you do this, you should have the value correctly set in your nbits file and it should stop to throw the exception about not a valid choice (By the way I should improve this error message when obviously the kind of database structure was not detected due to missing connection-string).

- [x] Genbi: Fix the bug with connection-string set in UI but not updated in model
- [ ] nbi: Improve error handling with structure and no connection-string set.

**Comment by chifaanfar** [comment]
it's OK now , i can see the connection string in my nbits file , thank you seddryck , the last think i would ask you for , and sorry if i exaggerated , i just wanna know if i have the opportunitie to run just one test suite , because i have to modify the path in the config file , for each new test suite , and to delete the previous nbit file on my test folder and leave just the new one .

**Comment by Seddryck** [comment]
No problem to answer questions, you're welcome  ... but I don't understand this one :-)

What do you mean by "run just one test suite"? AFAIK, it's not possible to run two test-suites in one run (limitation of NUnit).

To be short, the relation between the differents files is "project file" referencing "config file" referencing "test-suite". If you just want to update your test-suite, you should just use the same name than the previous iteration.

IRL, the use-case is to have several config (one by environment) for a unique test-suite (with different connection-strings), not to share a same config file for several tests-suites.

**Comment by chifaanfar** [comment]
thank you Seddryck , your answers was very helpful to me , thank you a lot.

**Comment by Seddryck** [comment]
Could you confirm that you're using v1.17 and not v1.18-RC2 ?

**Comment by chifaanfar** [comment]
I am using v1.17

**Comment by Seddryck** [comment]
Ok. Thx. 

I (finally) fixed the known issue in the UI in the last beta binaries on appVeyor and a better error handling of empty connection strings was already included in previous build of v1.18. 

I should publish the final v1.18 before End of month.

**Comment by chifaanfar** [comment]
OK , thank you Seddryck , and i want to congratuled you on this great job , good luck .

**Comment by Seddryck** [comment]
If you want to thanks aGitHub project then starring it (in the tap banner of any project) is usually a really good and appreciated start :-)
