### ISSUE TITLE
GenbiL is not serializing the attribute 'caption' of the 'contain' assertion

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#369]
@chifaanfar 

Hey Seddryck !!
I try to check the existence of one member in a given level , so when i execute my test with my template , the member value to caption is blank , any help please.

![bug](https://user-images.githubusercontent.com/37936281/39697300-001754dc-51e0-11e8-8b27-111825cae81e.png)

**Comment by Seddryck** [comment]
This is indeed a bug but there is an easy work-around. Change your template to replace the ```caption``` attribute by an ```item``` member.

``` xml
<assert>
  <contain>
    <item>$Member$</item>
  </contain>
</assert>
```

**Comment by Seddryck** [comment]
I created a branch with a bugfix and the build is available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.18.0-alpha.1+133.build.390

The expected behaviour is that the ```caption``` attribute is automatically replaced by the canonical element ```item```.

**Comment by chifaanfar** [comment]
It works now , thank youu !!

**Comment by Seddryck** [comment]
beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.22.build.410/artifacts
