### ISSUE TITLE
verification the formula of calculation a measure 

### ISSUE THREAD

**Issue by chifaanfar** [Seddryck/NBi#370]
hey ! i want to test if a **mesureX** is equal to **mesureA / mesureB** , there is a way to test it using NBi ? 
i found this section in the NBi documentation : Expression and predicate  " http://www.nbi.io/docs/resultset-predicate/" but i don't know how to apply it in my case .

**Comment by Seddryck** [comment]
Indeed performing this kind of test isn’t intuitive and a better support is expected soon. 

You should define an expression « checkMeasureX » with ```measureA/measureB```

Then a second expression « equalX » with ```checkMeasureX=MeasureX```

Then finally a predicate ```true``` operating on ```equalX```. 

Is it clear? If not I’ll need more than my smartphone to give a complete example and it will wait until this weekend.

**Comment by FuegoArtificial** [comment]
If you have the possibility to query your database you can also apply a comparison between two query results. One returning the measure, one returning the explicit calculation of the measure.

**Comment by chifaanfar** [comment]
thank you @Seddryck  , but what should i put in the "system under test" , should i specify the mesures "SELECT {[$Measures$].[$MesureA$], [$Measures$].[$MesureB$], [$Measures$].[$MesureX$]}ON 0
FROM [MYCUBE]" or just write the connectionString ,

@FuegoArtificial thanks for your return , i want to create a template that generalize this kind of test , and that can be applicable to all my test of verification the formula of calculation , so using two query can not be  usefull in my point of view , but  if you have an exemple I will be very grateful :D

**Comment by Seddryck** [comment]
Yes, the system under test should be a query.

**Comment by chifaanfar** [comment]
![example](https://user-images.githubusercontent.com/37936281/39872359-418cdb8e-5457-11e8-9721-6e7567199e4c.PNG)

i tried to excecute this test but it doesn't work , so i  will wait until this weekend to give me an example as expected , thank you  again Seddryck

**Comment by chifaanfar** [comment]
i tried to excecute this test but it doesn't work , surely it's wrong ,  so i will wait until this weekend to give me an example as expected , thank you again Seddryck

**Comment by chifaanfar** [comment]
i tried to excecute this test but it doesn't work , surely it's wrong , so i will wait until this weekend to give me an example as expected , thank you again Seddryck
![example](https://user-images.githubusercontent.com/37936281/39873766-5e5d3a70-545b-11e8-8240-766f2c131228.PNG)

**Comment by FuegoArtificial** [comment]
For this specific kind of test I generalized the query as a whole. When creating the test I develop two queries one with the measure(s), another one with the calculation(s) as calculated members. These two queries I add to the template.
The next test takes two queries again. 
Furthermore the test name and categories are set as parameters, too.
For me and my colleagues that level of generalization is the sweet spot of simplicity/flexibility/maintainability to write such tests, also when it comes to slicing the data for testing semi additive-measures. However, it might be different for you, of course, especially if you want to avoid that testers have to write queries.
Perhaps, I have a slightly different approach, where I let testers not hassle with the XML at all and everything is set into the templates with meta data (queries, etc.) and test-generation with genbi.
With other kinds of tests like testing for the count of dimension members, templates are easier to generalize without using queries due to the powerful support of certain kinds of tests with nbi.
I might miss something here and am open for suggestions, too! :)

**Comment by Seddryck** [comment]
I published a blog about how to resolve this kind of case at https://seddryck.wordpress.com/2018/05/13/using-nbi-to-assert-calculations-based-on-measures/
I'll update it to cover the automation but will wait until Monday evening more than probably.

**Comment by chifaanfar** [comment]
Thank you Seddryck , it's very interessting , waiting for the automation part 

@FuegoArtificial i have the same approach , the goal of my project is to minimise the fact that testers have to write queries , and to set everything into the templates

**Comment by Seddryck** [comment]
I updated the post with the template, the genbiL script and some explanations about them. Note that due to unfair circonstances there is a bug in the serialization of expression in NBi and you should use the last beta: https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.9.build.396

**Comment by chifaanfar** [comment]
thanks you a lot Seddryck for your effort
i tried to execute my test with the last version V1.18 to avoid the bug in serialization , but  I came across an error of another type :( 
![p2](https://user-images.githubusercontent.com/37936281/40131398-6c30bf0a-5929-11e8-8bd0-7d9a84d28595.png)

i used the same Template and Macro defined in the blog 
![p1](https://user-images.githubusercontent.com/37936281/40131476-9ef0299e-5929-11e8-8344-09b4a891dbbc.png)
![p3](https://user-images.githubusercontent.com/37936281/40131491-a35194a0-5929-11e8-941d-6a96ab008bba.png)
![p4](https://user-images.githubusercontent.com/37936281/40131498-a71381d4-5929-11e8-8a10-44f36f7b4fd2.png)

**Comment by Seddryck** [comment]
I’m sorry but your screenshot clearly shows that your script is executed twice. Is it really a screenshot related to this script ... I doubt!

Could you post your files for the script, the template and test cases in place of screenshots?

**Comment by chifaanfar** [comment]
yes , of course 
**script** 
case scope 'First Set';
case load file 'D:\NBi-1.18.0.1\MyTestProject\CSV\calculations.csv';
case split column 'alias' with value ',';
case split column 'measure' with value ',';
setting reference 'ref-one' connectionString '@ORIGIN_DEV';
template load file 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbitt';
case cross 'First Set' with vector 'ref' values 'ref-one';
suite generate;
suite save 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbits';

**Template**

<test name="$trunc(alias); separator=" and "$ to calculate $last(alias)$">
    <system-under-test>
      <resultSet>
        <query>
          <![CDATA[
          select
          {
         $measure; separator=", 
"$
          } on 0,
          {
          [Calling Format].[Calling Format Description].members
          } on 1
          from
          [WII_ORIGIN]
          ]]>
        </query>
      </resultSet>
    </system-under-test>
    <assert>
      <all-rows>
        $alias:{ x | <alias column-index="$i$">$x$</alias>}$
        <expression name="calculate">
           Round($expression$, $round$) = Round($last(alias)$, $round$)
        </expression>
        <predicate operand="calculate" type="boolean">
          <true />
        </predicate>
      </all-rows>
    </assert>
  </test>

**TestCase**

alias;expression;measure;round
call,volume,Alloc;volume/call;[Measures].[Calls #] , [Measures].[Volume] , [Measures].[50 ALOC];2

**Comment by chifaanfar** [comment]
Yes of course 

**testcase**
alias;expression;measure;round
call,volume,Alloc;volume/call;[Measures].[Calls #] , [Measures].[Volume] , [Measures].[50 ALOC];2

**template**
<test name="$trunc(alias); separator=" and "$ to calculate $last(alias)$">
    <system-under-test>
      <resultSet>
        <query connectionString="@$ref$">
          <![CDATA[
          select
          {
         $measure; separator=", 
"$
          } on 0,
          {
          [Calling Format].[Calling Format Description].members
          } on 1
          from
          [WII_ORIGIN]
          ]]>
        </query>
      </resultSet>
    </system-under-test>
    <assert>
      <all-rows>
        $alias:{ x | <alias column-index="$i$">$x$</alias>}$
        <expression name="calculate">
           Round($expression$, $round$) = Round($last(alias)$, $round$)
        </expression>
        <predicate operand="calculate" type="boolean">
          <true />
        </predicate>
      </all-rows>
    </assert>
  </test>

**script**
case scope 'First Set';
case load file 'D:\NBi-1.18.0.1\MyTestProject\CSV\calculations.csv';
case split column 'alias' with value ',';
case split column 'measure' with value ',';
setting reference 'ref-one' connectionString '@ORIGIN_DEV';
template load file 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbitt';
case cross 'First Set' with vector 'ref' values 'ref-one';
suite generate;
suite save 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbits';

**Comment by chifaanfar** [comment]
yes of course 

**testcase**
alias;expression;measure;round
call,volume,Alloc;volume/call;[Measures].[Calls #] , [Measures].[Volume] , [Measures].[50 ALOC];2

**template**
![tt](https://user-images.githubusercontent.com/37936281/40135803-befe556a-5935-11e8-97da-9c652e34ea1a.PNG)

**script** 
case scope 'First Set';
case load file 'D:\NBi-1.18.0.1\MyTestProject\CSV\calculations.csv';
case split column 'alias' with value ',';
case split column 'measure' with value ',';
setting reference 'ref-one' connectionString '@ORIGIN_DEV';
template load file 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbitt';
case cross 'First Set' with vector 'ref' values 'ref-one';
suite generate;
suite save 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbits';

**Comment by Seddryck** [comment]
For your background, when you post a screenshot  and not the content of a file, you’re enforcing people who are trying to help you to rewrite the content of your file. It could be leading to differences but it’s also not consider as respectful of their own time. 

To publish code you need to enclose it between three back ticks. (Check the syntax supported by github). 

That said, you didn’t answer my question: your first screenshot displays the execution of the genbiL script and there I can see that you are loading twice the CSV file. It’s not the case in the script that you provided. Could you explain that? Did you test the exact script that you posted here?

**Comment by chifaanfar** [comment]
to answer in your question , i have run the macro two times , and i have test second  script that i posted here . 
i posted the screenshot because the code was innabel to be pasted , i will try again 

`case scope 'First Set';
case load file 'D:\NBi-1.18.0.1\MyTestProject\CSV\calculations.csv';
case split column 'alias' with value ',';
case split column 'measure' with value ',';
setting reference 'ref-one' connectionString '@ORIGIN_DEV';
template load file 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbitt';
case cross 'First Set' with vector 'ref' values 'ref-one';
suite generate;
suite save 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbits';`

**Comment by chifaanfar** [comment]
to answer in your question , i have run the macro two times , and i have test second  script that i posted here . 
i posted the screenshot because the code was innabel to be pasted , i will try again 

`to answer in your question , i have run the macro two times , and i have test second  script that i posted here . 
i posted the screenshot because the code was innabel to be pasted , i will try again 
i appreciate your help , and the time that you devote to answer on our questions , so i can't consider it as respectful of your own time 
i put below the codes:
`case scope 'First Set';
case load file 'D:\NBi-1.18.0.1\MyTestProject\CSV\calculations.csv';
case split column 'alias' with value ',';
case split column 'measure' with value ',';
setting reference 'ref-one' connectionString '@ORIGIN_DEV';
template load file 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbitt';
case cross 'First Set' with vector 'ref' values 'ref-one';
suite generate;
suite save 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbits';``

`<test name="$trunc(alias); separator=" and "$ to calculate $last(alias)$">
    <system-under-test>
      <resultSet>
        <query connectionString="@$ref$">
          <![CDATA[
          select
          {
         $measure; separator=", 
"$
          } on 0,
          {
          [Calling Format].[Calling Format Description].members
          } on 1
          from
          [WII_ORIGIN]
          ]]>
        </query>
      </resultSet>
    </system-under-test>
    <assert>
      <all-rows>
        $alias:{ x | <alias column-index="$i$">$x$</alias>}$
        <expression name="calculate">
           Round($expression$, $round$) = Round($last(alias)$, $round$)
        </expression>
        <predicate operand="calculate" type="boolean">
          <true />
        </predicate>
      </all-rows>
    </assert>
  </test>`

and there is my CSV
`alias;expression;measure;round
call,volume,Alloc;volume/call;[Measures].[Calls #] , [Measures].[Volume] , [Measures].[50 ALOC];2
`

**Comment by chifaanfar** [comment]
to answer in your question , i have run the macro two times , and i have test second script that i posted here .
i posted the screenshot because the code was innabel to be pasted , i will try again
 btw i  appreciate your help , and the time that you devote to answer on our questions , so i can't consider it as respectful of your own time 
i put below the codes:
`case scope 'First Set';
case load file 'D:\NBi-1.18.0.1\MyTestProject\CSV\calculations.csv';
case split column 'alias' with value ',';
case split column 'measure' with value ',';
setting reference 'ref-one' connectionString '@ORIGIN_DEV';
template load file 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbitt';
case cross 'First Set' with vector 'ref' values 'ref-one';
suite generate;
suite save 'D:\NBi-1.18.0.1\MyTestProject\calculation.nbits';`

`<test name="$trunc(alias); separator=" and "$ to calculate $last(alias)$">
    <system-under-test>
      <resultSet>
        <query connectionString="@$ref$">
          <![CDATA[
          select
          {
         $measure; separator=", 
"$
          } on 0,
          {
          [Calling Format].[Calling Format Description].members
          } on 1
          from
          [WII_ORIGIN]
          ]]>
        </query>
      </resultSet>
    </system-under-test>
    <assert>
      <all-rows>
        $alias:{ x | <alias column-index="$i$">$x$</alias>}$
        <expression name="calculate">
           Round($expression$, $round$) = Round($last(alias)$, $round$)
        </expression>
        <predicate operand="calculate" type="boolean">
          <true />
        </predicate>
      </all-rows>
    </assert>
  </test>`


and my CSV file
`alias;expression;measure;round
call,volume,Alloc;volume/call;[Measures].[Calls #] , [Measures].[Volume] , [Measures].[50 ALOC];2
`

**Comment by Seddryck** [comment]
I checked in details your code and your issue is related to the ```case cross```. I opened the bug #376 and I developed a fix.

There is also an easy work-around (and reason this bug was never detected), just move your ```cross``` before the first ```split```.
