### ISSUE TITLE
Starting Genbi from SSIS with quotes in path

### ISSUE THREAD

**Issue by ChNolden** [Seddryck/NBi#371]
Hey people,

I want to start Genbi out of a SSIS package. So far so good, but as soon as I want to start Genbi from an Execute Process Task AND the path has quotes in it, it doesn't work.

Does anyone of you have an idea how I can use quotes for the path of Genbi from an SSIS Package?

Thanks in advance,

ChNolden

**Comment by FuegoArtificial** [comment]
Hi :)
Is this a nbi-issue or a general how-to-call-cmd-in-SSIS-related issue?
Do you have an example of what you would like to do?

**Comment by ChNolden** [comment]
I think this is a specific NBI/Genbi Issue.

I want to call Genbi from a Execute Process Task in an SSIS Package.
As Argument I want to give the path of the genbi folder with quotes around it.
Something like

"/C start /WAIT "(quote #1)D:\NBI\Genbi\genbi.exe D:\NBI\GenbiScripts\.genbil -q"(quote #2)

**Comment by Seddryck** [comment]
Why do you think it’s related to NBi? Normally with SSIS and an Execute Task, you should put your arguments on the argument property.

**Comment by Seddryck** [comment]
@ChNolden Any feedback on this?
