### ISSUE TITLE
"But was" section is empty in a test result

### ISSUE THREAD

**Issue by ashalitkin** [Seddryck/NBi#378]
The "But was" section in test results is always empty if a test fails. 
I'm using Visual Stuidio 2017 and start NBI from it. I've tried to read data by mean of MDX (Miscrosoft Analysis services 13.0.x) and from CSV. In both cases the "But was" section doesn't show anything.
I'm testing single row.
![image](https://user-images.githubusercontent.com/3977931/40606305-a191cef8-626d-11e8-901b-226051bcbe06.png)

**Comment by ashalitkin** [comment]
Actually if I copy the content of this test result text area and past into a file I can see all the info so looks like it's a UI bug

**Comment by Seddryck** [comment]
This is related to NUnit GUI 2.x and I can’t fix it on NBi side. I’m following the progress of NUnit 3.x on the UI part and hope the same issue won’t be there.
