### ISSUE TITLE
Setting default connection strings for system-under-test and assert in test suite using C#. 

### ISSUE THREAD

**Issue by JurgenVonP** [Seddryck/NBi#379]
Hi Cedric,

first of all thank you for the great work you did. I'm working on test automation of OLAP cubes in my current project. I've been able to do it writing some simple C# code, espacially thanks to [this conversation](HTTPS://github.com/Seddryck/NBi/issues/184). The last issue I have is how to modify/set test suites settings such as default connection strings for system-under-test and assert. Each time I generate the test suite from the template I get this part empty.

Kind regards,
Michal

**Comment by Seddryck** [comment]
Not tested: You should use the class ```DefaultAction``` in the namespace ```NBi.genbiL.Action.Settings```. The second parameter of the constructor of this action should be set to the magic string (oups)« ConnectionString ». Naturally this action should be executed before you save the suite. If it doesn’t work tell me and I’ll check that in front of a computer. 

Note: could you explain why you decided to go with C# and not genbiL? Is there anything you’re doing with C# that is not available in genbiL?

Note: this API is not really supported. Not that I don’t want to answer but more that it’s not the way I would recommend to use genbiL

**Comment by Seddryck** [comment]
Any feedback on this? If my answer is resolving your case, could you close the issue?

**Comment by JurgenVonP** [comment]
Hi, sorry for the late reply. Yes it helped, I've been able to implemented it. The reason I want to use it like this is that I need to automate the tests and include them in our ETL process. Is there any other way to do it fully automatic, without any actions taken by the user?

**Comment by Seddryck** [comment]
You can execute your genbiL recipe with genbi.exe (it’s possible to start an exe from SSIS).

**Comment by Seddryck** [comment]
Anyway about setting connection strings in the test-suite ... IMHO, it’s not a best practice. Connection-strings should be defined in the ```.config``` file (or another file referenced in this file). 

If you use this feature, you’ll be able to define one test-suite and execute it in different environments without changing anything to the test-suite, just link it to the correct ```.config``` file
