### ISSUE TITLE
Genbil - case scope example

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#381]
Hi All,

I have tried to use the **case scope** command as per the documentation on the nbi.io.

I am not able to make it work as I do not know what name should I insert as the 'name of the test-cases'.

Below is the code/options I have tried (without any success):

```
//load to test sets:

case load file 'C:\test\csv\01_test.csv';

case load file 'C:\test\csv\01_test.csv';

//change the scope to the 01_test.csv: (I have tried the 3 options below, none of them working)

case scope '01_test';

case scope '01_test.csv';

case scope 'C:\test\csv\01_test.csv';

// save the result to new csv after using the case scope:

case save as 'C:\test\csv\03_test.csv';
```

Could you provide me with some working example please?

Thanks in advance!

**Comment by Seddryck** [comment]
Hi @fefeslon 

A bit of context: each genbiL sentence is just the equivalent of a command that you could be able to execute in the UI. When you write ```case load ...```, it's the equivalent of clicking on the button "open csv file ...". In the case of ```case scope ...```, just imagine that you've different tabs with different set of cases. Each time you're calling ```case scope ...```, you're clicking an a tab to select it. If this tab doesn't exist, you're creating it and selecting it. Next  ```case ... ``` actions will be executed on the selected tab.

If you don't use any ```case scope ...```, you're writing in a defaut scope with no name. So when you do ```case load file 'C:\test\csv\01_test.csv';``` in your *first* sentence, you're loading your csv file into a default (unnamed) scope.

The name of the scope is fully independent of the name of file used to load the cases into the scope.

When you'll use something such as ```suite generate```, the content of the selected scope will be used.

In your case I'd change my script to this:
```
//create a new scope named '01'
case scope '01';
//load to test sets:
case load file 'C:\test\csv\01_test.csv';

//create a new scope named '02'
case scope '02';
case load file 'C:\test\csv\02_test.csv';

//switch back to the first scope:
case scope '01';

//do many things on this scope '01'
case remove column ...;
case move column ...;

//switch to the second scope:
case scope '02';

//do many things on this scope '02'
case remove column ...;
case move column ...;

//switch back to the first scope:
case scope '01';

// That will save current content of the scope '01' into the file 03_test.csv
case save as 'C:\test\csv\03_test.csv';
```

Is it clear? If yes, feel free to close the question else tell me where it's not clear.

**Comment by fefeslon** [comment]
Ah ok, I got it now!

I just did not understand it (the point that the set has no name by default and you have to define it first) from the documentation on the page (but now with you explanation it is quite clear).

Thanks Cedric.
