### ISSUE TITLE
Ampersand Sign throws an error in Genbi

### ISSUE THREAD

**Issue by barth11** [Seddryck/NBi#382]
Hi, when generating test using Genbi, I loaded CSV and Custom template and the tests did not get generated because it threw this error: "There is an error in XML document (1,115)".
Using code below, when I generate the XML with the same CSV and template, it creates the XML with no problem.
Code below generates the XML file without an issue.
`case load file '.\Genbi\Out\UT-OlapObjectExistenceColumn.csv';`
`template load file '.\Genbi\TestTemplate-OlapObjectExistence.nbitt';`
`suite generate;`
`suite save '.\ETLTest\TestSuiteGenerated\UT-OlapObjectExistenceColumn.nbits';`

This issue occurs when there is "&" sign in CSV. When I exclude line with "&" it works seamlessly.

**Comment by Seddryck** [comment]
You’ll find the answer to your question in the documentation at http://www.nbi.io/automation/format-variable/ 

If it’s solving your case, close the issue, else could you specify what’s going wrong with this solution?

**Comment by barth11** [comment]
It has not worked for me.
`caption="$columnName; format="xml-encode"$"`
Attaching CSV and nbitt file.

[Ampersand issue.zip](https://github.com/Seddryck/NBi/files/2098425/Ampersand.issue.zip)

**Comment by Seddryck** [comment]
Columns ```testDesc``` and ```testName``` also have an ampersand, you should apply the renderer ```xml-encode``` to them. Your template should be:

```xml
<test name="$testSuite$ - $order$ - $testCase$ - $testName;format="xml-encode"$$if(testDataScenario)$ - $testDataScenario$$endif$$if(mask)$ - $mask$$endif$">
	<description>$testDesc;format="xml-encode"$</description>
	<edition author="$username$" created="$now$"/>
	$if(category)$<category>$category$</category>$endif$
	<system-under-test>
		<structure>
			$if (ObjectType)$<column connectionString="@$connectionString$" caption="$columnName; format="xml-encode"$" perspective="$perspective$" table="$tableName$"/>$endif$
		</structure>
	</system-under-test>
	<assert>
		<exists/>
	</assert>
</test>
```

**Comment by barth11** [comment]
Thank you. Columns`testDesc` and `testName` are generated from `columnName`. That's why I missed that.
