### ISSUE TITLE
Genbil - case cross using multiple columns

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#389]
Hey All,

Is it somehow possible to use the case cross to join on multiple columns?

If yes (then just ignore the part below), could you provide me with the correct syntax/example for this feature?

In case it is not, should it be implemented please?

Motivation:
Sometimes I have csv/sql templates where the key is the combination of more columns.
In case i would like to inner join these to compare only the comparable values I would like to case cross them easily on multiple columns.

Of course it is possible to make some workarounds right now, I just think this should be quicker and more simple solution.

Cheers.

**Comment by Seddryck** [comment]
It’s not supported at the moment but I could add that to the next release.

**Comment by Seddryck** [comment]
I just published a new version of genbi at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.37.build.426 … tell me if something is wrong.

Just define more than column by separating them by a coma.

**Comment by fefeslon** [comment]
Looks like it works perfectly.

Thanks Cédric!
