### ISSUE TITLE
structure case is blank

### ISSUE THREAD

**Issue by chifaanfar** [Seddryck/NBi#391]
I try to generate nbit file , i used a template about verification of a stucture of a table, but the structure part is blank, as you can see below 
![cap2](https://user-images.githubusercontent.com/37936281/42515043-5b07e28e-844a-11e8-8165-627eb0473fff.png)
the nbit file generated : 
![cap1](https://user-images.githubusercontent.com/37936281/42515231-cef677dc-844a-11e8-8203-04b8baa8e18b.png)

thanks in advance for your help

**Comment by Seddryck** [comment]
```Column``` should be ```column```. All xml elements and attributes are starting by a lower case letter.

**Comment by chifaanfar** [comment]
it's work perfectly, thank you Seddryck
