### ISSUE TITLE
Genbil - column index propagated into the transformation element

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#392]
Hi All,

When I generate the test suite using the .nbitx template with **transformation** element used the generation process adds **column index** element into it as well (see below):

nbitx template:
```
<assert>
    <equalTo>
      <column index="0" role="key" type="numeric" />
      <column index="1" role="value" type="numeric">
        <transformation language="native" >
          null-to-value
        </transformation>
      </column>
```

generated nbits file (with column-index="0" added into the transformation element):
```
<assert>
      <equalTo>
        <column index="0" role="key" type="numeric" />
        <column index="1" role="value" type="numeric">
          <transformation column-index="0" language="native">
          null-to-value
        </transformation>
        </column>
```

Could you fix it please?

Cheers.

**Comment by Seddryck** [comment]
I published an alpha version a few hours ago at https://ci.appveyor.com/project/Seddryck/nbi/build/artifacts

If you confirm it's OK, I'll merge to the develop line, create a beta, integrate it in next RC and release.

**Comment by fefeslon** [comment]
Hey Cedric,

The column index = 0 error has been fixed, however the new block of code has appeared (InternalTransformationInner tag) in the generated nbits file.

**Error message in nunit:**
The element 'column' in namespace 'http://NBi/TestSuite' has invalid child element 'InternalTransformationInner' in namespace 'http://NBi/TestSuite'.


**Nbitt template (I have tried both the transform and the transformation tags):**
```xml
    <equalTo>
      <column index="0" role="key" type="numeric"/>
      <column index="1" role="value" type="numeric">
        <transform language="native" >
          null-to-value
        </transform>
      </column>
      <column index="2" role="value" type="numeric">
        <transformation language="native" >
          null-to-value
        </transformation>        
      </column>
```

**Nbits result:**
```xml
      <equalTo>
        <column index="0" role="key" type="numeric" />
        <column index="1" role="value" type="numeric">
          <transform language="native">
          null-to-value
        </transform>
          <InternalTransformationInner language="native">
          null-to-value
        </InternalTransformationInner>
        </column>
        <column index="2" role="value" type="numeric">
          <transform language="native">
          null-to-value
        </transform>
          <InternalTransformationInner language="native">
          null-to-value
        </InternalTransformationInner>
        </column>
```

**Comment by Seddryck** [comment]
Argggh, fixed at https://ci.appveyor.com/project/Seddryck/nbi/build/1.18.0-alpha.1+166.build.431/artifacts

**Comment by fefeslon** [comment]
Yep, now it looks ok!

Thanks for the fix.

**Comment by Seddryck** [comment]
Thx for the feedback! Merged to the development branch and beta released at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.42.build.433/artifacts or ```Update-Package NBi.Framework -Version 1.19.0-beta0042```
