### ISSUE TITLE
Genbil - transform element does not exist

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#393]
Hi All,

I have tried to use the Transform element (language="native") as per the documentation on the nbi webpage, but got the error message,

Code:
```xml
<transform language="native" source-type='text'>
   null-to-value
</transform>
```
Error Message:
```
'http://NBi/TestSuite' has invalid child element **'transform'** in namespace 'http://NBi/TestSuite'. 
List of possible elements expected: **'transformation'** in namespace 'http://NBi/TestSuite'.
```

The transformation element does work however I got another error message regarding **source-type=** not declared.

Code:
```xml
<transformation language="native" source-type='text'>
      null-to-value
</transformation>
```
Error Message:
```The 'source-type' attribute is not declared.```

Using the transformation element and removing the source-type it is possible to make it work.

Could you check/update the documentation please so it is clear how does it work?

Cheers.

**Comment by Seddryck** [comment]
Thx for pointing this discrepancy in the documentation. I’ll check that after this week-end.

**Comment by Seddryck** [comment]
Inside the ```column``` element, apparently the code is expecting ```transformation``` and ```original-type```. I'll switch to ```transform``` to be sync with the alterations. For ```original-type```, I'll check what's inline with the wording of the xsd. Naturally, I'll try to support during a few releases the existing notation if I need to change it during this review.

**Comment by Seddryck** [comment]
Fixed doc incorrect *source-type* replaced by *original-type*. *transform* should be standard way to define these transformations and is accepted by the next version, won't fix it in documentation.
