### ISSUE TITLE
Basic overview of querying cubes to compare to database result sets

### ISSUE THREAD

**Issue by zakwillis** [Seddryck/NBi#397]
Hi Seddryck, I am attempting to reconcile cube datasets to sql datasets. I am pretty familiar with NBI, and strong on SQL/MDX. 

**I have supplied sample queries but my feeling is, the rows dimension is mucking up the query. I can't find any examples to show how this should work simply.**

I have played around with specifying the column indexes, having no column indexes, using member.measures, etc etc and I always get this error - it is obvious what it means but not so obvious as to how to construct the MDX or correctly specify comparisons between cube and sql datasets..

NBi.NUnit.Runtime.TestSuite.BSP-694_MonthlyHoursTotalBetweenCubeDatabase:
NBi.NUnit.Runtime.CustomStackTraceErrorException : The column with index '[Business Date].[Year - Month - Day Date].[Month].[MEMBER_CAPTION]' is expecting a numeric value but the first row of your result set contains a value 'January 1900' not recognized as a valid numeric value or a valid interval.

SAMPLE QUERIES (Ignore the horrendousness of the code).

ACTUAL
```
select
          convert(varchar(20),
                    DATENAME(m, CONVERT(date, CONVERT(varchar(12),DateKey)))
                    + ' ' +
                    DATENAME(YYYY, CONVERT(date, CONVERT(varchar(12),DateKey)))
          ) BusinessDate
          ,SUM(Value) [Hours - Productive Work]
from
          etl.sometable
where 
          CountryCode = 'SOMEWHERE'
group by 
          convert(varchar(20),
                    DATENAME(m, CONVERT(date, CONVERT(varchar(12),DateKey)))
                    + ' ' +
                    DATENAME(YYYY, CONVERT(date, CONVERT(varchar(12),DateKey)))
          )
```
ASSERT 
```
select 
          (
                    DATENAME(m, CONVERT(date, CONVERT(varchar(12),DateKey)))
                    + ' ' +  
                    DATENAME(YYYY, CONVERT(date, CONVERT(varchar(12),DateKey)))
          ) BusinessDate 
          ,SUM(Value) [Hours - Productive Work]
from 
          etl.RawProductiveManagerHours
where 
          CountryCode = 'SOMEWHERE'
group by
          DATENAME(m, CONVERT(date, CONVERT(varchar(12),DateKey)))
          + ' ' +  
          DATENAME(YYYY, CONVERT(date, CONVERT(varchar(12),DateKey)))
```

**Comment by Seddryck** [comment]
Hello, I'm not sure that I fully understand your question because you've provided two SQL queries and you error message is clearly linked to a MDX query.

Anyway, based on your error message I'm guessing that the issue is related to the hierarchy ```[Business Date].[Year - Month - Day Date]```. This is the same issue that some users were facing in #224 and #355 Based on the name, I'm guessing that you've a real hierarchy with levels *Year* (2010, 2011 ….), *Month* (January 2010, February 2010, …, January 2011 ...) and *Date* (2010-01-01, 2010-01-02 ...).

Your MDX query is probably written with ```[Business Date].[Year - Month - Day Date].[Date].members on 1``` and you're expecting that this specific part will return just the date … **wrong**. Adomd will return three columns: year, month and date (2010;January 2010;2010-01-01 for first row). 

There is no built-in mechanism to avoid this behaviour but putting the columns in ignore is usually the trick that i used to overcome this kind of situation.

**Comment by zakwillis** [comment]
Hi Cedric, thanks for replying.

Yes, the error is linked to the MDX query and it appears obvious there are more columns coming from the MDX query than the SQL Query.

I assumed it was because MDX/ADOMD was returning more columns than what was specified within my query and had been looking into the query properties to overcome it. Would you be able to supply the specific instruction to ignore, or even better a pseudo example. The website is pretty comprehensive but there are some gaps in strategies for tackling certain tasks.

Keep up the good work,

Zak
________________________________

**Comment by Seddryck** [comment]
I usually try to limit myself to facts and features concerning the documentation on the website. A minimum of personal opinion on how you should use the framework. When it's more about strategy or tricks, I use my own blog. Anyway, this trick wasn't explained there either.

I added a blog about ignoring unexpected columns in MDX queries: https://seddryck.wordpress.com/2018/07/31/using-nbi-with-hierarchys-level-in-mdx-queries/

As a side note, it's surely not the only way to overcome this issue but probably the most intuitive. I'm working on a set of new features to remove/hold some columns in a result-set (#385, #386 and #387) … these features will also be useful to overcome this ADOMD behaviour.

**Comment by zakwillis** [comment]
Thanks seddryck, didn't know you had a blog. Am on holiday now so will take a look when I get back.
