### ISSUE TITLE
Genbil - template from a query

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#398]
Hi All,

Should it be somehow possible to use the connection string from nbi settings file when using the source from query in Genbil (In case it is possible could you provide me with example or link)?

The motivation is that usually both use the same connection anyway and it could be much more clearer to read, easier to maintain and bulletproof to mix different connections during the testing.

Cheers.

**Comment by Seddryck** [comment]
At this moment, it’s not possible to use any parameter in the genbiL script and especially using external reference file.

**Comment by fefeslon** [comment]
Ok, thanks for answer.
