### ISSUE TITLE
Facilitate the embeding of NBi into an application or service

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#404]
It should be possible to embed NBi into an application and start the execution of a few tests then retrieve the results and send them back to the application.

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.62.build.455

**Comment by raghavenderm** [comment]
Do we have the sample code on how to use this feature. Excited to see and use this feature.

**Comment by Seddryck** [comment]
The code infrastructure to achieve this is available in NBi for free. The code calling this infrastructure (mostly NUnit incantations) is not. Not on the roadmap to share this code, sorry.
