### ISSUE TITLE
Read environment variables in config/test suite

### ISSUE THREAD

**Issue by Tannenwedel** [Seddryck/NBi#410]
Hi,

Is there a way to read environment/system variables in either the config or test suite? I'd like to run NBi unit tests on a CI server such as Bamboo and set certain values as environment variables.

Thanks!

**Comment by Seddryck** [comment]
It’s not supported as-is but you could achieve it with a script in a variable. Anyway, I’ll add this as a feature. Thx for the good idea.

**Comment by Tannenwedel** [comment]
Thanks for the tip. Will it be possible to use those variables as part of a connection string? That way passwords wouldn't have to go in the file that holds the test suite.

**Comment by Seddryck** [comment]
I plan to support two ways to use environment variables:


```xml
<variable name="myVar"/>
  <environment name="MyEnvVar"/>
</variable>
```

and for connection-strings it will be supported in the defaults and reference (not with inline definition).

```xml
<default apply-to="sut"/>
  <connectionString>
    <environment name="MyEnvConnStr"/>
  </connectionString>
</default>
<reference name="xyz"/>
  <connectionString>
    <environment name="MyOtherEnvConnStr"/>
  </connectionString>
</reference>
```

Note that for the connection-strings the evaluation of the value of the environment variable is executed during the read/load of the test-suite and not during the execution!

**Comment by Seddryck** [comment]
Beta should be available at https://ci.appveyor.com/project/Seddryck/nbi/builds/19356719

**Comment by Tannenwedel** [comment]
This works fine for me, thanks!

**Comment by Tannenwedel** [comment]
Sorry for the late feedback,
Picking up environment variables when using the stand-alone NUnit tool works fine. However, when using the Nunit runner task within the Bamboo build server the bamboo-provided env vars are not being picked up and the connection strings are empty.

**Comment by Seddryck** [comment]
That’s probably because the environment variables are not accessible to the account running the build. I’d recommend to ensure that the environment variables are in the user-scope.

**Comment by fmms** [comment]
@Seddryck could you give an explaination why NBi is looking at the `user` rather than `process` scope of a variable?

I think the code reason for my issue is: https://github.com/Seddryck/NBi/blob/90e0a283fbac3b69ce37551e3788bad25a2c8042/NBi.Core/Scalar/Resolver/EnvironmentScalarResolver.cs

I was expecting to just set an environment variable before executing nbi on my build agent. However, nbi does not read environment variables but only user defined environment settings.

**Comment by Seddryck** [comment]
I probably didn't make the choice between user and process but between user and machine. But you're right that process souns to be a better choice. You can submit a PR if you want.

**Comment by fmms** [comment]
I have opened ticket #717 and PR #718 for this however I have not been able to proof backward compatibility in the test suite… I suspect you might be able to see the mistake…
