### ISSUE TITLE
Release 1.19-RC1 Framework.zip invalid

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#428]
Hi All,

I have tried to download the latest release and update the NBi.

I was able to download the Framework.zip, but it looks like the zip is damaged (I am unable to open it).

Could you check it please?

Thanks.

**Comment by Seddryck** [comment]
The [pre-release on github](http://github.com/seddryck/nbi/releases) has been re-packaged. AppVeyor and Nuget were OK.
