### ISSUE TITLE
Nbi/NUnit running into hash collisions by tests on DataVirtuality 

### ISSUE THREAD

**Issue by pablo437** [Seddryck/NBi#429]
Hi all,
our infrastructure consists of the SQL Server, where the source applications with the original data are located, and of the DataVirtuality Platform, where we provide views, which are pointing on the data from the SQL Server. 

Most of the views are materialized, thus we can run regression tests against those materializations and compare if the result sets are equal.

We use the NBI/NUNIT Test Suit for testing, but we experience strange and hardly diagnosable errors, like the following:

```
NBi.NUnit.Runtime.TestSuite.Referential Integrity Regression Test - SECURITY:
NBi.NUnit.Runtime.CustomStackTraceErrorException : The expected data set has some duplicated keys. Check your keys definition or the result set defined in your assertion. The duplicated hashcode is -1444580570.
Row to insert:<AMS:Security:2375802>.
Row already inserted:<AMS:Security:2375802>.
```

```
NBi.NUnit.Runtime.TestSuite.Referential Integrity Regression Test - SECURITY:
NBi.NUnit.Runtime.CustomStackTraceErrorException : The expected data set has some duplicated keys. Check your keys definition or the result set defined in your assertion. The duplicated hashcode is -145034326.
Row to insert:<AMS:Security:1804790>.
Row already inserted:<AMS:Security:1804790>.
```

The error message suggests that there are duplicates in the result set of the given query, which cause the hash collisions. We carefully ruled out, that there were duplicates in the data. We also run the tests against the original data on the SQL Server and experienced no hash collisions there. Therefore we are pretty sure, that our test data is free from duplicates and the errors must be caused by something else, most probably related to the DataVirtuality Platform itself.  

The following post https://github.com/Seddryck/NBi/issues/186  from year 2016 seems to describe quite similar situation and we would like to know, how this issue was solved and if there are any known bugs concerning this type of situation.

We are using NBi_1.18 NUnit Version: 2.6.4.14350  and Net3.5

Best Regards
Pablo

**Comment by Seddryck** [comment]
Hi Pablo,

Thx for the detailed explanation.

As explained in #186, long time ago, there was an issue with false positives due to a poor implementation of the hashing algorithm **but this bug as been fixed since years** (and the probability was really really low: you needed to compare millions/billions of records to have a (bad) chance to get this bug). At this moment, there is no evidence of a bug when comparing two datasets.

Based on your logs, I'm quiet confident that this is not a bug in NBi but a bug of the DataVirtuality Platform. Most of the time, complex (to investigate) duplicated rows are due to CHAR/VARCHAR/ANSI settings skipping or adding trailing spaces (it was the case in #186). If it helps you can also run a test for ```unique-rows```, you will perhaps find additional details that could help you!

**Comment by pablo437** [comment]
Hi Seddryck,

Many Thanks for your prompt response. I did one additional test. I accessed data on DataVirtuality with Excel, and the data was correct and without duplicates. This test is meaningful, because Excel uses the same driver as NBi by connecting to DataVirtuality.  Consequently if data uploaded to Excel is correct, then by using the same driver also the data uploaded to NBi should be correct. IN order to find out the root cause of the error we have to see the result (the data set) of the query which is buffered in NBi before the hashes are calculated. 
1.  Is there any possibility to have a look at this intermediate set ? 
2.  In which particular piece of code does it happend, this calculating of hashes ?

Rgds
P.

**Comment by Seddryck** [comment]
Hi Pablo, 

Thx for your message. I’m still really sceptical that NBi is having some troubles with the hashes. The main reason is in your own error message that you posted above. It clearly states that when calculating the hash of a row, NBi has found with the same hash ... and it appears that the keys are exactly the same. 

Now to get back to your last questions, I’d recommend to use a test “unique-rows”. It will fail and will display the rows that are not unique but also the actual-set. You can play with the profile failure report as explain at http://www.nbi.io/docs/config-profile-failure-report/ to get the full report. 

The effective code to calculate the hash is in NBi.Core.ResultSet.DataRowKeysComparer 

C.

**Comment by Seddryck** [comment]
@pablo437 could you provide some feedback on this issue? What was the root cause?

**Comment by pablo437** [comment]
Hallo Cedrick,

please apologise a long delay, I was first on holidays and then sick for a while, but anyway we received the definite answer regarding the problem last week. The problem (Hash collisions because of duplicates) is caused not by NBi, but trough a buggy implementation of the ODBC drivers (by handling of parallel queries) in DataVirtuality, the vendor will deliver a patch for this bug. So the NBi is absolutely OK and not the cause for the problem. Once more sorry for delay and Many Thanks for your valuable and soon answers.

Best Regard
Pablo

**Comment by Seddryck** [comment]
Thx for the feedback, really appreciated. (Now ... will sell my testing skills to DataVirtuality :-) )
