### ISSUE TITLE
Debugging tests in external files (DTD Processing)

### ISSUE THREAD

**Issue by SmallTomas** [Seddryck/NBi#430]
Hi Cédric,
we currently work on a testing architecture which is based on the DTD Processing feature, specifically on the possibility of referencing to tests in external files. 

The issue we face now is that when a test suite consists of more external tests and there is some syntax error in one of them, the information about the position of the error shows the line number of the external file, without any information which file it is. Therefore finding the error is quite difficult.

So I would like to ask if there is some better way to find the location of the error other than checking the reported line for each external file? If not, would it be possible to somehow improve the error reporting?
Thank you for your time.

P.S. Below I uploaded picture with the error warning. It is a test suite consisting of 7 tests in 7 external files. I made syntax error in the 7th test. The warning shows the error is at line 17, which is the location of the error in the .xml file of the external file.

<img width="663" alt="external file error" src="https://user-images.githubusercontent.com/42866145/50097694-b7595100-021a-11e9-9ea9-83312b2a7ea9.PNG">

**Comment by Seddryck** [comment]
Hi  @SmallTomas,

I took a few minutes to investigate but didn't find any solution for this in the .NET framework. It will be low on my priorities and I don't think I'll work on this. But feel free to investigate deeper and ask questions if you need (The code to handle that is in NBi.Xml.XmlManager).

As a side note, why don't you use genbiL to include external tests into the main test-suite? Which scenario is covered by DTD but not by genbiL?

**Comment by SmallTomas** [comment]
Thank you for the response. Actually, we experimented with other ways than genbiL trying to keep the testing framework as simple as possible.
