### ISSUE TITLE
Bootstrapper for Visual Studio without NuGet?

### ISSUE THREAD

**Issue by win32nipuh** [Seddryck/NBi#438]
I'd like to add some changes to NBi framework and test the changed library with my testsuite app.
Is it possible to create my TestSuite app without NuGet package but with local built NBi framework?
How to make this kind of TestSuite solution? 
#

**Comment by Seddryck** [comment]
What kind of change do you want to implement in NBi? It's probably safer to explain and discuss them before implementing them! I'd be able to guide you in the darkness code of NBi.

Anyway, yes it's possible to not use the nuget bootstrapper, just take a look to [Test environment's setup](http://www.nbi.io/docs/installation-environment/) ... but this is surely not the best way to tests change into the libraries, you can run tests (including acceptance tests) during the build and not after the build.

**Comment by win32nipuh** [comment]
I want to add some additional logging for the cases like duplicate keys error etc. 
Now it is my internal changes.
I trust you that hash collisions are not possible but anyway I receive this kind of errors and do not understand why. I'd like to investigate. I had ideas probably there are duplicated records from the odbc connection but I have created the c# app and exported the result set to text file and all records are unique.

**Comment by Seddryck** [comment]
In the output, you already have the two rows that are sharing the same key. If you want more details about all the rows that have this issue, you should take a look to the test ```unique-row```.

**Comment by win32nipuh** [comment]
Thank you for the useful information.
