### ISSUE TITLE
how to setup connectionstring for Oracle DB in NBi

### ISSUE THREAD

**Issue by pablo437** [Seddryck/NBi#445]
Hello Cedrik,

I hope you enjoyed Christmas Time and all the best for you in the 2019, let me ask you sth. probably very easy for you. Could you please verify why this connectionstrings for Oracle DB cause the error ? 
Could you post any samples ?

```

NBi.NUnit.Runtime.TestSuite.7_SMALL  Referential Integrity Regression Test on DATA VIRTUALITY - TRANSACTION:
System.AggregateException : One or more errors occurred.
  ----> NBi.Core.ConnectionException : ERROR [HY000] [Oracle][ODBC][Ora]ORA-12560: TNS:protocol adapter error

ERROR [IM006] [Microsoft][ODBC Driver Manager] Driver's SQLSetConnectAttr failed
ERROR [HY000] [Oracle][ODBC][Ora]ORA-12560: TNS:protocol adapter error

The connection string used was 'Driver=Oracle in Ora12201_0x64;  Service Name=******;user=*********;Password=***********'

```
Best Regards

Pablo

**Comment by FuegoArtificial** [comment]
Hi Pablo,

I didn't check your issue in detail. Just some thoughts, which might help

- did you install the driver on the machine on which nbi is executed from? 
- did you check http://www.nbi.io/docs/connection-providers/?
- you can get the names to register a provider by building a connection in some tool and copy the relevant part from the connection string 

My registration of the oracle driver looks like that:

```xml
<providers>
   <add id="OraOLEDB.Oracle.1" invariant-name="System.Data.OleDb" />
</providers>
```
Does that help or are you already beyond this point?

Cheers!

**Comment by Seddryck** [comment]
Hi @pablo437 ,

You have many ways (OLEDB, ODBC ...) to connect to Oracle and the connection-strings are depending on the selected driver

Based on your connection-string, you're probably trying to setup an ODBC connection. Unfortunately I rarely used them, but I checked in some documentation written by @WimDeRons and found following useful information:

**Oracle in OraClient11g_home1:**
Depending on the installed driver version, this could also be a viable option. There are two ways to define the data source:
1. In configuration file “tnsnames.ora”: Add the following entry in the file:
	```AliasOfChoice=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=HostName)(PORT=PortNumber))(CONNECT_DATA=(SERVICE_NAME=ServiceName)))```
      Use the following connection string:	```Driver={Oracle in OraClient11g_home1};DBQ=AliasOfChoice;UID=xxxxx;PWD=yyyyy```
1. In the connection string itself: Use the following connection string: ```Driver={Oracle in OraClient11g_home1};DBQ=Hostname:PortNumber/ServiceName;UID=xxxxx;PWD=yyyyy```
Remarks: If both 32 and 64-bits versions are installed then two “tnsnames.ora” files are existing!

**Microsoft ODBC for Oracle:**

* 32-bit only.
* There are three ways to define the data source:

1. In configuration file “tnsnames.ora”:  Add the previously mentioned entry in the file and use the following connection string:
```Driver={Microsoft ODBC for Oracle};Server=AliasOfChoice;UID=xxxxx;PWD=yyyyy```
1. In the connection string itself (full): Use the following connection string: ```Driver={Microsoft ODBC for Oracle};Server=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=HostName)(PORT=PortNumber))(CONNECT_DATA=(SERVICE_NAME=ServiceName)));UID=xxxxx;PWD=yyyyy```
1. In the connection string itself (shorthand): Use the following connection string:
```Driver={Microsoft ODBC for Oracle};Server=HostName:PortNumber/ServiceName;UID=xxxxx;PWD=yyyyy```

My preference goes to **OLE DB (OraOLEDB.Oracle - 32- and 64-bits)** and we also have 3 ways to configure the connection-string.

1. In configuration file “tnsnames.ora”: Add the previously mentioned entry in the file and use the following connection string:```Provider=OraOLEDB.Oracle;Data Source=AliasOfChoice;User Id=xxxxx;Password=yyyyy```
1. In the connection string itself (full): Use the following connection string:
```Provider=OraOLEDB.Oracle;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=HostName)(PORT=PortNumber))(CONNECT_DATA=(SERVICE_NAME=ServiceName)));User Id=xxxxx;Password=yyyyy```
1. In the connection string itself (shorthand): Use the following connection string: ```Provider=OraOLEDB.Oracle;Data Source=HostName:PortNumber/ServiceName;User Id=xxxxx;Password=yyyyy```

Finally, a brief troubleshooting guide:

Encountered errors:
* ```ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified```
	Is the driver name correct?
	Is the driver 64-bit compatible?
* ```ERROR [HY000] [Oracle][ODBC][Ora]ORA-12560: TNS:protocol adapter error```
	Correct use of “DBQ” or “Server” or “Data Source” keyword?
* ```ERROR [08004] [Oracle][ODBC][Ora]ORA-12154: TNS:could not resolve the connect identifier specified```
	Is the used alias identical to the one defined in the configuration file?
	Is the alias entry missing in the configuration file?
* ```ERROR [HY000] [Oracle][ODBC][Ora]ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA```
	Is the service name correct?
	Is the service name missing?
* ```Arithmetic operation resulted in an overflow.```
	Bug in Oracle driver...
* ```Oracle client and networking components were not found. These components are supplied by Oracle Corporation and are part of the Oracle Version 7.3.3 or later client software installation.```
	Does the path environment variable contain an Oracle entry?


From the top of my head, the registration of the additional providers as mentioned by @FuegoArtificial  is not needed anymore for OLE DB (But I'm not 100% sure).

**Comment by Seddryck** [comment]
@Pablo437 Is it really too much to get a message to tell us if the provided answers are solving your case or not? 

I’m really fed up of to see people asking questions on open source projects receiving answers and not having the courtesy to give some feedback about the answers.

**Comment by pablo437** [comment]
Hi Cedric,
again apologise, you are absolutely right, I should answer much quicker  but we faced some other problems and I was also sick for a while. You find the sample of the connection string which was finally working in this case in the file:

[sample_connection_string_oracle.txt](https://github.com/Seddryck/NBi/files/2777054/sample_connection_string_oracle.txt)


Maybe it would be a good idea to list all the samples of working connecting strings for  the DB’s which are known that NBi can connect with them?  

Best Regards
Pablo

**Comment by Seddryck** [comment]
Thanks for your feedback, hope it will also help others looking for the same info.

Thanks also for your suggestion. I tried to make a few blog posts about to connect to MySQL, PostreSQL ... with NBi but never Oracle. The main issue with this blog posts is that this information is not directly related to NBi but to the drivers. Especially difficult when you've 36 distinct drivers (each having it's own syntax) for the same database such as with Oracle. Anyway, I'll add a link to this thread and to the blog posts in the main documentation.

**Comment by AustinRGovender** [comment]
> Thanks for your feedback, hope it will also help others looking for the same info.
> 
> Thanks also for your suggestion. I tried to make a few blog posts about to connect to MySQL, PostreSQL ... with NBi but never Oracle. The main issue with this blog posts is that this information is not directly related to NBi but to the drivers. Especially difficult when you've 36 distinct drivers (each having it's own syntax) for the same database such as with Oracle. Anyway, I'll add a link to this thread and to the blog posts in the main documentation.

Hey dude, could you link the blog posts please.

**Comment by Seddryck** [comment]
Hey dude, never had time to write the blog post but the content of this blog post is just a few lines above in my answers.
