### ISSUE TITLE
Hashes collision with huge result-sets

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#46]
**Jenni_P**:

Hi, 

I'm using NUnit / NBI in my project. 
But i have a important volumetry issue. 

I compare two queries, aroung 800 000 rows. 

But i have this message : 
______NBi.NUnit.Runtime.TestSuite.Compare CodeActe,count(*) on CubeDimActe+CubeDimActe2 : 
NBi.NUnit.Runtime.CustomStackTraceErrorException : The expected data set has some duplicated keys. Check your keys definition or the result set defined in your assertion.______ 

Using the query in my database, i have already checked the result. It's seem ok. No duplicated keys. 

Does a row number limitation exist ? How i can solve my issue and continue using this software ? 

Thank you, 
J.

**Comment by Seddryck** [comment]
Hello,

There is no limitation on the row count.

I'm quite sure that you've duplicated keys in your expected dataset (Assert). Are you sure that your key-fields are correctly configured?

If you think your configuration is correct, the best way to troubleshot this is to add a "top 1" in the query for the expectation (Assert). Then check if the header of your column is effectively what you've configured (KEY or VALUE or IGNORE). If it's the case, check again the content of your key columns, you'll find a duplicate.

**Comment by Seddryck** [comment]
**Jenni_P**

Thank you for the answer, 
But i didn't solve my problem. 

I'm doing this test : 

```
<test name="Compare Column1, count(*) on Table1+Table2">
<description></description>
<edition author="" created="2014-11-21T14:46:20" />
<system-under-test>
  <execution>
    <query name="MyBase" connectionString="MyConnection" >
            SELECT  Column1, count(*) FROM Table1
            GROUP BY Column1
</query>
  </execution>
</system-under-test>
<assert>
  <equalTo>
    <query name="MyBase" connectionString="MyConnection" >
            SELECT  Column1, count(*) FROM Table2
            GROUP BY Column1
</query>
  </equalTo>
</assert>
</test>
```

I compare two table with the same structure. And I want to know if data are the same.
Duplicate aren't possible because I use GROUP BY clause.

I don't understand key-fields configuration documentation. How can i complete my script to use `<column />` syntax ? 

Thank you

**Comment by Seddryck** [comment]
Have you any special requirement on your table2 (Special chars?). Are you sure your query has effectively only two columns?

About the configuration of your assertion equalTo, based on the expected resultSet, the configuration should be

```
<equalTo keys="first">
```

or

```
<equalTo keys="all-except-last">
```

... this last value (all-except-last) will be used if no other parameter is defined. As you've only two columns this is equivalent.

**Comment by Seddryck** [comment]
**Jenni_P**

Hello,

We have no special requirement (varchar(250) for the key column and the count(*)). The sql statement is composed of 2 columns (see the example). 

We tried your 2 configurations without success. The duplicated keys error happens each time we execute a statement on huge number of rows. We made hand test in Management Studio to check that there is no doublon returned by the statements. We got the error from 600 000 rows and the error didn't seems linked with the execution time. 

Have you any other suggestion ? 

Thanks

**Comment by Seddryck** [comment]
If I had to investigate this kind of issue, I'd add an "order by Column1" in my query (Assert) and then play wit a "top xxx". By dichotomy, I'd be able to identify the first row considered as a duplicate by NBi.

To fasten the comparison, NBi makes some usages of hashes, so there is a small probablity of conflict between the hashes, but I've never encoutered them. On Wednesday night (CET), I'll provide a nighly build with a more explicit message in case of duplications to help to understand what happen in this case.

**Comment by Seddryck** [comment]
I've built a new version that should clarify your problem. Could you download it and run your test, then just copy paste the full error message, it should contain information to debug this issue.

New version: https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.7.0.99064

**Comment by Seddryck** [comment]
Have you got any feedback when using the nightly build?

**Comment by Seddryck** [comment]
**Jenni_P**

Hello, 
Thank you for your answer. 
This days, I didn't had time to see that, sorry. 
But thank you, it'll be usefull.

**Comment by rvdpluijm** [comment]
Hi Cedric,

I have the same problem. See below my result and my nbits file

# Nbits file

``` xml
<?xml version="1.0" encoding="utf-8"?>
<testSuite name="Unit Testing" xmlns="http://NBi/TestSuite">
    <test name="Speedtest OAS_DOCUMENT">
        <system-under-test>
            <execution>
                <query connectionString="Server=brytta;Database=HR_DWH_FIN_DATT;User Id=PluRe;Password=hy@@rvv1">
                        <![CDATA[

                        SELECT fp.jaar, fp.periode, tt.transactietype, LTRIM(RTRIM(ftrans.documentnummer)) as docnummer, ftrans.documentregelnummer,
                         dtrans.omschrijving, dtrans.rwexterne_referentie1, sum(uren) as uur, sum(ftrans.transactiesbedrag) as bedrag
                         FROM
                          ((HR_DWH_FIN_DATT.DWH.fact_transactie ftrans INNER JOIN HR_DWH_FIN_DATT.DWH.dim_transactie dtrans ON (ftrans.transactie_id = dtrans.transactie_id)) 
                          INNER JOIN HR_DWH_FIN_DATT.DWH.dim_finperiode fp ON (fp.finperiode_id = ftrans.finperiode_id))
                          INNER JOIN HR_DWH_FIN_DATT.DWH.dim_transactietype tt ON (tt.transactietype_id = ftrans.transactietype_id)
                          INNER JOIN HR_DWH_FIN_DATT.DWH.dim_administratie adm ON (ftrans.administratie_id = adm.administratie_id)
                          WHERE adm.administratie = 'HR' and fp.jaar = 2015 and fp.periode between 1 and 5
                          GROUP BY fp.jaar, fp.periode, tt.transactietype, ftrans.documentnummer, ftrans.documentregelnummer, dtrans.omschrijving,
                          dtrans.rwexterne_referentie1
                          ORDER BY fp.jaar, fp.periode, tt.transactietype, ftrans.documentnummer, ftrans.documentregelnummer
                      ]]>
                </query>
            </execution>
        </system-under-test>
        <assert>
            <equalTo>
                <column index="0" role="key"/>
                <column index="1" role="key"/>
                <column index="2" role="key"/>
                <column index="3" role="key"/>
                <column index="4" role="key"/>
                <column index="5" role="ignore"/>
                <column index="6" role="ignore"/>
                <column index="7" role="value" type="numeric" tolerance="0.9"/>
                <column index="8" role="value" type="numeric" tolerance="0.01"/>
                <resultSet file="C:\Users\PluRe\UnitTesting\UnitTesting\Plat overzicht.csv"/>
            </equalTo>
        </assert>
    </test>
</testSuite>
```

# Result

```
NBi.NUnit.Runtime.TestSuite.Speedtest OAS_DOCUMENT:
NBi.NUnit.Runtime.CustomStackTraceErrorException : The expected data set has some duplicated keys. Check your keys definition or the result set defined in your assertion. The duplicated hashcode is -9031735459879438143.
Row to insert:<2015|3|MEMO|411500033|41|Hintshop trxtotaal 06/01/2015 corr|HRCAT282335||-316>.
Row already inserted:<2015|3|MEMO|411500032|91|Hintshop trxtotaal 01/12/2014|HRCAT281113||-80>.
```

As you can see, the five key columns I've chosen are different on key 4 and 5, but they still deliver the same hash.

**Comment by Seddryck** [comment]
Thx for the confirmation. Could you specify the version of NBi that you're currently using?

**Comment by rvdpluijm** [comment]
I'm on 1.11.0.99089 (the build from 2 days ago).

**Comment by Seddryck** [comment]
OK, I've taken a look to the code and checked the documentation of the .NET framework and indeed there is a good chance of collision. It's not a non-trivial task. I'll check this next week and try to provide a fix.

**Comment by Seddryck** [comment]
Dag @rvdpluijm ,

I think this build should solve your problem. It's really hard to reproduce, so your feedback is really welcome.

https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99090

**Comment by rvdpluijm** [comment]
Hi @Seddryck,

Thanks. I won't be able to test this during this week (I'm having a week off), but I'll make sure to test it the week thereafter.

**Comment by rvdpluijm** [comment]
Solved! Thank you!

**Comment by Seddryck** [comment]
Just to be clear, it's not part of release v1.11 but I've already compiled a beta for v1.12 including this feature and with all the features of v1.11.

**Comment by Seddryck** [comment]
https://github.com/Seddryck/NBi/releases/v1.12-beta

**Comment by Yingmin-Li** [comment]
We are facing the same problem, with a long dataset result of (11 columns) to compare with CSV, we got the same error message. And when we reduce the colulmn to last 3 columns, this error disappeared.

Can you please check it?

NBi 1.13.0-ci.92

**Comment by Seddryck** [comment]
This bug wasn't related to the count of columns but to the count of rows ... and the probability to face this bug was really low with datasets of less than a few thousand rows.

Could you post your test (configuration of key and values) and the exact error message that you've. But I could guess that the problem is in the definition of the keys and values ... check this [page of the documentation](http://www.nbi.io/docs/compare-configuration/)

**Comment by Yingmin-Li** [comment]
Yes, you are right. The problem is because of missing unique key. 

Thank you

**Comment by Yingmin-Li** [comment]
Hello, according to the document [Configuration for comparison](http://www.nbi.io/docs/compare-configuration/), it's obliged to have unique key column to compare two resultsets. 

With the latested version, is it possible to compare a table without unique key with a csv file?
If not, do you consider to add this feature?

Thank you in advance.

**Comment by Seddryck** [comment]
Indeed, it's mandatory yo have a unique key for compaison of result-sets.

There is no feature planned to support comparison of non-unique result-sets. But you can define the unique key on the whole set of fields to work-around this.

If you want to have support for comprison of non-unique result-sets, please open a new issue and describe the expected behaviour. How do we say that two rows are not equal or are equal? Detail your expectations and explain this samples ... you'll see that it's really tricky to have a functional design on this.
