### ISSUE TITLE
Comma separated file has comma in a column data, then it is giving the error

### ISSUE THREAD

**Issue by raghavenderm** [Seddryck/NBi#461]
Comma separated file has comma in a column data, then it is giving the error.

![image](https://user-images.githubusercontent.com/48467794/54524411-e6a56880-4997-11e9-9e08-ae947ebd33a1.png)

**Comment by raghavenderm** [comment]
Also observed that if a column has text qualifier then the test is failing. in my file column "Values"  has the text qualifier then data is reading as is that means with double quote.

![image](https://user-images.githubusercontent.com/48467794/54524667-924eb880-4998-11e9-92f4-83a2e86f29ae.png)

**Comment by Seddryck** [comment]
Have you checked http://www.nbi.io/docs/config-profile-csv/ ? What's your csv-profile and what's your version of NBi (and PocketCsvReader if NBi is v1.20)?

Specification of the text-qualifier should be supported in v1.20 (beta) and you should specify the ```text-qualifier``` to "DoubleQuote" in the ```csv-profile```.(Sounds to be undocumented)

**Comment by aniketh02** [comment]
Thank you @Seddryck . Issue is resolved with v1.20
