### ISSUE TITLE
AdomdClient version 15.15

### ISSUE THREAD

**Issue by Victor-Blaga** [Seddryck/NBi#462]
Hey @Seddryck 

I've recently updated some NuGet packages in my test project, and the AdomdClient got upgraded to version 15.15 as a result. I checked the dependencies of NBi Framework in my project, and it looks like stuff should work with Microsoft.AnalysisServices.AdomdClient.retail.amd64 >= 15.3.1. The Visual Studio project reference to the AdomdClient also says version 15.15.0.0, so I think this is OK.

However, when I run the tests in the NUnit test runner, I looks like it attempts to load the exact version 15.3.1.0 and then fails. Is there any other place with a hard reference to the exact 15.3.1 version, or am I missing something?

_**Later edit:** Reverting the Microsoft.AnalysisServices.AdomdClient.retail.amd64 package back to version 15.3.1 fixed it, the error has disappeared from NUnit. Still not clear why the newer version does not work._

![AdomdClient Reference Properties](https://user-images.githubusercontent.com/38884537/54686967-c7831400-4b1a-11e9-843b-a67fade688ac.PNG)

![AdomdClient Installed Version](https://user-images.githubusercontent.com/38884537/54686968-c7831400-4b1a-11e9-9503-c2e85ae24dbe.PNG)

![AdomdClient NUnit Fail](https://user-images.githubusercontent.com/38884537/54686969-c7831400-4b1a-11e9-93af-f5c1c0f61259.PNG)

![AdomdClient Project Reference](https://user-images.githubusercontent.com/38884537/54686970-c7831400-4b1a-11e9-8d04-61d8c098a183.PNG)

**Comment by Seddryck** [comment]
I guess you're using NBi.VisualStudio package ... clarification: the test "project" is not compiling anything just downloading the nuget packages, creating a few files and setting a few details to run NUnit on F5 ...

Over this point, I'm really not sure of my answer ... we reach the limit of my understanding of C#/.Net

The NBi dlls are compiled with the version 15.3.1 of adomd.dll. It means that at runtime they will try to find this specific version of adomd.net ... if it's not available it will fail. If you want that the NBi dlls to consider a newer version of adomd.net dll, you'll need to add a binding redirect in the config file.  The process is explained for the extensions at http://www.nbi.io/docs/extension-installation/ 

Absolutely no guarantee on this ... just sharing my experience with these issues when I developped the extensions.

**Comment by Victor-Blaga** [comment]
Thanks for the feedback, I'll leave the version at 15.3.1 then. I'll just keep in mind to not update this dependency, and if I manage to make it work using the process at the link you provided, I'll be sure to drop a comment.
