### ISSUE TITLE
Local-variable values  provided by custom code

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#487]
It should be possible to call a C# method returning a list of values that a local-variable should take.

```xml
<instance-settling>
  <local-variable name="myFile" type="text">
    <custom assembly-path="." type-name="VariableProvider">
       <parameter name="param1">@myVar</parameter>
       <parameter name="param2">10101011</parameter>
    </custom>
  <local-variable>
</instance-settling>
```

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/28639359/artifacts or `1.22.0-beta0017`

**Comment by lukzas** [comment]
@Seddryck According to docs I should implement `ISequenceResolver` interface, but I can't see it in `NBi.Extensibility` package. Interfaces for flat files or custom conditions are there though. Is package missing it indeed or I should approach it differently? (I guess it should be consistent with all the extensions?)

**Comment by lukzas** [comment]
I've been able to succeed with importing `NBi.Core.dll` into the Library project directly. Maybe that would help someone, but still feeling it should be consistent 😝 

```
using NBi.Core.Sequence.Resolver;
using System.Collections;
using System.Linq;

namespace CustomSequence
{
    public class CustomSequence : ISequenceResolver
    {
        private string Foo { get; }
        private string Bar { get; }

        public OlapSecurityPlanSlicer(string bar, string foo)
        {
            Bar = bar;
            Foo = foo;
        }

        public IList Execute()
          => new string[] { Bar, Foo }.ToList();

        object IResolver.Execute() => Execute();
    }
}
```
Usage
```
<local-variable name="myVar" type="text">
  <custom assembly-path="CustomSequence.dll" type="CustomSequence">
    <parameter name="bar">10</parameter>
    <parameter name="foo">1</parameter>
  </custom>
</local-variable>
</instance-settling>
```

**Comment by Seddryck** [comment]
That’s clearly a mistake it should be in the Extensibility package not in Core.
