### ISSUE TITLE
Genbil - Unable to generate test for a value containing & (ampersand)

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#497]
Hi All,

I am trying to generate tests using Genbil - using nbitt template and csv file.

I am using the 1.20 build (but it is the case in 1.19 as well).

If any of the values in the csv file contain '&' (ampersand) there is an error during the test generation (if the metrics with & are removed from the csv file, other tests cases are generated correctly).

![image](https://user-images.githubusercontent.com/25638272/60578752-0e231400-9d82-11e9-8438-be2dc469ab96.png)

Is this a bug or a feature?

Could you check it please?

Cheers,

Michal.

**Comment by Seddryck** [comment]
It's more a feature than a bug. Could you check this [part of the documentation](http://www.nbi.io/automation/format-variable/) or this [issue](https://github.com/Seddryck/NBi/issues/382)? Tell me if it doesn't solve your issue.

**Comment by fefeslon** [comment]
Ah ok, sorry for the duplicity.
I did not notice that.

Cheers.
