### ISSUE TITLE
Regex no longer working correctly with | (or) symbol

### ISSUE THREAD

**Issue by CoolsJoris** [Seddryck/NBi#511]
Hi,

Regex no longer works as expected.
As simple regex checking on a single character works, when you start using | to specify or it stops working. 

The following works (simple regex)
```xml
<assert>
  <all-rows>
    <predicate operand="[Column]" type="text">
      <matches-regex not="true">([ ]){17}</matches-regex>
    </predicate>
  </all-rows>
</assert>
```

The following doesn't work.

```xml
<assert>
  <all-rows>
    <predicate operand="[Column]" type="text">
      <matches-regex>([A-Z]| |\d|[+]|[-]|[%]|[*]){17}</matches-regex>
    </predicate>
  </all-rows>
</assert>
```
The error i get is the following:
NBi.NUnit.Runtime.TestSuite.TestName:
NBi.Core.Transformation.Transformer.Native.NotImplementedTransformationException : The native transformation named '' is not implemented in this version of NBi

I have this issue in the following version. (could have been even earlier)

- 1.21.0-beta.244
- 1.21.0-beta.286

thanks in advance.

**Comment by Seddryck** [comment]
This is a not-anticipated side effect of #494. The pipe symbol (```|```) is interpreted as a separator for the native transformations. 

I propose to add a feature that if the value is starting AND ending by a grave symbol (``` ` ```) then the value is a literal. That means that it's not fully retro-compatible, but the cases where a change would be required are minimal.

```xml
<matches-regex>`([A-Z]| |\d|[+]|[-]|[%]|[*]){17}`</matches-regex>
```

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/26970850/artifacts or ```1.21.0-beta0287```
