### ISSUE TITLE
Result-set file ignored using genbil (not generated)

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#514]
Hi All,

I am trying to generate the test where the result set is a csv file.

I am using the version 1.20.

After generating the tests using the genbil, result-set tag is visible, but the file is missing in the code.

See below:

Template:
```
<system-under-test>
    <result-set file="..\csv\test.csv"/>
</system-under-test>
```

generated code (nbits):

Template:
```
<system-under-test>
    <result-set />
</system-under-test>
```

Note: When I copy the file="..\csv\test.csv" into the generated nbits file, the test is working.

Also the assert part works only if I write it using the "old" syntax:
```
<assert>
   <equal-to>
      <resultSet file="..\test.csv"/>
   </equal-to>
```
instead of the:
```
<assert>
   <equal-to>
      <result-set file="..\test.csv"/>
   </equal-to>
```

Could you check it please and let me know if I am missing something or it is a bug?

Cheers.

**Comment by Seddryck** [comment]
Version 1.20 introduced a new syntax for the ```file``` attribute. The following syntax is considered non-canonical (but is still valid as a shortcut):

```xml
<system-under-test>
    <result-set file="..\csv\test.csv"/>
</system-under-test>
```

and should be replaced by (#444 and #442 offer new opportunities requiring to have an element and not anymore an attribute).

```xml
<system-under-test>
    <result-set>
        <file>
            <path>..\csv\test.csv</path>
        </file>
    </result-set>
</system-under-test>
```

Anyway, the non-canonical syntax should still be supported by genbiL (in a template) ... but the output will be the canonical version.

**Comment by Seddryck** [comment]
About the issue with genbiL, take a look at my comment above but I just checked your issue on 1.21-beta and I cannot reproduce. With this [template](https://github.com/Seddryck/NBi/blob/feature/result-set_file_missing_with_genbiL_(%23514)/NBi.Testing/Acceptance/GenbiL/Resources/ResultSetFile.nbitt), I have the following [result](https://github.com/Seddryck/NBi/blob/feature/result-set_file_missing_with_genbiL_(%23514)/NBi.Testing/Acceptance/GenbiL/Resources/ResultSetFile.expected.nbits).

I didn't check with v1.20 but I'd recommend to update genbi.exe (and dlls) to v1.21 to fix this potential issue. 

About the issue with result-set in the assert part of the test, #354 is part of 1.21, not really surprised that it doesn't fully work in 1.20 ;-)

**Comment by fefeslon** [comment]
Ok,

It is working the 1.21 beta.

Thanks.
