### ISSUE TITLE
Problem with settings in external file

### ISSUE THREAD

**Issue by Postarion** [Seddryck/NBi#518]
Hello :)
When I am trying to use settings from external file i get error message: settings xmlns='' was not expected. All files are in the same folder. What 

**Config file:**
`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section 
	name="nbi" 
	type="NBi.NUnit.Runtime.NBiSection, NBi.NUnit.Runtime"/>
  </configSections>
  <nbi 
  testSuite="Work in Progress\SLS R\SLSR.nbits"
  settings="AllocationTest.nbiset"/>
</configuration>`

**Settings file:**
`<?xml version="1.0" encoding="utf-8"?>
<settings>
	<default apply-to="everywhere">
		<parameter name="dateFrom">31</parameter>
		<parameter name="dateTo">2</parameter>
		<parameter name="seasonFrom">SS 2019</parameter>
		<parameter name="seasonTo">AW 2019</parameter>
		<parameter name="store">803</parameter>
	</default>
	<default apply-to="system-under-test">
		<connectionString>connection string</connectionString>
	</default>
	<default apply-to="assert">
		<connectionString>connection string</connectionString>
	</default>
</settings>`

**test file:**
`<?xml version="1.0" encoding="utf-8" ?>
<testSuite name="SLS R suite" xmlns="http://NBi/TestSuite">
	<group name="My first tests' group">
  <test name="SLS R">
    <system-under-test>
      <execution>
        <query>
		<![CDATA[
			some tests
		]]>
		</query>
      </execution>
    </system-under-test>
    <assert>
      <equalTo>
		<column index="0" role="key" type="text"/>
		<column index="1" role="value" type="numeric"/>
        <query>
		<![CDATA[
			some tests
		]]>
		</query>
      </equalTo>
    </assert>
  </test>
	</group>
</testSuite>`

**Comment by Seddryck** [comment]
I'm away from my computer and cannot double-check but it sounds that the second line of your settings file is not correct. It shouldn't be 
```xml
<settings>
```
but
```xml
<settings xmlns="http://NBi/TestSuite/">
```
(sounds that documentation is wrong, if you confirm it's fixing your issue, I'll update the documentation)

**Comment by Postarion** [comment]
Thank you, it helped. 
I only corrected one thing. The slash after http://NBi/TestSuite/ was causing problems. 

`<settings xmlns="http://NBi/TestSuite">`

**Comment by Seddryck** [comment]
Thx for the feedback. I updated the documentation at http://www.nbi.io/docs/config-settings-external-file/
