### ISSUE TITLE
Support: Is possible to define that null=0 in NBi?

### ISSUE THREAD

**Issue by CristianaDias** [Seddryck/NBi#522]
I'm trying to create a test using NBi that compare a table (SQL Server Database) against a cube (SSAS). 
The problem is that the table have zeros and the cube nulls, in the same row. 
When ruining NBi, obviously, this is a difference. 

Is possible to define in NBi that the value <null> is equal to 0?

Thank you!
Regards,
Cristiana Dias

**Comment by Seddryck** [comment]
Yes surely, you can take a look to the alteration [transform]((http://www.nbi.io/docs/scalar-transform/) to change the nulls to zero.

More specifically, I’d use a [native transformation](http://www.nbi.io/docs/scalar-transform#native) more specifically the ```null-to-zero``` native transformation. www.nbi.io/docs/scalar-native-transformation/#numeric

**Comment by CristianaDias** [comment]
Thanks for the reply!
That was exactly what I was looking for. Problem solved!
