### ISSUE TITLE
equalTo MDX comparison of 2 empty result sets should pass

### ISSUE THREAD

**Issue by analyzethat** [Seddryck/NBi#535]
Hi I am comparing MDX result sets from a tabular model versus a multidimensional model. If both MDX-queries return an empty result set the test fails because an empty set does not have key columns. I would prefer the test to pass in this case. How should I do this?

Thanks for your answer!

Johan

**Comment by Seddryck** [comment]
You've empty and empty :-). Generally speaking, comparing (`equal-to`) two result-sets having the same columns and zero rows will pass (green). On the other hand, comparing (`equal-to`)  two result-sets having different columns but still zero rows will fail (red). `equal-to` requires that the key and value columns are effectively available, this is part of the test definition. 

Depending on how you've written your queries you could have a misalignment between the two structures (columns) of the result-sets and it will fail your test.

About how to fix your issues, I'm unsure of the actual state of your test. If you're sure your queries will return 0 rows, I'd switch to a [`row-count` assertion](http://www.nbi.io/docs/resultset-rows-count/). If your tests return different structures, you can play a bit with [alterations](http://www.nbi.io/docs/resultset-alteration/) to have matching structures. If your two result-sets are so different but should return the same count of rows, I'd opt for a [`row-count` result-set to result-set](http://www.nbi.io/docs/resultset-rows-count/#row-count-of-another-result-set).

**Comment by Seddryck** [comment]
@analyzethat Does it answer your question? If yes could you please close the issue. Thx.

**Comment by analyzethat** [comment]
Thanks. Yes it does for now. I changed my test generation powershell to save tests that return an empty resultset to a different file.
