### ISSUE TITLE
Behavior="single-row" does not support column name

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#543]
Hi All,

I have tried to use the **behavior="single-row"** together with **column name** and got the following error message:
_System.InvalidOperationException : Sequence contains no elements_

It is working if I use column index instead of the name.

Is this a bug or a feature?

In case this is a feature, could it be possible to add this functionality to the next release?

Cheers.

**Comment by Seddryck** [comment]
Sounds more like a bug than a feature. I don't remember any good reason to not be able to use column names with a single-row behavior.

**Comment by fefeslon** [comment]
Ok, thanks.

One more note: I am using the latest release (1.21-RC.2).

Cheers.

**Comment by Seddryck** [comment]
The single-row behaviour was effectively expecting an ordinal comparison and not a named comparison. I changed this and it's now supporting both type of comparisons. Tell me if it works and I'll inlcude it in the final v1.21 (even if it's now in the v1.22 pipeline)

Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/28229626/artifacts or `NBi 1.22.0-beta0003`

**Comment by fefeslon** [comment]
Hey,

Just tried the 1.22 beta and the single row with column name works perfectly.

Thanks!

M.

**Comment by Seddryck** [comment]
Ok thx for feedback.
