### ISSUE TITLE
Unstack alteration should support a set of columns that must be created

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#546]
The `unstack` alteration is great to create columns from rows. Unfortunately, it’s not possible to ensure that a column will be created independently of the rows values. It’s a blocking issue when the expected columns are used in further alterations. 

It should be possible to define a set of columns that will be created independent of the rows values.

Requested by @CoolsJoris

**Comment by Seddryck** [comment]
Syntax: add `enforced-value` ... even when the values specified in this element are not found in the *header* columns based on these values will be created.

```xml
<unstack>
  <header>
    <column identifier="Header"/>
    <enforced-value>alpha</enforced-value>
    <enforced-value>omega</enforced-value>
  </header>
  <group-by>
    <column identifier="#0"/>
  </group-by>
</unstack>
```

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/28303470/artifacts or `1.22.0-beta0004`(will be integrated into final v1.21 if positive feedback)

**Comment by CoolsJoris** [comment]
Thx, seems to be working as designed.
