### ISSUE TITLE
xml-source file path error

### ISSUE THREAD

**Issue by HIrena** [Seddryck/NBi#554]
Hello, 

When in an nbitt the following is used:

```xml
<xml-source ignore-namespace="true">
  <file>~C:\Temp\\$fileIdentification$\\{@file}</file>
```

It is translated in the nbits as 

```xml
<xml-source ignore-namespace="true">
  <file>
    <path>~C:\Temp\Imbalance Prices - 17.1.G\{@file}</path>
  </file>
```
Which returns the following error: 

`At line 207: The element 'http://NBi/TestSuite:file' cannot contain child element 'http://NBi/TestSuite:path' because the parent element's content model is text only.`

Just removing the `<path></path>` tags seems to do the trick as a workaround, the test suite is loaded in the NBi then. 

Thanks!

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/28734636/artifacts or `1.22.0-beta0021`
