### ISSUE TITLE
Empty XML file generation

### ISSUE THREAD

**Issue by HIrena** [Seddryck/NBi#555]
Hello, 

Not really an issue, but is it possible to generate an xml from an existing from-select structure? Creating manually xmls to use paired with a `<if-missing>` feature could be troublesome. 

Thank you!

**Comment by Seddryck** [comment]
Fair feedback, creating empty files is boring and not so straightforward. 

I propose to add a `if-unavailable` element in a `result-set` to specify another `result-set` if the first one is failing. At the moment, I'll just activate this feature in case an `xml-source` is failing but feel free to give me some feedback and check if we cannot generalize.

In addition, I'll create a new child element of `result-set` named `empty` and accepting an attribute `column-count` or a list of column-names. 

Combining these two new features, it should be easier to create an empty result-set when something is going wrong into your `xml-source`.

**Comment by Seddryck** [comment]
- [X] new element `empty` for a `result-set`
- [X] new element `if-unavailable` for a `result-set`

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/28736908/artifacts or `1.22.0-beta0025`
