### ISSUE TITLE
Relation between object test causes System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by NeilRoper** [Seddryck/NBi#558]
Hi,

I've searched through the issues list and double checked my test, but I am getting this error running any tests using the "Linked to Measure Group" and "Linked to Dimension" test templates. NBi version 1.19. I am following the instructions http://www.nbi.io/docs/model-relation/.

```
NBi.NUnit.Runtime.TestSuite.A dimension 'Dimension_Name' is linked to a measure-group named 'Measure_Group_Name' in perspective 'Perspective_ABC'.:
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.

at NBi.Core.Structure.Tabular.TabularStructureDiscoveryFactory.InstantiateBuilder(Target target, TargetType type)
at NBi.Core.Structure.Olap.OlapStructureDiscoveryFactory.Instantiate(Target target, TargetType type, IEnumerable`1 filters)
at NBi.NUnit.Builder.StructureLinkedToBuilder.InstantiateCommand(AbstractItem item)
at NBi.NUnit.Builder.AbstractStructureBuilder.InstantiateSystemUnderTest(StructureXml sutXml)
at NBi.NUnit.Builder.AbstractStructureBuilder.BaseBuild()
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build()
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
```

An example test is defined as:
```
  <test name="A dimension 'Dimension_Name' is linked to a measure-group named 'Measure_Group_Name' in perspective 'Perspective_ABC'.">
    <description>Assert that the dimension named 'Dimension_Name' is linked to a measure-group named 'Measure_Group_Name' in perspective 'Perspective_ABC'</description>
    <edition author="UserXYZ" created="2019-11-12T13:15:35" />
    <system-under-test>
      <structure>
        <dimension caption="Dimension_Name" perspective="Perspective_ABC" />
      </structure>
    </system-under-test>
    <assert>
      <linkedTo>
        <measure-group caption="Measure_Group_Name" />
      </linkedTo>
    </assert>
  </test>
```

This is as per the template without any changes. I also checked the same tests that are in the NBI testing project and couldn't see any major differences.

To load the template I am using this source query:
```
SELECT
	[CUBE_NAME] AS [perspective],
	[MEASUREGROUP_NAME] AS [measuregroup],
	--to remove square brackets as caption name not available in this dmv
	LEFT(
		RIGHT([DIMENSION_UNIQUE_NAME], LEN([DIMENSION_UNIQUE_NAME])-1),
		LEN([DIMENSION_UNIQUE_NAME])-2
		) AS [dimension] 
FROM [$system].[MDSCHEMA_MEASUREGROUP_DIMENSIONS]
```

Other tests in the same test suite run fine so I am assuming my connection information is fine. Setup of the framework was done using the package manager console with just

`Install-Package NBi.VisualStudio -version 1.19.0`

I found that plain vanilla installs of versions 1.20.0 and 1.21.0 had assembly library issues.

Any help appreciated and thanks for a wonderful framework.

**Comment by Seddryck** [comment]
Hello,

Thanks for the detailed error message:

Is it a Tabular (DAX) or a Multidimensional (MDX) model? If it's tabular then the usage of this test is not supported (as far as I remember, relations are not really in the model with a tabular model).

If it' a multidimensional model then I'll need the connection-string and your version of SQL Server because apparently the automated detection of the mode (Tabular or Multidimensional) is not happening correctly.

Thx for the head up for NBi.VisualStudio 1.20 and 1.21, I'll fix it.

**Comment by NeilRoper** [comment]
Hello @Seddryck,

Yes sorry this is my mistake, I should have read the documentation a bit closer, as it is tabular I am using. 

I will have to work out another way of seeing if a dimension is joined to a measure group, i.e. do aggregation amounts change for different attributes of the same dimension.

Thanks for getting back to me.
