### ISSUE TITLE
Genbil converting "connectionString" property in template to "connection-string" in generated test

### ISSUE THREAD

**Issue by NeilRoper** [Seddryck/NBi#560]
Hi @Seddryck 

Have raised a new issue as I couldn't find a similar item in the issues list.

When using an assert with "connectionString" in the template, this is converted to "connection-string" in the generated test. This of course means the test fails to run and requires a find and replace - no big issue but not great for automation - is there a known workaround for this?

**To replicate**
Open genbil and load the following test cases as a query:
`select 'example test' as testname`

Add this example template. Note I have put two asserts here on purpose just to check if this is happening for multiple property types.
```xml
<test name="template $testname$">
  <system-under-test>
    <execution>
      <query>
        <![CDATA[select * from [$testname$]]]>
      </query>
    </execution>
  </system-under-test>
  <assert>
    <row-count>
      <less-than or-equal="true">
        <!--the "connectionString" propery gets converted to "connection-string" when processed through genbil-->
        <query-scalar  connectionString="Data Source=mhknbn2kdz.database.windows.net;Initial Catalog=AdventureWorks2012;User Id=sqlfamily;password=sqlf@m1ly" >
          <![CDATA[select * from [$testname$]]]>
        </query-scalar>
      </less-than>
    </row-count>
  </assert>
<assert>
      <row-count>
        <more-than or-equal="true">
          <projection type="row-count">
            <resultSet>
              <query connectionString="Data Source=mhknbn2kdz.database.windows.net;Initial Catalog=AdventureWorks2012;User Id=sqlfamily;password=sqlf@m1ly">
                <![CDATA[  select * from [$testname$]]]>
              </query>
            </resultSet>
          </projection>
          </more-than>
       </row-count>
    </assert>
</test>
```
When generating tests, note that the output now has "connection-string" which causes the test to fail.
![image](https://user-images.githubusercontent.com/10855163/69056914-3b125380-0a11-11ea-819a-86fb2acb4a25.png)

Hope you don't mind me reporting such a pedantic bug :) Thanks in advance for your time.

Version used is 1.19.

**Comment by NeilRoper** [comment]
Also, the same thing is happening with `<resultSet>` being converted to `<result-set>`.

This is only in the Assert section of the test, the System under test remains the same.

**Comment by Seddryck** [comment]
Hi Neil, transformation of syntax 1.0 into syntax 2.0 is a feature not a bug :-). http://www.nbi.io/docs/syntax-2-0/#pascalcase-vs-dashes 

Genbi is a bit more advanced than simply using a text template and perform some substitutions. Genbi will serialize the test and then deserialise it. It means that the syntax 2.0 is applied and the unknown tags are removed. It sounds a bit weird at the beginning but also means that it’s forward compatible.

**Comment by Seddryck** [comment]
If I understand correctly, your test is working with the old syntax but not the new one. I’ll investigate this point to be sure that the new syntax is also supported.

**Comment by NeilRoper** [comment]
Thanks Cedric, so if the conversion is going from pascal (connectionString) to dash (connection-string) during serialise/deserialise, why does the test runner not recognize the changed attribute (connection-string)? Am I referencing an incorrect xsd or something silly like that?

So in answer to your second comment, the tests are not working with the dash syntax...weird.

Apologies in advance if I am doing something stupid ;)

**Comment by Seddryck** [comment]
I tried with v1.21 and I can't reproduce. NBi correctly understands the syntax 2.0. 

I checked v1.19 and this version is not supporting the `connection-string` or the `result-set` syntax. It should generate errors such as
```
The element 'system-under-test' in namespace 'http://NBi/TestSuite' 
has invalid child element 'result-set' in namespace 'http://NBi/TestSuite'. 
List of possible elements expected: 'execution, resultSet, scalar, members, structure, data-type' 
in namespace 'http://NBi/TestSuite'.
```
or
```
At line 105: The 'connection-string' attribute is not declared.
```

On the other hand, *genbi.exe* v1.19 should not generate the `connection-string` or the `result-set` syntax. Are you using *genbi.exe* v1.21 to generate the test-suite and the framework v1.19 to run the test-suite? If it's the case, it's not supported. You should downgrade *genbi.exe* to v1.19 or upgrade the framework to v1.21 (recommended).

**Comment by Seddryck** [comment]
As a side note, NBi is not supporting `default` or `reference` connection strings in the `row-count` assertion. This is a feature that I will investigate.

**Comment by NeilRoper** [comment]
Thanks very much for the last two comments 👍 :

"Are you using genbi.exe v1.21 to generate the test-suite and the framework v1.19 to run the test-suite?" 

That was the stupid thing I felt I must be doing. Yes, a while ago I downloaded v1.21 genbi framework and was using this so problem at the keyboard. I will upgrade the framework.

"NBi is not supporting default or reference connection strings in the row-count assertion."

This was driving me crazy yesterday as I could not get the reference connection string working for the row-count assertion - glad to know that it is currently unsupported and not something I was doing wrong. I have worked around this by putting in the whole connection string for now as part of the source query for the nbitt template.

**Comment by NeilRoper** [comment]
Just to confirm, I had package NBi.VisualStudio 1.19.0 installed.

I ran this on package manager console:
`update-package NBi.Framework`

This updated the framework to version 1.21.0 but caused a reference error requiring nunit version 2.7.1.

I then ran:
`update-package NUnit -version 2.7.1`

Tests ran fine after that and also the generation of tests from Genbil.

**Comment by Seddryck** [comment]
Great. You can check the version `1.22.0-beta0035` available on nugget. It should be fixing the issue with row-count connection strings not taking into account defaults/references.

https://www.nuget.org/packages/NBi.Framework/1.22.0-beta0035

**Comment by NeilRoper** [comment]
Ok, tried to test this.

I ran this package update (also the 0044 version) on a project with version 1.21.0 on:

`update-package NBi.Framework -Version 1.22.0-beta0035`

Unfortunately I couldn't test as I was getting this error message:

Could not find file ...\bin\Debug\NBi.NUnit.Runtime.dll

Checking the build directory all the NBi....dll assemblies are missing - is it because I ran an update instead of a clean install?

All package references remained the same except these two:
```
<package id="NBi.Framework" version="1.22.0-beta0044" targetFramework="net461" />
<package id="RestSharp" version="106.6.10" targetFramework="net461" />
```
