### ISSUE TITLE
Define sequence with a query

### ISSUE THREAD

**Issue by lukzas** [Seddryck/NBi#565]
I'm currently using sequence defined manually inside `<instance-settling>` block, let's say
```xml
<instance-settling>
      <local-variable name="locale" type="text">
          <item>EN</item>
          <item>FR</item>
      </local-variable>
</instance-settling>
```
Is is possible to use query inside to generate list adhoc e.g. similarly to `<one-column-query>` available in assertion? If not, are you able to deliver such feature? It would be really handy in a few scenarios I have.

`<file-loop>` seems to be not flexible enough, because I would need to have the CSV beforehand, on the other hand, custom assembly sequence seems to be overkill (and not a really smart solution for such scenario?)

In general, the ability to define a sequence as a variable in `<settings>` block would be nice too.

**Comment by Seddryck** [comment]
Yes, I could implement to support a query as the definition of a sequence. About the ability to define sequences at the test-suite level, I’m thinking about it for release 2.0

**Comment by Seddryck** [comment]
Feature available at https://ci.appveyor.com/project/Seddryck/nbi/builds/29234608/artifacts or `1.22.0-beta0047`
