### ISSUE TITLE
Usage of variables in an assert/equal-to/query

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#568]
Reported by @lukzas in #566:

``` xml
<assert>
  <equal-to>
    <query>
      <parameter name="@table">@Table</parameter>
           SELECT * FROM @table
      </query>
   </equal-to>
</assert>
```

NBi doesn't sound to understand the variable.

**Comment by Seddryck** [comment]
This test is perfectly working (available in acceptance tests [variable.nbits](https://github.com/Seddryck/NBi/blob/develop/NBi.Testing/Acceptance/Resources/Positive/Variable.nbits) - line 50 to 68):

```xml
  <test name="Usage of the same variable in Sut and Assert" uid="0010">
    <system-under-test>
      <result-set>
        <query>
          <parameter name="common">@common</parameter>
          select @common;
        </query>
      </result-set>
    </system-under-test>
    <assert>
      <equal-to>
        <column index="0" type="dateTime" role="key"/>
        <query>
          <parameter name="common">@common</parameter>
          select @common;
        </query>
      </equal-to>
    </assert>
  </test>
```

The issue is in the definition of your parameter. It should be the name of the parameter without the arobas (@).

```xml
<parameter name="table">@Table</parameter>
```

**Comment by lukzas** [comment]
The reason why I had (@) is that I was executing in `<instance-settling>` context as per the original issue and this is what I've found in `NBi.Testing/Acceptance/Resources/Positive/MultipleInstance.nbits` suite line 150 `<parameter name="@dept">@department</parameter>` 😉

**Comment by Seddryck** [comment]
The attribute name is expecting the parameter’s name without the @. At the best, not checked, if you add a @ then the parameter’s name would become dynamic and based on variable value (should be tested). 

About the test you mentioned, I’ll have to double-check but I’m relatively sure that the parameter is ignored by the query (unexpected) and the query is returning more than 10 rows anyway. Thx the heads up I’ll check this.
