### ISSUE TITLE
Can NBI support Essbase database?

### ISSUE THREAD

**Issue by fondywang** [Seddryck/NBi#575]
Dear Sir,

Can NBI connect to Oracle Essbase database and do the MDX query for the validation? 

Thanks @ Best Regards,
Fondy

**Comment by Seddryck** [comment]
Does Essbase use the standard ADOMD.net library? Apparently not. If you confirm this, then the only way will be to provide your own extension for Essbase. Check this page to have link to existing extensions and feel free to check their code on how they have been developped. If you've questions specific to this development feel free to ask but I'll no clue about Essbase.
