### ISSUE TITLE
Add namespaces to CSharpScalarResolver

### ISSUE THREAD

**Issue by lukzas** [Seddryck/NBi#584]
I wanted to use LINQ and XML inside `<script language="c-sharp">` block, but unfortunately assembly reference was not found. 

I've checked the code and indeed only `System` was referenced in a code template. However, it works after I've added them to both template and `ReferencedAssemblies` field of `CompilerParameters()`

Could you add some of the standard namespaces that might be useful or parametrize? Also, I can create PR fo you like.

**Comment by Seddryck** [comment]
Feel free to submit a PR!

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/builds/31536821 (version `1.23.0-beta.18`)
