### ISSUE TITLE
Is there a way to display the failed rows in the test results?

### ISSUE THREAD

**Issue by lymedo** [Seddryck/NBi#588]
I'm performing a attribute comparison on a dimension and would like to see failed rows within the test result. Currently, I only see a message stating 'Execution of the query doesn't match the expected result' and a table is displayed with all of the rows (keys/values) of the assert query. 

Is there any way of displaying a list of keys where the comparison has failed on the attributes?

Here's my test:

```xml
<test name="Attribute Compare Rows Diff" uid="201">
      <system-under-test>
        <result-set>
          <query connection-string="@conn-localhost">
            SELECT business_key, attribute FROM [dbo].[source]
          </query>
        </result-set>
      </system-under-test>
      <assert>
        <equalTo>
          <column index="0" role="key"/>
          <column index="1" role="value" tolerance="ignore-case"/>
          <query connection-string="@conn-localhost">
            SELECT business_key, attribute FROM [dbo].[target]
          </query>
        </equalTo>
      </assert>
    </test>
```

**Comment by Seddryck** [comment]
The result of the test should contain three tables. One with the expectations, one with the actuals and one with the analysis only containing rows with a non-match (or missing/unexpected).

Have you got this problem in the NUnit UI or in the `TestResult.xml` file? If it's in NUnit UI, it's a bug of the UI, just copy/paste the result into notepad and you'll see the full content of the test result. If your TestResult.xml has this issue then it's probably something that you adapted in the config file. Check [this page](http://www.nbi.io/docs/data-quality-setup/) for documentation.

NB: it's recommended to use `equal-to` and not anymore `equalTo`

**Comment by lymedo** [comment]
@Seddryck 

Is there any documentation on what the allowed values are for the DQ config you suggested?

`<failure-report-profile
        threshold-sample-items="50"
        max-sample-items="25"
        expected-set="None"
        actual-set="None"
        analysis-set="Sample"
        format="Json"
        mode="Always"
    />`

**Comment by Seddryck** [comment]
@lymedo not more than the page that I pointed in my previous answer. What additional info are you looking for?
