### ISSUE TITLE
Nunit FileLoadException when using Bootstrapper in Visual Studio 2019

### ISSUE THREAD

**Issue by FLandgraf** [Seddryck/NBi#591]
When setting up a new Project (Class Lib .Net Framework) and integration the NBI.VisualStudio Bootstrapper in Visual Studio 2019 everything seems to be fine at first glance.

When hitting F5 Nunit will show up but present the following error:
_System.IO.FileLoadException: Could not File or Assembly "nunit.framework, Version=2.7.1.0, Culture=neutral,PublicKeyToken=2638cd05610744eb" or one of its dependencies.

These Token points to
```
<Reference Include="nunit.core, Version=2.7.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnitV2.Core.2.7.1\lib\nunit.core.dll</HintPath>
</Reference>
<Reference Include="nunit.core.interfaces, Version=2.7.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnitV2.Core.2.7.1\lib\nunit.core.interfaces.dll</HintPath>
</Reference>
```
Does anybody else experience the same problem?

**Comment by volkerheck** [comment]
Yes, I am running into the same issue. 
Volker

**Comment by Seddryck** [comment]
I'll take a look to this.

**Comment by Seddryck** [comment]
As a work-around, run `Update-Package NUnit -version 2.7.1.0` to be sure that the correct version is registered in your project. I'll check in the package itself where the reference is wrong.

**Comment by volkerheck** [comment]
Thank you – that makes sense. I will try and let you know.

**Comment by Seddryck** [comment]
I updated to NBi.VisualStudio 1.22.0 and 1.22.1 to fix this kind of issues, feel free to use them.

**Comment by volkerheck** [comment]
Thank you!

Mit freundlichen Grüßen
Volker Heck
Senior Consultant | Microsoft Certified Trainer<https://www.youracclaim.com/badges/3b239071-c662-48c3-a210-6de1f6e11ab5/public_url>

Mob:    +49 175 3317482
Mail:    v.heck@kigroup.de<mailto:v.heck@kigroup.de>
Web:   www.ki-performance.com<http://www.ki-performance.com/>
_____________________________________________________
KI performance GmbH – Mittelstraße 12-14 – D-50672 Köln
Geschäftsführer: Steffen Braun, Sascha Utzen – Sitz/Registergericht: Köln – HRB 86595
w3w address: /// anfrage.ereignen.rahmen<https://map.what3words.com/anfrage.ereignen.rahmen> /// cycle.trout.hovered<https://map.what3words.com/cycle.trout.hovered>

Von: Cédric L. Charlier <notifications@github.com>
Gesendet: Sonntag, 7. Juni 2020 14:40
An: Seddryck/NBi <NBi@noreply.github.com>
Cc: Volker Heck <v.heck@kigroup.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Seddryck/NBi] Nunit FileLoadException when using Bootstrapper in Visual Studio 2019 (#591)


I updated to NBi.VisualStudio 1.22.0 and 1.22.1 to fix this kind of issues, feel free to use them.
