### ISSUE TITLE
Support XPath evaluation to non-element types returned by functions in xml-source select

### ISSUE THREAD

**Issue by lukzas** [Seddryck/NBi#593]
Consider the following code
```
<xml-source>
  <file>...</file>
    <xpath>
      <from>...</from>
      <select attribute="Name">../..</select> // ok
      <select>.</select> // ok
      <select>ElementName</select> // ok
      <select attribute="Name">string-length(.)</select> // throws exception
    </xpath>
</xml-source>
```

```
NBi.NUnit.Runtime.TestSuite.Test:
System.AggregateException : One or more errors occurred.
  ----> System.InvalidOperationException : The XPath expression evaluated to unexpected type System.Double.
```

There are multiple XPath functions that return `Boolean`, `String`, or `Number` instead of an element or node. I didn't dig into the evaluation code, but usually, with this kind of error, it's the matter of evaluating the result with `XPathEvaluate()` rather than `XPathSelectElement()`. Or maybe there is some workaround?

**Comment by Seddryck** [comment]
Did you try this feature (select evaluate)?
https://github.com/Seddryck/NBi/blob/7fc8c073a52a6f05568f3591b66eb740f0430170/NBi.Testing/Acceptance/Resources/Positive/QueryEqualToXml.nbits#L112-L116

I don't find documentation but I think it should do the job.

**Comment by lukzas** [comment]
Thanks, it works fine.
