### ISSUE TITLE
Error with Visual Studio

### ISSUE THREAD

**Issue by jsh2github** [Seddryck/NBi#597]
Hello, I'm following the documentation on setting up NBi using the visual studio bootstrapper and the install goes fine.

However when I hit F5 like the next step says, I get this error: 
![error1](https://user-images.githubusercontent.com/66076354/83156143-ac6d4600-a0c7-11ea-8386-a9896e223779.PNG)

So following my folder structure, it seems like it's looking for that SSASNBi folder one place early. (I created a folder on my desktop to host the project that I created within visual studio)

I try to circumvent this by taking what exists within the folder that seems to be missing and pasting it into the folder seems to think it should be in. After doing this and hitting F5 again, I get a new error:
![error2](https://user-images.githubusercontent.com/66076354/83156392-fb1ae000-a0c7-11ea-9772-09d1d50feaba.PNG)

I'm fairly new to NBi so I'm sorry if I'm missing something obvious, but I'm not really sure what else to try here.

Thanks in advance for the help.

**Comment by Seddryck** [comment]
Sorry but I can't reproduce. If you go to the "properties" of your project then on "debug", you've a parameter "Working directory". This one is probably wrong, you should adjust this value.

**Comment by permind** [comment]
The default installation of NBi.VisualStudio has extra `\..\` in working directory location. You need to fix that.
E.g.` NBi.VisualStudio.1.21.0\..\..\..\NBI_temp\bin\debug\`

Also. NBi.VisualStudio is not aligned with NBi.Framework package. You need to upgrade framework to 1.22 manually. Otherwise you will get error in Nunit runner.
      System.IO.FileLoadException. Could not load nunit.framework Version=2.7.1.0

**Comment by Seddryck** [comment]
Thanks for pointing out that the package was not updated with a reference to 1.22.0. new version published. I fixed it in `NBi.VisualStudio 1.22.0`

About the working directory location that was not correct, I cannot reproduce this but I updated the code for this detection in `NBi.VisualStudio 1.22.1`. Hope, it's fixing the issue.
