### ISSUE TITLE
Every failed tests end up as error

### ISSUE THREAD

**Issue by AnimeshRoy86** [Seddryck/NBi#602]
Currently trying to assert the rowcount which should return as less than equal to 45. However the number returning is 47. In this scenario the should be marked as failed and not error. Am I missing something in this case?

NBi.NUnit.Runtime.TestSuite.My fifth test:
NBi.NUnit.Runtime.CustomStackTraceAssertionException :   Expected: count of rows returned by the query is less than or equal to 45m
  But was:  47

Actual result-set returned by the query:
Result-set with 47 rows

     #0 (fact_grn_gst[unit_key]) | #1 ([GRN_Count])
     --------------------------- | ---------------- 
     95                          | 33543           
     53                          | 28466           
     10                          | 4702            
     2                           | 35941           
     92                          | 59940           
     11                          | 26203           
     69                          | 34643           
     58                          | 45576           
     51                          | 26240           
     15                          | 23977           

37 (of 47) rows have been skipped for display purpose.

**Comment by Seddryck** [comment]
Due to limitations of NUnit Framework 2.x, all falures are reported as Errors. Won't fix before moving to NUnit 3.x, where I hope this limitation is removed.
