### ISSUE TITLE
Visual Studio Test explorer not showing/Identifying the NBi tests 

### ISSUE THREAD

**Issue by RaghavM3** [Seddryck/NBi#604]
Hi @Seddryck,

I have created a ClassLibrary project in visual studio 2017 as per the documentation here (http://www.nbi.io/docs/installation-bootstrap-visual-studio/ ) and able to run the tests by pressing F5.

![image](https://user-images.githubusercontent.com/67321649/85400476-13bad080-b576-11ea-8d5a-6a1ee616f86a.png)

I wanted to see the tests in tests explorer then will associate these with azure.

Could you please help me if I am missing something here.

Many thanks.

**Comment by Seddryck** [comment]
You cannot do that at this moment.
