### ISSUE TITLE
Adding CSV profile to GenbiL and other small additions

### ISSUE THREAD

**Issue by TheAutomatingMrLynch** [Seddryck/NBi#610]
Hi Seddryck,

I have created a PowerShell module for test generation based on GenbiL (perhaps you remember :-) ). We have used the alpha version internally for some years and I think it's ready for prime time now. I have made a few changes/additions to the NBi.genbiL project that I would like to share with you. 

- Added actions for CSV profiles (FieldSeparator, RecordSeparator, FirstRowHeader, EmptyCell, MissingCell and TestQualifier)
- Added a "public" modifier to the GenerateTestGroupBySuiteAction class
- Added the class "IncludeSuiteFromStringAction" to enable the same functionality as "IncludeSuiteAction" but without having to save it as a file first
- Added test cases for the above

Kind regards
Bjarne

**Comment by Seddryck** [comment]
Included your pull request in a branch "feature/csv-profile_to_genbiL_(#610)" and adding parsers.

**Comment by Seddryck** [comment]
Beta available in [1.23.0-beta0056](https://ci.appveyor.com/project/Seddryck/nbi/builds/36814366)

**Comment by Seddryck** [comment]
@TheAutomatingMrLynch I'd like to refactor a few things including a change of namespace, is it a problem for you?

**Comment by TheAutomatingMrLynch** [comment]
Not at all! I'll just fix my code whenever you have a new release.

**Comment by Seddryck** [comment]
I mostly removed the `CsvProfile` prefix on the actions and moved these actions to a new namespace `Setting.CsvProfile`
