### ISSUE TITLE
Unable to pass parameter to Sql query

### ISSUE THREAD

**Issue by q3abhi** [Seddryck/NBi#634]
I am trying to pass the variable as a parameter to my sql query. 

This is my test. I am passing the variable (DateKey) declared in assert section.

``` XML
<test name="Cash Receipts - Current">`
  <system-under-test>`
    <execution>
      <query file="DaxQueries\CashReceipts\CashReceipts - Current.sql" />
    </execution>
  </system-under-test>
  <assert>
    <equalTo>
      <column  index="0" role="key" type="text" tolerance="1"/>
      <column  index="1" role="value" type="numeric"/>
      <column  index="2" role="value" type="numeric"/>
      <column  index="3" role="value" type="numeric"/>
      <column  index="4" role="value" type="numeric"/>
      <query file="SqlQueries\CashReceipts\CashReceipts - Current.sql">
        <parameter name="DateKey" sql-type="Int">20200331</parameter>
      </query>
    </equalTo>
  </assert>
</test>
```

This is my sql query defined in "CashReceipts - Current.sql" file. Using @DateKey to pass the value here.

``` sql
SELECT
	r.AsOfDate AS [CalendarKey]
	,SUM(r.YesterdayBalance) AS [Today]
	,SUM(r.WeekBalance) AS [WeekToDate]
	,SUM(r.MonthBalance) AS [MonthToDate]
	,SUM(r.FYTDBalance) AS [YearToDate]
FROM
	wdw.fctReceivable r
INNER JOIN
	[wdw].[dimCalendar] c ON r.AsOfDate = c.CalendarKey
WHERE
	c.CalendarKey = @DateKey
GROUP BY
	r.AsOfDate
```

When I run the test, I get the following error :

```
NBi.NUnit.Runtime.TestSuite.Cash Receipts - Current:
System.AggregateException : One or more errors occurred.
  ----> System.Data.OleDb.OleDbException : Must declare the scalar variable "@DateKey".`
```  
If I hard-code the value in sql query, test runs fine.

**Comment by Seddryck** [comment]
_Preliminary comment:_ I do not recommend to use the ```execution``` and ```equalTo``` syntax but to switch to the new syntax ```result-set``` and ```equal-to```. The old syntax that you're using is still supported but limited in terms of new features and will be deprecated.

_Main answer:_ The issue is probably related to 

```xml
<execution>
      <query file="DaxQueries\CashReceipts\CashReceipts - Current.sql" />
</execution>
```
This query has no parameter defined.

**Comment by q3abhi** [comment]
@Seddryck 

The parameter is defined in the "Assert" section as I am testing SSAS (System under test) and asserting it with sql. 

`<assert>`
    `<equalTo>`
      `<column  index="0" role="key" type="text" tolerance="1"/>`
      `<column  index="1" role="value" type="numeric"/>`
      `<column  index="2" role="value" type="numeric"/>`
      `<column  index="3" role="value" type="numeric"/>`
      `<column  index="4" role="value" type="numeric"/>`
      `<query file="SqlQueries\CashReceipts\CashReceipts - Current.sql">`
        `<parameter name="DateKey" sql-type="Int">20200331</parameter>`
      `</query>`
    `</equalTo>`
  `</assert>`

**Comment by Seddryck** [comment]
Could you post your exact queries in the assert and system under test. I don’t see any reason why your query in system under test shouldn’t have a parameter but the query in assertion should.
