### ISSUE TITLE
how can I have multiple nbits files in VS project

### ISSUE THREAD

**Issue by manish-minni** [Seddryck/NBi#660]
I am new to NBi. I have setup a project in my VS 2019 solution following the NBi documentation. 

But I wish to be able to separate test suites into multiple nbits files for maintainability. 

How can I achieve that ?

Thanks for your help

**Comment by manish-minni** [comment]
I found a way which seems to meet my need:

1. Create multiple Config tags in the TestSuite.nunit file
2. Each Config tag can use configfile attribute to point to a different config file
3. Each config file can use its nbi tag's testSuite attribute to point to a different nbits file
4. In the nunit file, the Settings tag's activeconfig attribute can point to the name of the Config to be selected

Please let me know if this is the correct way, or there is some better way.

Thanks

**Comment by Seddryck** [comment]
To be honest, creating multiple `nbits` files has never been a concern for us. As we use genbiL to generate the `nbits` file, the maintainability challenge is not really in the resulting file.

The way you've implemented sounds really aligned with our vision of config files and the re-use of NUnit settings. Sounds as a smart idea to me.

**Comment by manish-minni** [comment]
Thanks for the confirmation & encouragement 

I will have a look at genbiL 

I can close this one :)
