### ISSUE TITLE
Stacktrace shows ConnectionString Username and Password on failure

### ISSUE THREAD

**Issue by Davijde** [Seddryck/NBi#662]
Hello,
When I execute Test Suite through AzureDevOps in case of test failure it shows clearly all sensitive data from Connection String.

I'm targeting Azure SQL Database and SQL Pool

![2021-10-14_13-02-07](https://user-images.githubusercontent.com/28105040/137306133-84350f03-273f-4025-b46d-c25fcbc9f9a9.png)

I tried with all possible Authentication methods but this seems to be the only working one on DevOps.

There is a way to hide the string info and just showing the actual test failing?

**Comment by Seddryck** [comment]
Does it solve your issue? https://github.com/Seddryck/NBi/issues/585

**Comment by Seddryck** [comment]
As there is no answer, i consider that indeed this previous issue resolution was also applicable for this case.
