### ISSUE TITLE
Question (Need Help): SQL Terminator ; or GO

### ISSUE THREAD

**Issue by shiv24saxena** [Seddryck/NBi#673]
Hi Seddryck,

Happy New year. One quick question I have on SQL statement terminator. SQL SERVER support both semicolon ; and GO as script terminator. I tried to execute a CREATE VIEW statement through NBi, but it failed as script is having GO as terminator. Later I change it to ; and able to execute the script. 

So my question is, in NBi do we have any attribute where I can define what terminator NBi should use or I need to do GO to semicolon conversion externally to NBi.

Thanks in advance.

**Comment by Seddryck** [comment]
GO is a command not a statement terminator. As such it's not supported in queries.

**Comment by shiv24saxena** [comment]
Thanks for your response.
