### ISSUE TITLE
Genbil csv profile - escape char for double quote?

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#688]
Hi All,

Does anyone know what is the escape char used in the Genbil?

I have tried backslash and doubling the quotes, without success.

Is it somewhere in the documentation?

Is it possible to change it? (from the documentation I assume it's not.) 

Cheers.

**Comment by fefeslon** [comment]
Sorry, looks the **backslash** works as escape character (if the whole field is double quoted).

Maybe it'd be worth to document it somewhere.

Cheers. (closing the issue)

**Comment by Seddryck** [comment]
I'm off at this moment but will check in a few days and fix doc if needed.
