### ISSUE TITLE
Pipeline log result in Azure DevOps

### ISSUE THREAD

**Issue by stefaniaa09** [Seddryck/NBi#689]
Hello,
I don't know if it's the right place to answer, but has anyone struggled with this?
I have a NBi test integrated in Azure DevOps pipeline where I compare 2 queries.
In the pipline logs I get the message: "x (of y) rows have been skipped for display purpose" and I get only 10 rows to view the differences, even if I have maybe more than 100. I don't find any solution to view all rows.

Thank you!

**Comment by Seddryck** [comment]
That's the default option when you have more than 25 rows in error only the 10 first are displayed. You can override this setting in your config file as explained in the [doc about settings](http://www.nbi.io/docs/data-quality-setup/). 

Nevertheless, keep in mind that it can overload your error report :-). 

Thx to close the issue if it answers your question.

**Comment by Seddryck** [comment]
This [page](http://www.nbi.io/docs/config-profile-failure-report/) could also help.

**Comment by stefaniaa09** [comment]
Thank you, I already made those changes. I only have the .trx file with test results in DevOps and from the documentation I understand that I need the TestResult.xml where I can find all rows. I couldn’t find it yet.

**Comment by stefaniaa09** [comment]
Updates not very productive :(

In documentation, at "Setup for Data Quality Rules engine" it says "These two settings will enable NBi to always add to the result file some information about the tests in a JSON format. The JSON content is embedded in the element message of the xml file containing the results." How and where this xml file is generated? Because I don't find it anywhere.

I have a pipeline like this one with VsTest assemblies: https://github.com/Seddryck/NBi/issues/399

Thank you for your answers!

**Comment by ghost** [comment]
Hello , can you provide please provide the method to run the test on azure pipelines
