### ISSUE TITLE
TestResult.xml - missing content if tests contain error using Nunit console

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#690]
Hi All,

When I run the NBi tests using the nunit3 console, if there is en error message in any of the tests then the TestResult.xml is empty and does not contain the result data (only the test run tag and command line tag inside it with the run parameters).

If I run the very same tests using the Nunit 2.4 GUI, the TestResult.xml contains both, the tests data (either passed of failed) and the error data (e.g. duplicities in keys, hexadecimal errors in the OLAP cubes etc.)

Is there a way to get the very same result using the nunit3 console?

Maybe this is more of nunit thing than NBi, but I would be thankful for any advice/documentation.

Cheers.

**Comment by Seddryck** [comment]
NBi 1.x is not using NUnit 3.x but NUnit 2.x. There is a branch (dev_v2) with a port of NBi to NUnit 3.x but not all tests are already migrated. 

AFAIK, using NUnit GUI 3.x with NUnit 2.x requires the user of an adapter to generate the results in the same format than NUnit GUI 2.x. It's surely documented on NUnit repository.

**Comment by fefeslon** [comment]
Ah ok.. 

I have been using the nunit3 console (by mistake) whole time without any problems until I got the tests with error as test result (didn't even notice I should have used 2.x).

Thanks for the explanation.

Cheers.
