### ISSUE TITLE
Why the Lookup-Matches assertion returns error even if it is not supposed to ?

### ISSUE THREAD

**Issue by Davijde** [Seddryck/NBi#701]
Hi All,
I'm trying to build a test using the [lookup-matches](http://www.nbi.io/docs/lookup-matches/) assertion, based on the documentation:

> _If a row from the candidate result-set has no matching key in the reference result-set, it’s not considered as an issue for the test and this row will be considered as successful._

Anyway, when I execute it trough Azure DevOps I get a failure with the following message

![image](https://user-images.githubusercontent.com/28105040/199926530-30e19c12-9bf9-4eb0-a097-ed6789607219.png)

Am I missing something ?

This is the test template I'm using

![image](https://user-images.githubusercontent.com/28105040/199927470-369a09c9-97c8-444d-8e2d-27efc18472be.png)

Thanks in advance for any useful feedback :)

**Comment by Seddryck** [comment]
I was a bit by surprise by my own documentation when reading
> If a row from the candidate result-set has no matching key in the reference result-set, it’s not considered as an issue for the test and this row will be considered as successful.

and the code confirmed my doubts

https://github.com/Seddryck/NBi/blob/9c01075681d4532137b6bfbbf06cbfae20e6fd93/NBi.Core/ResultSet/Lookup/LookupMatchesAnalyzer.cs#L72-L73

Clearly sounds that the documentation is not aligned with the code ... it means that the truth is in the tests! Unfortunately, the tests are giving following answer: the code is right and the documentation is wrong. We've a specific test checking that candidate rows without matching keys in the reference should be reported as violations.

https://github.com/Seddryck/NBi/blob/9c01075681d4532137b6bfbbf06cbfae20e6fd93/NBi.Testing.Core/ResultSet/Lookup/LookupMatchesAnalyzerTest.cs#L110-L119

**Comment by Seddryck** [comment]
I'll be waiting your feedback and especially your use-case for considering that candidate rows without matching reference keys should be marked as successful. I can always change my mind!

**Comment by Davijde** [comment]
Hi Seddryck, 
sorry for late response, my intent was to have a test that checks the following:

given two dataset A and B, all rows from A that **have a Key match** with B must have equal **Value** too.
All non matching rows we don't care.

![image](https://user-images.githubusercontent.com/28105040/202396240-5de4e1e3-2bdd-4dbd-ac46-8186d7f25468.png)

In the example above, only the two matching record would be compared, all others would be ignored and therefore the test would be successful.

**Comment by Seddryck** [comment]
Ok, I'll apply a fix in this case to align with the documentation.
