### ISSUE TITLE
Ignore footer in CSV file

### ISSUE THREAD

**Issue by michalkleta-gain** [Seddryck/NBi#708]
Hi,

In my test I'm trying to compare query result with CSV. Is there an option to ignore the footer in CSV file - similar to first-row-heafer="true" in csv-profile maybe?

**Comment by Seddryck** [comment]
No it doesn't exist.

Parsing of the CSV file is done with [PocketCsvReader](https://github.com/Seddryck/PocketCsvReader). You can take a look to this tiny project and check if you can implement this into this project. But TBH, skipping the last lines of a file will require to know that it's the last lines which could be tricky.

**Comment by michalkleta-gain** [comment]
Thank you for your answer. I'll try to find some workaround then.
