### ISSUE TITLE
Genbil - substring replace?

### ISSUE THREAD

**Issue by fefeslon** [Seddryck/NBi#714]
Hi All,

Is it currently possible to make substring replace in the Genbil?

E.G. 
Imagine you have objects like dim_prod, fact_sales etc.. 
Each environemnt (TST, PRD.) has its own suffix on objects like: dim_prod_tst, dim_prod_prd
I would like to get list of "general" object name like dim_prod, fat_sales and then apply this to template.

https://www.nbi.io/automation/column-replace/

Is it possible to replace just suffix/prefix/substring somehow?

If not, could it be added please or is it too much effort?

Cheers,

Michal.

**Comment by Seddryck** [comment]
Using [substitute](http://www.nbi.io/automation/column-substitute/) you should be able to substitute the dim_ of dim_product by dim_prod which should end into dim_prod_product.

**Comment by fefeslon** [comment]
Ah cool, thanks Cedric.

I haven't noticed it in the documentation.
