### ISSUE TITLE
Failures' report

### ISSUE THREAD

**Issue by allurusrinivasulu** [Seddryck/NBi#720]
Hi Seddryck,

I am using the following code, but I am not getting all the records set. It has been displayed only 1617 records out of 1858251 records in analysis-set. Could you please provide the maximum number of records that will be displayed in the analysis-set?
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nbi" type="NBi.NUnit.Runtime.NBiSection, NBi.NUnit.Runtime"/>
  </configSections>
  <nbi testSuite="Testssuite1.nbits">
	<failure-report-profile
        threshold-sample-items="2000000"
        max-sample-items="10"
        expected-set="None"
        actual-set="None"
        analysis-set="Full"
    />
 </nbi>
</configuration>

```

**Comment by Seddryck** [comment]
Analysis set only contains records not validating the test.

**Comment by allurusrinivasulu** [comment]
Thankyou for quick response seddryck.  I am getting full list of the failure report after executing it using  bat file script result will be saved in the text file.
