### ISSUE TITLE
Load result-sets from xml files

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#73]
Currently, result-sets can be defined in an external file, embedded in the test-suite or are the result of a query. It should be possible to also load from an xml file. 

When done, it should be possible to implement "Compare a report to an atom feed" #41

**Comment by Seddryck** [comment]
``` xml
<equalTo>
     <xml-source>
          <file>..\PurchaseOrders.xml</file>
          <xpath>
            <from>//PurchaseOrder/Items/Item</from>
            <select attribute="PurchaseOrderNumber">../..</select>
            <select attribute="PartNumber">.</select>
            <select>../../Address[@Type="Shipping"]/City</select>
          </xpath>
        </xml-source>
</equalTo>
```

**Comment by Seddryck** [comment]
The xpath expression is transforming the hierarchical structure of an xml file into a tabular structure. Each _select_ is translated to a column. The granularity is given by the _from_ clause.

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99046

**Comment by Yingmin-Li** [comment]
Is this feature still available in current version 1.13.0.18?

If not, will you consider to continue with it in the future?

**Comment by Seddryck** [comment]
Yes, it is available. What do you think is missing in this implementation?

**Comment by Yingmin-Li** [comment]
I found the test example in this document (https://github.com/Seddryck/NBi/blob/master/NBi.Testing/Acceptance/Resources/Positive/QueryEqualToXml.nbits)

But it seems to compare only one row value with that in XML file in one test case. We also create other test case by using DB query, but only the query of selecting one row works.

Did I make mistake?

Is that the case: we can only test one row in one test case?
