### ISSUE TITLE
Add support for testing members of a set

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#83]
Currently it's not possible to validate the members of a set (contain, subset, equivalentTo).

**Comment by Seddryck** [comment]
```
<test name="The set Large Resellers contains at least some items" uid="0099">
    <system-under-test>
      <members>
        <set caption="Large Resellers" perspective="Adventure Works"/>
      </members>
    </system-under-test>
    <assert>
      <contain>
        <item>Bicycle Lines Distributors</item>
        <item>Certified Sports Supply</item>
      </contain>
    </assert>
  </test>
```

**Comment by chifaanfar** [comment]
Hey seddryck !!
i Try to check the existence of one member in a given  level , so when i run my template , the value to caption is blank .
![probl](https://user-images.githubusercontent.com/37936281/39697085-3c940186-51df-11e8-8f44-17832b3b36a9.png)

thanks in advance :D

**Comment by chifaanfar** [comment]
Hey Seddryck !!
I try to check the existence of one member in a given level , so when i execute my test with my template , the member value to caption is blank , any help please 
![probl](https://user-images.githubusercontent.com/37936281/39697300-001754dc-51e0-11e8-8b27-111825cae81e.png)
 thanks in advance

**Comment by Seddryck** [comment]
Please don't post on closed items except if you want to comment on a unfixed bug. I duplicated your post in #369
