### ISSUE TITLE
Incorrect handling of special characters in queries from file

### ISSUE THREAD

**Issue by TheAutomatingMrLynch** [Seddryck/NBi#90]
Hi Seddryck,

I have an MDX query saved as file which contains special characters (It's part of some of the members names, not their technical names). The query it written and saved using SSMS from where the query works (=has results). If I run the query file from a test suite, the special characters are somehow "converted" to square characters and the result set is empty. 
In SSMS profiler the two queries are identical except for these characters - no parameters or anything fancy. The characters include Æ, Ø, Å and accents as well. 

Kind regards 
Bjarne

**Comment by Seddryck** [comment]
Hi Bjarne,

It could be linked to the encoding of your file. NBi is expecting files encoded in UTF-8, yours is probably encoded in ANSI. Just open your file with SSMS and select "Save as" then use the small drop down near the button save with encoding ...
![ssms-save as](https://cloud.githubusercontent.com/assets/5455045/8499271/64c1589c-2191-11e5-889e-bd5c7d4b6ce1.PNG)
Then select the Unicode value (see screenshot)
![ssms-save as unicode](https://cloud.githubusercontent.com/assets/5455045/8499301/d1a8fca8-2191-11e5-9b3f-b80c4045fac9.PNG)

If it doesn't resolve your problem tell me.

**Comment by TheAutomatingMrLynch** [comment]
Silly me. Must be the heat or something. :-)
Thanks for the quick reply.
