### ISSUE TITLE
Configuration of failures' report can not be updated.

### ISSUE THREAD

**Issue by cissi2015** [Seddryck/NBi#98]
NBi is a cool tool and I am new to it. I installed version 1.10 and compared DB tables on different servers. Things go well but I would like a better failure report with all the differences of two tables are listed on it. So I change the configuration file by adding element "failure-report-profile".
 Here is my new config file.
![nbi config](https://cloud.githubusercontent.com/assets/13541791/8936749/ed8116e0-354b-11e5-9bb4-ce90ef6d3cee.jpg)

I rerun the tests however I still can only see the first 10 rows of a result-set as default one on TestResult.xml.

Please could you help me figure out what is going wrong.
Many thanks.

**Comment by cissi2015** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
                <configSections>
                                <section name="nbi" type="NBi.NUnit.Runtime.NBiSection, NBi.NUnit.Runtime"/>
                </configSections>
                <nbi testSuite="MyFirstTestSuite\MyFirstTestSuite.nbits">
     <failure-report-profile
        max-sample-items="10"
        threshold-sample-items="15"
        expected-set="sample"
        actual-set="sample"
        analysis-set="sample"
                                />
    </nbi>
                </configuration>

**Comment by cissi2015** [comment]
![nbi config](https://cloud.githubusercontent.com/assets/13541791/8936729/cb5a347a-354b-11e5-9f32-575f65c05d10.jpg)

Display issue of xml on original request.

**Comment by Seddryck** [comment]
It's a bug somewhere in the framework. I'll check this next week and provide a fix.

**Comment by cissi2015** [comment]
Thanks for your quick feedback.

**Comment by Seddryck** [comment]
Could you try using "Sample" with a "s" uppercase in place of lowercase. I think it will solve your issue. If it's OK, I'll fix the documentation.

**Comment by cissi2015** [comment]
Hi Seddryck. Still not working for me. No matter I add element "failure-report-profile" or not, TestResult.xml is always the same. I'm sure I have more than 10 differences. Please advise. Thanks.

**Comment by Seddryck** [comment]
Hi @cissi2015, huum that's possible I haven't tested exactly what you're trying. Will investigate further this week-end.

**Comment by Seddryck** [comment]
I've finally found why unit tests were successful but it didn't work with the GUI of NUnit. It's now resolved. You can download the binaries at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99031

Don't forget also that it should be Full, None and Sample with an uppercase.

If you confirm it's working for you, I'll close the bug and add this to the master branch.
